### ISSUE TITLE
Auto play when opening file not working

### ISSUE THREAD

**Issue by Snipe3000** [clsid2/mpc-hc#216] opened 2020-01-05 06:07 UTC
I updated to the latest mpc-hc today and the first thing I noticed is that when I open a video file, it no longer auto plays. I have to hit the play button to get the video going. 
When the "play next file in the folder" option is set, the problem happens there as well. It wont play the next file, it will open the next file, then pause.

Anyone know a workaround for this?

**Comment by clsid2** [comment] 2020-01-05 18:35
Options > Miscellaneous > Reset

**Comment by Snipe3000** [comment] 2020-01-05 18:54
I'll give that a try, setup will take some time. I should screenshot all pages, I've customized the settings quite a bit.

**Comment by adipose** [comment] 2020-01-05 22:35
You could export the settings and upload them here.

**Comment by Snipe3000** [comment] 2020-01-06 00:08
Thats a good idea. I zipped it up and attached it here. Does anyone see anything that would cause 
this issue before I do the ole clean wipe?

[mpc-hc-settings.zip](https://github.com/clsid2/mpc-hc/files/4024280/mpc-hc-settings.zip)

**Comment by adipose** [comment] 2020-01-06 02:32
I will try these settings tonight, but you can reset sooner if you like.

**Comment by adipose** [comment] 2020-01-06 05:39
I imported those settings, and autoplay is still working for me. It may be something else.

**Comment by clsid2** [comment] 2020-01-06 15:14
Could be something in the filter chain that is causing this.

madVR has an option to delay playback start until queue is full. Maybe that isn't working correctly.

**Comment by Snipe3000** [comment] 2020-01-07 10:31
After trying to narrow down the cause for a while, it looks like the latest mpc-hc has an issue with auto-play on a secondary screen. I usually watch stuff on a second monitor. When the video is on my primary screen the auto-play feature works fine.

**Comment by clsid2** [comment] 2020-01-08 15:12
It is most likely an issue in the renderer. Try with EVR-CP.

**Comment by Rarurin** [comment] 2020-01-15 11:04
Are you perhaps using the dark theme in mpc-hc? i noticed the same thing was happening to me some weeks ago when i tried using the dark theme. At first i thought it was some kind of different "bug" with the player, but after thinking about it some mins, i tried disabling the dark theme as it was the only thing i changed recently, and... voila, autoplay was working again properly. And right now after reading this i tried switching the renderer from madVR to EVR-CP while using the dark theme and... voila, autoplay working properly as well. I've also a multimonitor setup and i usually play things on the secondary one, with madVR as the renderer (delay playback start until queue is full is disabled).

So, i would venture to guess it's some sort of "incompatibility" with the dark theme and madVR, for whatever reason, go figure...

**Comment by clsid2** [comment] 2020-01-15 12:57
@adipose, I can reproduce now: Dark theme enabled + madVR + remember window position (to open on secondary monitor). It doesn't happen every time, so several tries may be needed.

I noticed that it does the sequence Pause>Pause>Play at playback start. But only with madVR and only with dark theme, and only on secondary screen.

**Comment by clsid2** [comment] 2020-01-15 12:59
@madshi

**Comment by madshi** [comment] 2020-01-15 17:35
May be related to madVR's "delay playback start until render queue is full" option? Try disabling it.

**Comment by clsid2** [comment] 2020-01-15 18:18
Already disabled. It happens with completely default madVR settings (full reset). It sometimes takes 10 or more tries to trigger the issue.

I did some logging with DirectShowFilterSpy, and when the problem occurs the log shows that IMediaControl::Pause returned value 1, while in the good cases it returned 0.

I think that return value means that you must call IMediaControl::GetState to wait until the state transition is complete?
https://docs.microsoft.com/en-us/windows/win32/api/control/nf-control-imediacontrol-pause

Filter Spy: http://alax.info/blog/777

**Comment by madshi** [comment] 2020-01-15 19:09
Why would I call Pause(), though, if the "delay playback" option is off? Normally, there are only very few situations where I call Pause(). Ok, maybe if playback moves to another monitor, I'm not sure.

**Comment by adipose** [comment] 2020-01-15 19:52
@clsid2 

I will take a look tomorrow.  Nothing comes to mind related to the theme, but clearly it's broken it somehow.

**Comment by Snipe3000** [comment] 2020-01-15 19:53
Yeah looks like it is the dark theme. Thats a shame, I really liked it.

**Comment by clsid2** [comment] 2020-01-15 21:54
Playback does not move to another monitor. The player is opened directly on secondary screen. But I suspect there may be a bug in the dark theme that somehow makes madVR think the window was moved. So triggering the pause is the player's fault. But I think the failure to resume is a bug in madVR.

**Comment by madshi** [comment] 2020-01-15 22:18
Yeah, madVR doesn't like it too much if the rendering window moves from one monitor to another. It requires a full rebuild of all the rendering stuff, and although that usually works, it's a lot of extra work, and also causes delays. So fixing dark theme to not result in a monitor change should also speed madVR up, besides possibly solving this problem.

But yeah, this looks like a bug in madVR. No time to work on that atm, though...

**Comment by adipose** [comment] 2020-01-16 18:39
@clsid2 @madshi 

This is really weird.  I can't get it to fail, but I can see it going through pause/play cycle.  Dark theme doesn't send any display changed notifications.  One possibility is, it is slower to initialize, causing the renderer to start at a different timing vs the frame init.  Not sure.

I'll keep checking it.

**Comment by adipose** [comment] 2020-01-16 18:47
This may be related.  I have observed that the madvr OSD is not working on the second screen, but only when dark theme is enabled.

**Comment by adipose** [comment] 2020-01-17 05:30
@clsid2 @madshi @Snipe3000 

This should fix it:

https://mega.nz/#!RYJxnKBL!lgBsTcMwSA2Dyz_KVBRquaGlvUhvLYXQu3SZ1jMAPwI

Problem was an invisible window being created during my tooltip "optimization" code. Normally it creates a window and shows it without activating (SW_SHOWNOACTIVATE).  But on Win32 tooltip creation, the window is created initially with a position of 0,0,0,0.  The helper window clones the position, which at 0,0 would often be on the primary monitor.  This could cause the application (madvr) to think the current monitor had changed.

If the tooltip window is sizeless, I now do not create the helper at all.  It seems to fix all the issues I could observe (I only saw it stay paused once out of 100s of tries, but the play/pause/play thing happened every time).

**Comment by madshi** [comment] 2020-01-17 10:18
Awesome - thanks for the fix!  :-)

FWIW, the ideal approach would be to create the madVR instance and immediately assign the parent window, before even connecting the pins (!), so that madVR knows immediately which monitor it's supposed to render on. Otherwise it has to guess, and that can cause issues like this. E.g. like this:

1) CreateFullScreenWindow
2) CoCreateInstance(madVR)
3) CoCreateInstance(FilterGraph)
4) FilterGraph->AddFilter(madVR)
5) madVR->IVideoWindow->put_Owner(FullscreenWindow)
6) CoCreateInstance(LAV)
7) FilterGraph->AddFilter(LAV)
8) Connect pins.
9) Start playback.

**Comment by adipose** [comment] 2020-01-30 05:07
@madshi 

Note this bug did not require a fullscreen window, just a different monitor than the main monitor.  Here's the call stack when auto-playing:

![image](https://user-images.githubusercontent.com/3324395/73421468-d3af3480-42da-11ea-8604-0c7122354acf.png)

Is the following parameter significant?

![image](https://user-images.githubusercontent.com/3324395/73421479-dca00600-42da-11ea-8d65-f5e21f5513a6.png)

Perhaps it could ask the main thread for the main window and set it here.  I'm not sure why it would have to set the owner after adding the filter.

**Comment by madshi** [comment] 2020-01-30 08:15
That code confuses me. CoCreateInstance is a win32 API which has 5 parameters. See here:

https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-cocreateinstance

I don't understand why it only has 2 parameters in your code, and why it's a method of "m_pMVR". Maybe m_pMVR is a helper class which has a method called "CoCreateInstance"? If so, I'm not sure what purpose the 2nd prameter has. Maybe it's used to call "madVR->IVideoWindow->put_Owner()"?

Also, I don't know "GetOwner()", it doesn't appear to be a win32 API. Ideally you should pass the window to "madVR->IVideoWindow->put_Owner()" which you want madVR to render on. I'm not sure if "GetOwner()" does that? Maybe you have a better way to find the window handle you want madVR to render on?

**Comment by adipose** [comment] 2020-01-30 15:56
Here's a screen cap to answer some of that.  It comes from atlcomcli.h

![image](https://user-images.githubusercontent.com/3324395/73465923-f91d5c00-4335-11ea-91ec-ce2873653a06.png)

**Comment by adipose** [comment] 2020-01-30 15:59
I checked, and GetOwner() here is just returning a reference to CmadVRAllocatorPresenter instance.

**Comment by madshi** [comment] 2020-01-30 16:38
Ah ok, in that case this doesn't seem relevant to this problem. Maybe you can search for "put_owner"? That's the place where MPC informs madVR about which window to render on.

**Comment by adipose** [comment] 2020-01-31 05:23
Check out this comment:

![image](https://user-images.githubusercontent.com/3324395/73514486-c3648b80-43a6-11ea-9803-f8b903677892.png)

**Comment by adipose** [comment] 2020-01-31 05:52
In testing, this code didn't get called due to the if statement failing.  Instead, it gets set the same place as other renderers, in OpenSetupVideo() in the MainFrm.cpp.

I do wonder if the loop here is causing issues by enabling windows after setting the owner:

![image](https://user-images.githubusercontent.com/3324395/73515614-cd888900-43aa-11ea-8cd1-6aa98e97be4b.png)

**Comment by madshi** [comment] 2020-01-31 07:59
It looks like you're analyzing exactly the right code location. Could you try to find out why the if statement fails? I think the original issue might be solved if you solve the issue with the failing if statement.

**Comment by adipose** [comment] 2020-02-01 03:11
I got it working, now.  The interface for IVideoWindow depends on the renderer (m_pMVR) being inititalized, which it isn't at that point.  I moved the call down to after renderer initialization, and now it works.

The other setOwner call is still happening, though.  Not sure if it will still cause problems.

Here is a test build, if you have some way of testing whether this works better.

https://mega.nz/#!EVAl2YjR!gAtN6FSuQrwkiWyNfEZzu9e9yjodgeAnRGY2a7oeBIo

**Comment by adipose** [comment] 2020-02-01 05:59
Other changes to that dialog include the table filter.  That patch has a fix to kill the timer, which shouldn't hurt anything (fixes a bug).

**Comment by madshi** [comment] 2020-02-01 08:33
Happy to hear you got it working! So does it help fix the original issue(s) in this thread? At least it should generally help streamlining things in dual monitor situations. That's assuming the window handle you send to madVR is already on the correct monitor in that moment, right?

Calling put_owner multiple times shouldn't hurt, especially if it's the same window.

(I'm sorry, I'm currently extremely busy getting the Envy ready for production/sales, so I can't really do practical tests atm.)

**Comment by adipose** [comment] 2020-02-01 23:45
> So does it help fix the original issue(s) in this thread?

Yep!  I can remove my fix and with this change, the problem is still gone.  Leaving my fix in, though, too.

https://github.com/clsid2/mpc-hc/pull/258

**Comment by madshi** [comment] 2020-02-02 09:43
Great!  :-)

**Comment by adipose** [comment] 2020-02-02 16:57
@clsid2 , I think we can close this one.

**Closed as completed** 2020-02-02 22:12 UTC

**Comment by Snipe3000** [comment] 2020-07-24 23:50
Looks like this issue came back in a recent release. Auto play doesn't work on a secondary screen/monitor.

**Comment by clsid2** [comment] 2020-07-25 00:32
Works here.

**Comment by Snipe3000** [comment] 2020-07-25 00:49
Hmmm, it only works for me when the media player is on the primary monitor. Are you using MadVR?

**Comment by clsid2** [comment] 2020-07-25 01:17
Yes, same test as before.
Dark theme + madVR + remember window position to open on secondary monitor

Test older versions, and also this development build:
https://github.com/clsid2/mpc-hc/releases/download/1.9.6.7/MPC-HC.1.9.6.28.x64.zip

**Comment by Snipe3000** [comment] 2020-07-26 03:51
I tried the development build, but the same issue. Auto play doesn't work 90% of the time on the second screen.
So I started going backwards, trying old builds. 1.9.1 was the last build for me that works all the time. When 1.9.2 came out auto play on the second screen stopped working properly.

**Comment by adipose** [comment] 2020-07-26 04:33
@Snipe3000 I wonder if it has to do with this feature:

-- When player is minimized it now stays minimized when adding files to playlist from Explorer

This was a small change to keep the app from re-maximizing when it had been hidden.  I can't think of why this would affect you, but exactly how are you launching it, just to be sure?

**Comment by adipose** [comment] 2020-07-26 04:56
Interesting that 1.9.1 was the last good one.  This fix for madvr wasn't added until 1.9.2:

https://github.com/clsid2/mpc-hc/commit/7330e0d85856b30c1877104b49579bcc8d43b92c

**Comment by Snipe3000** [comment] 2020-07-26 04:58
I usually play a file one of 3 ways. mpc-hc is my default app for video files, so I'll just double click a file. Another way is, sometimes I'll drag a vid file over to a already open mpc-hc instance. And the most common way I open video files is with the After playerback - 'Play next file in the folder' feature.
All options I described are affected by this issue. The player is always on the secondary screen, and dark mode is on.

**Comment by adipose** [comment] 2020-07-26 05:41
https://mega.nz/file/AAY0FapD#VS-Z-ftK7bQ1Y5WC7ZpJ4Fhaixip6x88pwyehmQCTkg

Try this test build.

**Comment by Snipe3000** [comment] 2020-07-26 06:07
It seems that one works fine

**Comment by adipose** [comment] 2020-07-26 13:09
Hmm. Well, I reverted https://github.com/clsid2/mpc-hc/commit/7330e0d85856b30c1877104b49579bcc8d43b92c

I guess that fix has an unintended side effect for you.

**Comment by adipose** [comment] 2020-07-26 14:27
So, I was never able to reproduce the original issue, but the play/pause/play cycle was fixed first by a change in tool tip creation. Then taking @madshi suggestion, I "fixed" code that allowed window assignment before connecting pins. That hasn't caused any problems for me or @clsid2. By removing the first put_owner call, the problem goes away. Makes me think the second call is for a separate monitor.

**Comment by clsid2** [comment] 2020-07-26 15:22
Can you make a test build without the revert and with tooltips disabled? I am curious if tooltips is still what triggers the bug.

**Comment by adipose** [comment] 2020-07-26 16:11
Yes, also maybe he can test without dark theme.

**Comment by adipose** [comment] 2020-07-26 20:29
https://mega.nz/file/FMA0mCJJ#lTvr-CcaxYrujsE1H77n8CzJkf3NZNbyu1fRqt_6o8U

Can you please test this build?  This build has no themed tooltips at all.

**Comment by adipose** [comment] 2020-07-27 13:29
My current theory is if the monitor changes after put_owner, it will pause video. 

The tooltip issue made a monitor switch after the second call. The less common issue is now caused by the first call (which, until I fixed it, never occurred) succeeding, perhaps before monitor selection.

**Comment by madshi** [comment] 2020-07-27 14:01
Yes, a monitor change could potentially result in a paused video. I've always said that the best approach is to initialize madVR in such a way that it knows from the start which monitor it's supposed to render on. If there's a monitor change, madVR has to close and recreate a *LOT* of Direct3D related interfaces, which even if it works correctly will cause an initialization delay. So making sure madVR is initialized for the correct monitor will result in video playback starting faster.

**Comment by adipose** [comment] 2020-07-27 18:19
Right, I understand that.  I don't think either of the put_owner calls has any requirement to be done before monitor restore occurs.  That probably is the real issue, so maybe we can find some way to do the restore earlier.  It's unclear why this doesn't affect some and does others.  Makes me think it's a performance issue of some kind, but not sure.

**Comment by Snipe3000** [comment] 2020-07-27 18:58
> https://mega.nz/file/FMA0mCJJ#lTvr-CcaxYrujsE1H77n8CzJkf3NZNbyu1fRqt_6o8U
> 
> Can you please test this build? This build has no themed tooltips at all.

This build works as well. With dark mode on.

**Comment by adipose** [comment] 2020-07-27 19:00
Thanks--can you confirm the current release works if you disable the dark theme?

**Comment by Snipe3000** [comment] 2020-07-27 19:18
1.9.6 has the same problem, even with dark mode off.

**Comment by adipose** [comment] 2020-07-27 19:28
That is really weird.  The dark theme off should deactivate anything custom.  I wonder if this is related to the late initialization of the appsettings.  Let me try something.

**Comment by adipose** [comment] 2020-07-27 19:31
Sorry, I just realized I made a mistake.  The fix wasn't removed when I rechecked out the branch, so that test without tooltips was not a valid test.  Doing it again--

**Comment by adipose** [comment] 2020-07-27 19:40
Ok, try this build, now:

https://mega.nz/file/MApEAKpR#umpw4Fxxr-fs3LiF0uYAXlervIT2GHDg0h0FsquUM9I

**Comment by Snipe3000** [comment] 2020-07-27 19:54
> Ok, try this build, now:
> 
> https://mega.nz/file/MApEAKpR#umpw4Fxxr-fs3LiF0uYAXlervIT2GHDg0h0FsquUM9I

That build still has the problem with dark mode on and off.

**Comment by adipose** [comment] 2020-07-27 19:56
Great, that should mean tooltips are not the issue.

**Comment by adipose** [comment] 2020-07-28 18:42
https://mega.nz/file/EcRx3SAb#jZnlcxjYFlmnVnKgKj160ehGzJWFlrcIpZxqrCbTemg

Can you test this build?  This has the latest sources, including some changes (done by clsid2) to the way dark theme is enabled.  I just want to see if it made any difference in your bug.

**Comment by Snipe3000** [comment] 2020-07-28 19:07
> https://mega.nz/file/EcRx3SAb#jZnlcxjYFlmnVnKgKj160ehGzJWFlrcIpZxqrCbTemg
> 
> Can you test this build? This has the latest sources, including some changes (done by clsid2) to the way dark theme is enabled. I just want to see if it made any difference in your bug.

Same issue with dark mode on and off in that build.

**Comment by adipose** [comment] 2020-07-28 22:30
I have no luck reproducing this issue so far.  In my testing both put_owner calls refer to the same window.  The window position is set before both of them.  But then, it doesn't fail (pause) for me, so that doesn't tell us much.

**Comment by Snipe3000** [comment] 2020-07-28 22:49
Not sure why I'm seeing different results on my setup.

**Comment by adipose** [comment] 2020-07-28 22:55
Me either, but here is a test build with a simple check built-in.  If this helps, we may have a better idea.

https://mega.nz/file/tdBzSaDa#ez4EDKfEe4Skhy2SXmqUXB7tTwuumH91k6bKJSYkp5c

**Comment by Snipe3000** [comment] 2020-07-28 23:26
> Me either, but here is a test build with a simple check built-in. If this helps, we may have a better idea.
> 
> https://mega.nz/file/tdBzSaDa#ez4EDKfEe4Skhy2SXmqUXB7tTwuumH91k6bKJSYkp5c

Same issue with that one as well.
The way I run these tests is I run the player, drag over a video file to play and observe what happens. Usually if its not going to work, I'll know immediately cause the video wont start playing. Just to be sure I'll turn on "play next file in folder feature", start the playback, and skip to the end to see what happens. I'll do that about 10 times. It will work 20%  of the time, and the rest of the time it wont. 
I'll then run the same tests on 1.9.1 just to make sure the control subject is still working. 1.9.1 always works.

**Comment by adipose** [comment] 2020-07-28 23:31
I thought you were doing auto-play, but maybe I misunderstood what that meant.  So mpc-hc is already open, and you drag a video into it?

I know the code that breaks it, but it also "fixed" a play/pause/play issue we had, which I thought was the same.  A piece of code could never run, so I fixed it so it did run, but that code seems to cause your issue.

Can you make a video of the fail behavior, if you have a chance?

**Comment by clsid2** [comment] 2020-07-29 01:16
Yes, please be very clear about what happens exactly and how to reproduce it. Does the video only end up being paused? Or does it say it is playing, but video is "stuck" at 0:00?

**Comment by adipose** [comment] 2020-07-29 01:23
One thing I observed is that addfilter was actually called after put_owner, which is contrary to @madshi instructions.  I have refacted the code a bit to allow it to run before put_owner.

Please try this test build to see if it makes any difference.

https://mega.nz/file/oIATXKAI#6z1bIbxnfAecK_3SjpCeXUcXA61U80ks3vKUfG3RY8U

Thanks

**Comment by Snipe3000** [comment] 2020-07-29 01:53
That build has the same issue.
To clarify what happens; no matter how I open the video (Drag & drop into already open player, open fresh instance by double clicking on a video file, or auto play from "play next" feature. I test them all) about 80% of the time, the video loads into a paused state at 0:00 or where ever I last had stopped that video, because I use the "Remember file position" feature.

**Comment by Snipe3000** [comment] 2020-07-29 04:45
playing around with it a bit more. It looks like video plays for a about a quarter of a second, and then pauses itself.

**Comment by clsid2** [comment] 2020-07-29 12:01
Register the debug version of madVR (http://madshi.net/madVR.zip). This will generate a log file on your desktop.

Reproduce the problem, and then close the player immediately (to keep log small). Delete the log before each attempt, so that it only contains the session with the bug.

Zip/rar the log file and attach it here.

**Comment by adipose** [comment] 2020-07-29 12:38
I did observe the settings attached a while back had it minimizing to the tray. Any chance it is never fully closed but just minimized to tray?

Could you attach latest mpc settings?

**Comment by adipose** [comment] 2020-07-29 19:19
Just for @madshi and @clsid2 reference, here's what I've tried so far and the results for @Snipe3000 

1. Disable first put_owner call (in FGFilter.cpp) -- works
2. Disable second put_owner call if the owner is the same -- fails
3. Move first put_owner call to after AddFilter called -- fails

My guess is something about @Snipe3000 settings causes the second put_owner to use a different window.  I can create a log build to see if that's true.

**Comment by madshi** [comment] 2020-07-29 21:34
Yes, that seems like the most likely explanation.

Of course this is somewhat of a madVR bug of sorts. Moving to another window should be possible, after all. But I guess it's sort of an MPC bug, as well. Even if it works it's not as clean & fast as it could be. So hopefully if you can fix it on your side, that would be great, because I'm completely drowning in work atm...

**Comment by adipose** [comment] 2020-07-29 22:52
Just observed that get_owner is returning null. So #2 test is not valid.

**Comment by adipose** [comment] 2020-07-30 00:25
And now I see that the two calls are using entirely different video windows.

**Comment by adipose** [comment] 2020-07-30 01:01
Here is a new test build.  It has some logging, so please return the logs for @clsid2 and the madvr.log from %appdata%\MPC-HC as well.  I have changed something to make it use the same video window handle for both calls to put_owner.

https://mega.nz/file/cYJjhAqZ#NqAxeti0dJeQhCXBmblhvY3R8en9wr2pQeYJXXqU-sk

**Comment by adipose** [comment] 2020-07-30 01:14
@clsid2, here is where I changed it (MainFrm.cpp):

![image](https://user-images.githubusercontent.com/3324395/88869142-de358280-d1c6-11ea-876b-bd8829f78c46.png)

Previously it is set to m_pGB. I don't know if this is right or wrong.  But setting it to m_pCAP gives a different IVideoWindow object.  Which means, the first call and the second call of put_owner are achieving different things.  Maybe intentionally, I don't know.  Previously the first call failed, which meant put_owner never happened at all via m_pCAP.  That hardly mattered except on a different screen.  Once fixed, apparently we got this new issue, which is rare.

I could also do a put_owner on both at this point in the code to see if it helps.

**Comment by Snipe3000** [comment] 2020-07-30 05:00
Will running the install.bat in the debug version of madvr register it?

**Comment by adipose** [comment] 2020-07-30 05:03
I think you should extract it to a folder. Run the install.bat and leave the folder there.

**Comment by clsid2** [comment] 2020-07-30 12:04
The ZIP contains both normal and debug version. You can use the "install.bat" (right-click > run as admin) and then "activate debug mode.bat"

**Comment by clsid2** [comment] 2020-07-30 15:05
> 
> 
> @clsid2, here is where I changed it (MainFrm.cpp):
> 
> ![image](https://user-images.githubusercontent.com/3324395/88869142-de358280-d1c6-11ea-876b-bd8829f78c46.png)
> 
> Previously it is set to m_pGB. I don't know if this is right or wrong. But setting it to m_pCAP gives a different IVideoWindow object. Which means, the first call and the second call of put_owner are achieving different things. Maybe intentionally, I don't know. Previously the first call failed, which meant put_owner never happened at all via m_pCAP. That hardly mattered except on a different screen. Once fixed, apparently we got this new issue, which is rare.
> 
> I could also do a put_owner on both at this point in the code to see if it helps.

Yes, I can confirm the second call is different object (filter graph manager). The documentation says it is supposed to forward the call to the video renderer.
https://docs.microsoft.com/en-us/previous-versions/ms786972(v=vs.85)
It also says it should be reset to NULL before releasing the graph manager. We aren't doing that yet.
https://docs.microsoft.com/en-us/previous-versions/ms786984(v%3Dvs.85)

**Comment by adipose** [comment] 2020-07-30 16:59
Interesting.  Since we can get the m_pCAP pointer and send/set it there, maybe that's cleaner?

Note that the first get_Owner gets NULL above, and the second does not.  So, it doesn't seem to hold the same data, depending on the pointer?

**Comment by clsid2** [comment] 2020-07-30 18:15
Calling set_Owner directly on madVR (first call) does not forward that call to the graph builder (only other way around). So it is correct that get_Owner returns null before it has been set.

I think our current code is correct. The window handle is the same here for both calls to put_Owner. So question is does the window change for Snipe3000, and if so, why?

The logs from Snipe3000 will hopefully give some more information about what is happening.

**Comment by adipose** [comment] 2020-07-30 19:19
I made another logging build with that change removed:

https://mega.nz/file/hUIzhAqL#M04T2m263OoMPxKkGLCRdSwi4iR7iJcrshy0K8NZzmw

Test this one instead (or both if you want).

**Comment by clsid2** [comment] 2020-07-30 20:08
I have added call to "set_Owner(NULL)" before releasing the graph, as recommended by the docs.

@madshi, I have skipped this for madVR, as it causes the window to move from secondary to primary screen. You should probably make your code ignore NULL as input.

**Comment by adipose** [comment] 2020-08-02 18:50
@Snipe3000 

Hi, just checking in if you were able to collect the logs. I'm sure you have better things to do but it would help us move along (hopefully)!

**Comment by Snipe3000** [comment] 2020-08-02 19:21
I'm not able to find any logs. When I tried to activate the debug MadVR I got an "file 'madVR.ax' not found", and no log file was produced. 
In "\AppData\Roaming\MPC-HC" I see a default.mpcpl file that has the name of the previous file I played, but not log information.
Attached is my settings file.
[mpc-hc-settings.zip](https://github.com/clsid2/mpc-hc/files/5012710/mpc-hc-settings.zip)

**Comment by adipose** [comment] 2020-08-02 19:26
Did you use latest builds from me? You might have to enable logging too.

**Comment by clsid2** [comment] 2020-08-02 20:15
Options > Advanced > EnableLogging

After you have registered madVR, you can also just rename madvr_debug.ax to madvr.ax (and similar for 64bit version).

**Comment by Snipe3000** [comment] 2020-08-02 21:24
I still get the same error for activating madVR debug even after renaming the files. I turned on logging in the latest build of mpc-hc that you posted and now there is a madvr.log file in "\AppData\Roaming\MPC-HC". 
I reproduced the issue and the log is attached to this message.
[madvr.log](https://github.com/clsid2/mpc-hc/files/5013006/madvr.log)

**Comment by clsid2** [comment] 2020-08-02 22:31
You don't need to use the activate debug mode .bat if you have manually renamed the file. All that matters is that the correct .ax file has been registered.

The log from MPC-HC shows that the window handle is the same in both places. It seems very likely that the bug is in madVR.

**Comment by clsid2** [comment] 2020-08-03 12:32
@madshi
Unrelated to current topic, but here is another (rare) crash that seems to be caused by madVR:
https://drdump.com/Problem.aspx?ProblemID=587572
It sends WM_ACTIVATE message to a window that has already been destroyed (player is closing).
I can provide crash dumps if needed when you have time again for working on madvr.

**Comment by adipose** [comment] 2020-08-03 17:32
I have been able to recreate the play/pause/play cycle without tooltips causing it.  The original reason for the tooltip causing it was the creating of an empty window at (0,0), which would normally be on the "main" monitor.  Nothing about this should be problematic, but with madvr, it was.  That empty window was unneeded (though it really caused no issue other than this), so I fixed the code to eliminate it.

But I started thinking about why that would cause a problem.  All I can think of is the "active" monitor is changing from madvr's perspective, and all that would require (apparently) is a new window activating on another screen, or maybe even an existing window taking focus or becoming active (on another screen).

So, I decided to try keeping my playlist on the second monitor, with mpc-hc on the main screen.  Sure enough, the pause/play/pause cycle is back.  Since I have never been able to recreate the permanent pause problem myself, this may be a goose chase, but it still exposes that other bug in madvr.  Maybe something similar is happening to @Snipe3000 , though.

**Comment by clsid2** [comment] 2020-08-03 18:58
Good find. But I wonder why does madVR care about such other windows? In this case that other window isn't covering part of the video window.

**Comment by adipose** [comment] 2020-08-03 19:50
Maybe because madvr's parent loses focus?

**Comment by Snipe3000** [comment] 2020-08-03 20:41
I tested the playlist thing as well. Yeah, having the playlist on the main screen fixes it. Odd

**Comment by adipose** [comment] 2020-08-03 20:43
Interesting, but typically you have the pl on the same screen as the player?  What if you entirely hide the pl?

**Comment by adipose** [comment] 2020-08-03 20:52
Around the time the focus change happens is when I see the pause occur.  Hard to pinpoint exactly.  The focus lost was from the main window to the video window (madvr parent/owner).

![image](https://user-images.githubusercontent.com/3324395/89225627-5fa65f80-d58f-11ea-8605-a1f5871964ad.png)

```
13:32:38.261 - CFGFilterVideoRenderer::Create: [0]m_hWnd = 10a00, curOwner = 0, activeWindow= 109d8,focusWindow= 10a00, b=1, d=b58 (C:\dev\mpc-hc\src\mpc-hc\FGFilter.cpp:530)
13:32:38.262 - CFGFilterVideoRenderer::Create: [1]m_hWnd = 10a00, curOwner = 10a00, activeWindow= 109d8 (C:\dev\mpc-hc\src\mpc-hc\FGFilter.cpp:533)
13:32:38.812 - CMainFrame::OpenSetupVideo: [0]m_pVideoWnd->m_hWnd = 10a00, m_pVW curOwner = 0, hr=0, activeWindow= 109d8 (C:\dev\mpc-hc\src\mpc-hc\MainFrm.cpp:12216)
13:32:38.812 - CMainFrame::OpenSetupVideo: [1]m_pVideoWnd->m_hWnd = 10a00, m_pCAP curOwner = 10a00, hr=0, activeWindow= 109d8 (C:\dev\mpc-hc\src\mpc-hc\MainFrm.cpp:12219)
13:32:38.812 - CMainFrame::OpenSetupVideo: [2]m_pVideoWnd->m_hWnd = 10a00, m_pVW curOwner = 10a00, hr=0, activeWindow= 109d8 (C:\dev\mpc-hc\src\mpc-hc\MainFrm.cpp:12222)

```

**Comment by Snipe3000** [comment] 2020-08-03 21:57
> Interesting, but typically you have the pl on the same screen as the player? What if you entirely hide the pl?

I've never used the playlist. this is the first time I've ever opened it up.

**Comment by adipose** [comment] 2020-08-03 22:08
OK, and do you have any floating toolbars or just the main MPC-HC window?

**Comment by adipose** [comment] 2020-08-04 00:39
Another idea.  Do you have this setting set in madvr?  I notice it has the effect of starting the video paused.

![image](https://user-images.githubusercontent.com/3324395/89240147-1c101d80-d5b0-11ea-9ec8-1b30dac20172.png)

Also if you can export your madvr settings.  (Computer\HKEY_CURRENT_USER\SOFTWARE\madshi)

**Comment by adipose** [comment] 2020-08-04 01:38
Another test build based on updates from @clsid2 .  I also added a line to put the message drain before pins.  Maybe not having the message drain while having the owner is a problem.  It didn't seem to hurt anything for me.

https://mega.nz/file/MMhhyIRZ#DyV0RpxFRZKWec-QEvuzM6V4wmyzG_5YPOM0JI0zNwU

**Comment by Snipe3000** [comment] 2020-08-04 04:09
I do not have the delay playback setting checked.
I tried that latest build, but the same problem.
Attached is my MadVR settings.
[MadVR.zip](https://github.com/clsid2/mpc-hc/files/5020033/MadVR.zip)

**Comment by adipose** [comment] 2020-08-04 14:44
Thanks.  I have tested using your settings for madvr and mpc-hc (an older one you uploaded--maybe you can upload your latest just to be sure).  I cannot reproduce this at all on the second monitor.  With some work I can bring back the play/pause/play cycle, but that's just a glitch that doesn't leave it completely paused.

Without an update from @madshi I'm afraid it's unlikely we will be able to fix this, but if @clsid2 likes the idea, I could add an advanced option to disable the early put_owner call, which seems like it would solve your issue at least (possibly brings back the bug we experienced, but that's minor compared to a full pause).

I'd still like it if you could provide a video of the full experience so I can see if I'm missing anything.  Also if you could confirm your hardware, and OS versions.

**Comment by adipose** [comment] 2020-08-04 14:51
@clsid2 

An existing madvr window is getting this pause request event when I play a second video (nothing was playing).  Then the madvr window is destroyed.  I wonder--maybe somehow the pause request can go to the wrong (new madvr) window?

![image](https://user-images.githubusercontent.com/3324395/89308594-4c46d300-d627-11ea-9195-00b4d2356f54.png)

**Comment by clsid2** [comment] 2020-08-04 19:50
Lets wait until madshi can take a look at this issue.

**Comment by madshi** [comment] 2020-08-05 21:16
No time atm. So sorry, guys. Completely burried in work...  :-(  But I'll keep this in my inbox.
