### ISSUE TITLE
Save Image position

### ISSUE THREAD

**Issue by joaoandre120** [clsid2/mpc-hc#882] opened 2021-02-06 17:16 UTC
Hello, 
I use mpc to watch on a second monitor (its configurated to fullscreen on Display2) . 
Previous versions the save image window used to save its position on Display1, but now its opening on the Display2 when in fullscreen.
I don't know wich version it started. 
I tried the last version MPC-HC.1.9.8.157.x64.

![Screen Shot 02-06-21 at 02 09 PM](https://user-images.githubusercontent.com/7441934/107124969-95e9d200-6885-11eb-93b7-3dbe73765139.PNG)
![Screen Shot 02-06-21 at 02 08 PM](https://user-images.githubusercontent.com/7441934/107124970-9aae8600-6885-11eb-9f2a-f1f8e4918f42.PNG)

**Comment by adipose** [comment] 2024-02-20 07:54
@clsid2 

Bug confirmed.  It is caused by `PerMonitorV2` setting introduced in 1.9.8.26.  There must be a side-effect of per-monitor DPI and opening the dialog on the same monitor as the parent window.

A workaround is fullscreenseparatecontrols, as the parent window is now on the "main" monitor instead of the fullscreen monitor.  The save dialog then shows up on that screen instead.

If this is worth fixing, I have researched how it can be done.  In the windowproc we can trap the WM_WINDOWPOSCHANGING and call SetWindowPos.  We could save the last position or simply center it on the other monitor.  Code is already present to trap these dialogs just because it is necessary to theme the added controls sometimes.

**Comment by adipose** [comment] 2024-02-20 08:21
I also found I could create a message only window as the parent which is another way to control the monitor (though not the position).

**Comment by clsid2** [comment] 2024-02-20 13:12
Maybe we should just enable fullscreenseparatecontrols by default?

**Comment by adipose** [comment] 2024-02-20 21:44
> Maybe we should just enable fullscreenseparatecontrols by default?

I'm ok with that, it's quite useful for people with two screens.  I also noticed there is a "bug" that's caused by custom fields and the save dialog moving between screens of different DPI.  Even without the custom fields, the whole thing goes nuts for 1-3 seconds as it resizes and redraws.  But with custom fields, it does a terrible job and the bottom pane resizes so large it covers the whole dialog.  This doesn't appear to be an mpc-hc bug.

So anything that keeps it on the "other" screen is worth considering in FS.

**Comment by adipose** [comment] 2024-02-24 02:27
For now I vote we close the issue.  We can make it the default if we want, but basically the behavior changed from:

Always open the save-as in the last place it was used

To

Always open the save-as on the monitor the application is on (and sort of centered on that window).

**Closed as completed** 2024-02-24 13:41 UTC
Labels: bug, PatchRequired
