### ISSUE TITLE
OpenSubtitles API update

### ISSUE THREAD

**Issue by Sp3EdeR** [clsid2/mpc-hc#1876] opened 2022-10-12 23:18 UTC
If I'm not mistaken, OpenSubtitles has deprecated its xml-rpc API (which MPC-HC is current using). They have moved over to [this REST API](https://www.opensubtitles.com/docs/api/html/index.htm). The support for the xml-rpc API will end in 2023. Just a heads-up.

**Comment by josdemmers** [comment] 2023-04-27 08:22
In addition to this, MPC is currently using the OpenSubtitles.org API which is deprecated. The new one is at OpenSubtitles.com instead.

**Comment by justnope** [comment] 2023-07-16 13:41
Is someone working working on this? Otherwise I don't mind to implement it. 

From what I gathered from the opensubtitles api docs you'll also need to request an app-id. During development I can use my own account to request one, but I think it would be better if someone made an "official" mpc-hc account at opensubtitles and use the app-id from that account for releases.

**Comment by clsid2** [comment] 2023-07-16 17:55
Nobody is working on this yet as far as I know.

**Comment by Slyceth** [comment] 2023-08-17 23:16
ARL

I would like to propose an easier solution, one that is truly future proof and already used in software like Deemix: 

Open Chrome
Go to www.opensubtitles.org and log into your account
Click on the little "lock" icon next the URL
Click on Cookies > opensubtitles.org > cookies > arl
Select the string next to Content, and Copy
That's your ARL, now you can use it in the app

Considering the API for opensubtitles might change again, and you don't rely on an "official" mpc-hc account at opensubtitles and use the app-id from that account for releases that's prone to get banned.

**Comment by monkchi** [comment] 2023-09-25 13:57
can someone please sort this out. as there isnt even a way to add my own choice of subtitle site like there used to be. but if you could please sort out opensubtitles that would be a great help as the other two dont find anything and i know the subtitles are out there for download. thanks. would like the .com one added as the .org site doesnt work even in normal browseing. and the ability to add our own sites ans there is really only one site for english in there now as the other two dont work or do english, and even the one that does have english doesnt find ANYTHING, thanks alot for any help

**Comment by justnope** [comment] 2023-09-25 17:17
The main stumbling block for me is that someone needs to create an account at opensubtitles to get an app-id that we can use in mpc.  I don't want to use my own account. If I did, it would give me access to the download statistics at that site for all mpc users. I don't want that because it feels creepy to me.

If you can sort out the account registration and who would maintain it, it would help me out a lot.

There were also some technical frustrations caused by a lack of documentation. I'll spare you the details but I got a prototype connection working... well, almost...  My anti-virus kicked in and said that site was blacklisted. This is when I gave up.

If the documentation was better and I was sure the API would only fetch text and do no other processing, I would've continued. If I was sure someone would take care of the account to manage the app-id, I would've continued searching for answers on how the API could be used to limit risks.

**Comment by clsid2** [comment] 2023-09-26 08:55
Just use your own account during development. I will setup a new account before merging if an account is really needed. I thought we only needed a (new) approved user agent. You can ask on their support forum.

**Comment by monkchi** [comment] 2023-09-26 09:32
but it points to a site that cant be loaded. so wont sign in... .org doesnt work, need it to point to .com. but cant add or edit urls like we could years ago, that function is missing now, so just stuck with the 3 that are there, and open subs doesnt work, napsi only looks for pl and never finds anything, and podnapsi never finds anything (will have to check if it is broken like open subs.org). dont know if its only my comp, but it seems that mpc hc can see the net just fine as it checks for updates.

**Comment by monkchi** [comment] 2023-09-26 09:34
justnope, i created an account. 
do u need the login and password?
i dont know what is needed to maintain as there isnt any fee as far as i can see

**Comment by clsid2** [comment] 2023-09-26 10:31
Podnapsi has always worked fine. Adding other sites which do not provide an API is not going to happen. NEVER. Parsing websites is a maintenance hell. Use external tools for that. Do not even attempt to discuss parsing websites as I will just ban you for wasting my time. I am complete fed up with random idiots who think you can magically download subs off a website.

**Comment by Sp3EdeR** [comment] 2023-09-26 13:03
I am not inclined to argue about anything, but as a tip about such problems, they can be outsourced to plugin maintainers as well. For an example of website source parsing implementations, there's qBittorrent's python-based search engine. It requires python to be installed, and the "official" scripts are in a separate repo, maintained by someone else. There is an automatic script downloader from github in the program for the "official" script set.

**Comment by justnope** [comment] 2023-09-26 16:57
> justnope, i created an account. do u need the login and password?

No, for the development I can use my own account. It only needs to be changed to a general api-key when I do a PR. The test code I've written seems to be working. Now I have to integrate it into mpc.

**Comment by justnope** [comment] 2023-10-13 07:26
Does anyone want to beta test the new opensubtitles.com interface?

Keep in mind that beta testing is a chore. If everything works then it's great. But otherwise it's going to be: "try this, or try that. Here's a new version that doesn't fix anything but hopefully will give me info where the problem is"

If anyone is still up for beta testing: 
- I can build a test/debug version you can download and try out. 
- It uses my api-key so use it and don't abuse it. I can revoke it at any time without warning.
- If things go wrong, be patient while I figure things out.

**Comment by monkchi** [comment] 2023-10-14 01:37
sure i will give it a go for u (and me :) ) i have a few files on my pc that cant find any subtitles for even though i know they are out there....

**Comment by justnope** [comment] 2023-10-14 06:51
https://github.com/justnope/mpc-hc/releases/tag/subtest

Unzip it somewhere and run it. It's possible that after running this, your processor could crawl out of your computer and try to take over your city. :)

**Comment by monkchi** [comment] 2023-10-14 07:27
ah its cool, i live in a small town so no one will notice :)

**Comment by monkchi** [comment] 2023-10-14 07:38
mimm it wont render any mkv,mp4,flac,mp3 video will do avi  do i need to do something with the lav filters? it did pick up popapsi subs though which is awesome as other version wouldnt pick up ANY subs, also its running at 1.5% or under on cpu and only 32mb ram.... so looking good

**Comment by clsid2** [comment] 2023-10-14 10:47
There have not been any changes to Podnapisi implementation. That has always worked fine, so issue was on your side.

Changes have been merged and will be in next build.

**Closed as completed by clsid2** 2023-10-14 10:47 UTC
Labels: PatchFromAnotherDeveloperRequired

**Comment by monkchi** [comment] 2023-10-15 09:05
ive tried by itself and copied over current install of hpc, but it wont play mkv or other files, only avi.. i dont know what the podnapsisi problem was as i just downloaded current hpc and had it installed on three different computers which used different internet connections. this one worked first time, but only on podnapisi... but that could be because i only ad one avi file on this comp
