### ISSUE TITLE
Subtitle doesn't scale correctly with the playback speed

### ISSUE THREAD

**Issue by Uka-Uka** [clsid2/mpc-hc#367] opened 2020-04-21 03:47 UTC
Hey! I've just noticed that subtitles don't scale correctly when you change the video playback speed, which gets really important in educational videos.

**Comment by clsid2** [comment] 2020-04-24 17:36
Duplicate of https://github.com/clsid2/mpc-hc/issues/177

**Closed as completed by clsid2** 2020-04-24 17:36 UTC
