### ISSUE TITLE
Black screen after playing one of the titles on the DVD 

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#464] opened 2020-06-15 09:29 UTC
Black screen after playing one of the titles on the DVD. It seems that mpc plays the Title Menu because I can see the hand mouse cursor. And when I click it, mpc will play the corresponding title.
![image](https://user-images.githubusercontent.com/41434272/84640976-fd38c780-af2c-11ea-9446-7ded6a2dcfbb.png)

**Comment by lifegpc** [comment] 2020-06-15 09:35
I use the 1.9.4.29
![image](https://user-images.githubusercontent.com/41434272/84641997-7389f980-af2e-11ea-80e5-446203256597.png)
And my output settings.
![image](https://user-images.githubusercontent.com/41434272/84647926-b94ac000-af36-11ea-9f13-6f8ba8e75231.png)
![image](https://user-images.githubusercontent.com/41434272/84647984-d41d3480-af36-11ea-83e8-bde598a825eb.png)

**Comment by clsid2** [comment] 2020-06-15 13:53
Disable hardware acceleration for MPEG-2 and DVD

**Comment by lifegpc** [comment] 2020-06-15 14:49
It not works.
![image](https://user-images.githubusercontent.com/41434272/84671824-65ea6900-af5a-11ea-8d30-65af47b5022d.png)
And when i click it, mpc-hc become no response.
![image](https://user-images.githubusercontent.com/41434272/84671988-97fbcb00-af5a-11ea-8d29-c2a8a0bd9178.png)

**Comment by clsid2** [comment] 2020-06-15 14:53
The DVD Navigation filter from Windows that MPC-HC uses has some bugs. I can't fix that.

You can use the Navigate menu to play the desired title on the disc.

**Comment by lifegpc** [comment] 2020-06-15 14:59
Ok, thanks.

**Comment by lifegpc** [comment] 2020-06-15 15:05
I find use navigate menu to open title menu works fine, maybe you can call this function after playing complete.

**Comment by clsid2** [comment] 2020-06-15 15:15
And Root menu is giving black screen?

**Comment by lifegpc** [comment] 2020-06-15 23:37
@clsid2 Root menu and title menu is same in this DVD.

**Comment by lifegpc** [comment] 2020-06-15 23:50
Sorry, my English is not very good, so I recorded two videos. 
[2020-06-16 07-40-56.zip(With hardware acceleration)](https://github.com/clsid2/mpc-hc/files/4783523/2020-06-16.07-40-56.zip)
[2020-06-16 07-49-07.zip(Without hardware acceleration)](https://github.com/clsid2/mpc-hc/files/4783530/2020-06-16.07-49-07.zip)

**Comment by clsid2** [comment] 2020-06-17 13:08
Can you make an ISO file from this DVD and upload it for me? Then there is a small chance I can maybe fix it. Without a sample there is nothing I can do.

**Comment by lifegpc** [comment] 2020-06-17 14:34
https://1drv.ms/u/s!Aoq8mAMlVv8Ul1tXuHPKJlDTuEwO?e=3Uy59p
I made this ISO file with AnyDVD HD by using following settings.
![image](https://user-images.githubusercontent.com/41434272/84909803-b1cb1880-b0e8-11ea-952c-5b55aba09101.png)

**Comment by Nevcairiel** [comment] 2020-06-18 22:32
The ISO works fine for me. I play the Music Video, and when its done, the menu comes back just fine.

**Comment by clsid2** [comment] 2020-06-18 22:44
Thanks for checking.

@Aleksoid1978
It seems to happen only with MPC Video Renderer.
Open disc -> intro plays -> black menu and hang.
Loading title menu from Navigate menu works ok.

**Comment by Nevcairiel** [comment] 2020-06-18 22:46
The screenshot above says he is using EVR-CP.

**Comment by clsid2** [comment] 2020-06-18 23:06
I am not able to reproduce it with EVR-CP at this moment. Although I am pretty sure I also tested EVR-CP the first time.

**Comment by lifegpc** [comment] 2020-06-18 23:07
I test it in MPC Video Renderer.
![image](https://user-images.githubusercontent.com/41434272/85080372-93a20d00-b1fb-11ea-9f19-ab5b721a3e9d.png)
![image](https://user-images.githubusercontent.com/41434272/85080478-d9f76c00-b1fb-11ea-965c-7c936c5f9ce8.png)

**Comment by Aleksoid1978** [comment] 2020-06-19 00:51
Checked in MPC-BE using EVR-CP/MPC Video Renderer, using internal DVD Decoder/LAV Video Decoder(DXVA2 Native) - in all case perfect playback, at the intro end i see menu, select "All play" and all good :)

**Comment by lifegpc** [comment] 2020-06-19 01:04
MPC-BE using EVR-CP/MPC Video Renderer works fine.

**Comment by Aleksoid1978** [comment] 2020-06-19 01:15
Show filters list in MPC-HC.

**Comment by lifegpc** [comment] 2020-06-19 01:29
Filters currently loaded:
  - Internal Audio Renderer
  - Enhanced Video Renderer (custom presenter)
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder
  - LAV Splitter Source (internal)

**Comment by Aleksoid1978** [comment] 2020-06-19 01:35
Try using system DSound audio renderer.

**Comment by lifegpc** [comment] 2020-06-19 01:37
@Aleksoid1978 which one?
![image](https://user-images.githubusercontent.com/41434272/85087567-6e6bc980-b210-11ea-83d8-db065e05ea68.png)

**Comment by Aleksoid1978** [comment] 2020-06-19 01:39
System Default or Default DirectSound Device.

**Comment by lifegpc** [comment] 2020-06-19 01:40
I find when I use system default audio renderer, it works fine with EVR-CP/MPC Video Renderer.

**Comment by Aleksoid1978** [comment] 2020-06-19 01:44
So - some bugs in Internal Audio Renderer.
I think it's bad handle transitions between Titles on some DVDs.

**Comment by clsid2** [comment] 2020-06-20 13:28
@adipose
Could you have a look at this issue?
Possible bug in internal audio renderer.

**Comment by adipose** [comment] 2020-06-20 15:36
I reproduced it.  Open DVD directly with default renderer set to internal audio renderer.  Initial track plays before navigating to title menu automatically.  At that point it's a black screen but you can click.

Sanear is reporting repeated clock warps.

If you navigate directly to title menu there is no issue.

**Comment by adipose** [comment] 2020-06-20 19:35
I'm not sure this is the best way to solve the issue, but I have resolved it.  The problem is related to the slaveclocktoaudio.  If this is disabled, there is no problem.  Normally, it is unslaved when seeking to the title menu, but this signal is never received when auto-seeked.  I found this old bug report here:

https://forum.inmatrix.com/index.php?showtopic=14016

This is related to flush, and talks about how the last frame is shown rather than the menu frame.  I suspect it was solved by adding the DVD_CMD_FLAG_Flush flag.  But we can't set that (that I know of) when it auto-seeks.

What I did is add a special flag that records when the flag was set by mpc-hc.  If it seeks to the title menu without that flag, it simply forces it to go through the mpc-hc codepath which sets the flush flag.

Here is a test build:

https://mega.nz/file/AdQnBACL#yRucFYO6Bk9lvt2x1pzN6Fkj2oKfIfq3IZtDss_8x3U

**Comment by lifegpc** [comment] 2020-06-21 00:23
@adipose It works. Thanks.

**Comment by lifegpc** [comment] 2020-06-21 02:16
Hmm, I find it works with huge delay. But sometimes may let mpc-hc no response.
![image](https://user-images.githubusercontent.com/41434272/85215229-25e71400-b3a8-11ea-9763-d69f0bc311df.png)

**Comment by adipose** [comment] 2020-06-21 02:21
Darn, I will search for a cleaner solution.

**Comment by adipose** [comment] 2020-06-25 17:07
This build seems better, give it a shot.

https://mega.nz/file/ccgFkZLK#H35oCw5Slesl_KQdgqS9SHd5_sx5gUslR4x49PvHmQ8

@Aleksoid1978, there seems to still be a small issue with mpc-vr in d3d11 mode. In d3d9, this build is working well, but in d3d11 there is still a black screen with green bars highlighting the buttons on the DVD menu.

**Comment by lifegpc** [comment] 2020-06-25 22:07
It works well, thanks.

**Comment by Aleksoid1978** [comment] 2020-06-26 00:11
I check in MPC-BE - perfect output in DX9/DX11 mode with internal DVD decoder. Checked with LAV + DX11 Native - picture is normal, but menu element is not highlighting. I think it's not a MPC VR issue - video decoder highlighting menu element/button.

**Comment by adipose** [comment] 2020-06-26 18:47
It's interesting, because the exact opposite happens in mpc-hc.  No background but the button highlights show up.  I'll enter an mpc-hc bug, but I'm not clear on the source of the issue (maybe LAV).

**Closed as completed** 2020-06-26 19:02 UTC
Labels: bug

**Comment by ghost** [comment] 2025-01-09 05:51
MPC-BE doesn't read "jumppad" commands from DVD.  A jumppad is a DVD command saying to go to the next title at the end of a video.  VLC player knows how to read it and so does my DVD player.  It's unfortunate because I make a lot of my DVDs with jump pads.
