### ISSUE TITLE
Add option for UseSeekPreview window be under mouse/seek bar

### ISSUE THREAD

**Issue by tealkami** [clsid2/mpc-hc#2076] opened 2023-03-17 11:32 UTC
Hi, can you **please** add option in Options for SeekPreview to be shown below the mouse/seek bar ? like make the option "above/below seek bar" be applied to both "time tooltip" + "SeekPreview"

Reason/example:
99,999999% of time I watch in windowed mode anyway with Statistics on (ctrl+4), but when I skip/look/search through video SeekPreview window block actual video, and to be "usable" I set it up to 5%(so it doesn't block most of the actual video), but I would like to have it in 20-30% size window 

What feature I mean:
Options => Tweaks => Show preview on seek bar
or in mpc-hc.ini file it is as useSeekPreview

**Comment by adipose** [comment] 2023-05-14 19:07
Should probably only apply in windowed mode?

**Comment by tealkami** [comment] 2023-05-14 22:36
What makes to add/code-in the option to choose easier
Is it easier to make it only in windowed mode? Yes please, good enough.
Is it easier to make for both windowed/fullscreen? Yes, people can choose how they like it.

With *Statistics* on (ctrl+4) you could make it with 10% preview size in fullscreen mode too :D
**Realistic:** People who watch fullscreen most of the time would have it on top, and windowed people would use more the bottom version.
I would make it so you could use it in windowed/fullscreen, and who wants it will choose.

**Comment by clsid2** [comment] 2023-05-14 22:50
In fullscreen there is only space above, so option would not apply.
If placed below in windowed, it would need to be below mouse pointer, partial overlap lookw weird.

**Comment by tealkami** [comment] 2023-05-16 04:17
Mouse pointer is very small, which is less distracting for a PreviewWindow, than 20-30% useSeekPreview in actual video/subtitles.
So yea... under seek bar + under mouse pointer layer.

**Comment by bibsp** [comment] 2023-05-16 09:47
**adipose**, does your PR give users option to choose which one they want?
I have no issue if developer adds this feature, but please don't change the default preview position. An advanced option is needed.
Other players and all online streaming services show preview above seek bar.
Below seek bar will look bad, most people will not like it.
Hope you understand. Thank you.

**Comment by clsid2** [comment] 2023-05-16 11:21
adipose, do you have a screenshot since you said it looks a bit weird?

Another possibility would be to make the % relative to video width instead of screen width. So small video will have smaller preview.

**Comment by tealkami** [comment] 2023-05-16 12:16
Edited an example : https://i.imgur.com/GRdg4x6.png (both) , https://i.imgur.com/Bj4BL1F.png (only below)
In my opinion, SeekPreview window is great, but 10% is too small, and above 20% just block the actual video too much

Only new addition is, if you put timestamp on top frame, you would need to move timestamp to the left/right(not center), otherwise mouse would block the timestamps.

![Test](https://i.imgur.com/GRdg4x6.png)


You can definitely have 10% on fullscreen too, with **Statistics**+**Status** turn on  (default keybinds CTRL+4 CTRL+5), well... just proving something pointless :D

![only below](https://i.imgur.com/Bj4BL1F.png)

**Comment by clsid2** [comment] 2023-05-16 17:05
It needs extra code to make sure there is enough space below seekbar.

**Comment by adipose** [comment] 2023-05-16 17:15
![image](https://github.com/clsid2/mpc-hc/assets/3324395/6086d907-fdc4-4fcf-98fa-aea943925eab)



> **adipose**, does your PR give users option to choose which one they want?

It follows the tooltip above/below setting.

**Comment by adipose** [comment] 2023-05-16 19:45
> It needs extra code to make sure there is enough space below seekbar.

Added that.

**Comment by clsid2** [comment] 2023-05-18 14:59
Merged

**Closed as completed by clsid2** 2023-05-18 14:59 UTC

**Comment by tealkami** [comment] 2023-05-18 15:34
thank you

**Comment by tealkami** [comment] 2023-05-19 02:57
@clsid2 Can you please push update for the **Development Builds / Pre-release**, so I can test/see it ?

**Comment by tealkami** [comment] 2023-05-19 14:22
Thank you (for pushing Development Build)

@adipose odd choice preview window doesn't render above taskbar, it switch to *above seek bar*, same apply in fullscreen mode, too (test it 2rows - my default, 1 row , auto hide taskbar), the fullscreen mode is funny, because you don't see the taskbar, but it still *take it into account*.
is it some Windows restriction? well anyway, I am very happy that I can have at least something
Thank you very much **adipose**

**Comment by clsid2** [comment] 2023-05-19 15:40
There is no taskbar in fullscreen (F11). You probably mean maximized window. It shows below correctly for me when there is enough space.

**Comment by adipose** [comment] 2023-05-19 17:14
> Thank you (for pushing Development Build)
> 
> @adipose odd choice preview window doesn't render above taskbar, it switch to _above seek bar_, same apply in fullscreen mode, too (test it 2rows - my default, 1 row , auto hide taskbar), the fullscreen mode is funny, because you don't see the taskbar, but it still _take it into account_. is it some Windows restriction? well anyway, I am very happy that I can have at least something Thank you very much **adipose**

Well, the way it works is to key off the seekbar, not taskbar:

1. If the "below seekbar" option is enabled and the size of the preview would fit on the screen, try to put the preview below (roughly, below the mouse pointer).
2. If the "above seekbar" option is enabled, put the preview above (a few pixels above the seekbar)
3. If the "below seekbar" option is enabled and the size of the preview would not fit on the screen, put the preview in the same location as `#2`

**Comment by tealkami** [comment] 2023-05-20 13:08
Below is my Win10 version
My TaskBar setting : https://i.imgur.com/U9OcdSs.png 
```
Edition	Windows 10 Pro
Version	21H2
Installed on	‎17. ‎12. ‎2021
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

@adipose I did test now "Lock the taskbar" on/off, still it thinks the taskbar is the end of screen/resolution/display
Edited example :
![TaskBar Windowed](https://i.imgur.com/McXL6lC.png)

-----

> There is no taskbar in fullscreen (F11). You probably mean maximized window. It shows below correctly for me when there is enough space.

Yea... No, I know what I did write, picture say more in this case :
![TaskBar Fullscreen](https://i.imgur.com/Ef6MNs4.png)

**Comment by clsid2** [comment] 2023-05-20 13:40
This is apparently how Microsoft has intended it to work.

We will not make any further changes.
