### ISSUE TITLE
Remember File Position Not Working

### ISSUE THREAD

**Issue by noto10** [clsid2/mpc-hc#1595] opened 2022-03-13 18:16 UTC
I have just updated from 1.9.19.32 to 1.9.19.55

The setting **View > Options > Player > Remember File Position** is not working in both versions. It does not work whether a video is stopped and restarted within a session or after the player is closed and then re-opened. In either case, the video will start from the beginning.

**Comment by clsid2** [comment] 2022-03-13 18:42
Working fine for me.

Are you storing settings in INI file? Either stop doing that or make sure the player has write access to the file.

**Comment by noto10** [comment] 2022-03-13 20:35
> Working fine for me.
> 
> Are you storing settings in INI file? Either stop doing that or make sure the player has write access to the file.

No. The settings are stored in the registry. No INI file used. 

![mpchc](https://user-images.githubusercontent.com/13828004/158078104-b2895135-c75d-4f68-a57c-5c2657557964.jpg)

**Comment by clsid2** [comment] 2022-03-13 23:26
Is the recent file list itself working?

**Comment by noto10** [comment] 2022-03-14 06:28
> Is the recent file list itself working?

Yes. The recent file list is populated and working.

**Comment by clsid2** [comment] 2022-03-14 13:33
I can't reproduce the problem, meaning I can't fix it.

If it occurs only for short videos, then you may need to adjust this setting:
Options > Advanced > RememberPosForLongerThan

**Comment by noto10** [comment] 2022-03-14 14:40
> I can't reproduce the problem, meaning I can't fix it.
> 
> If it occurs only for short videos, then you may need to adjust this setting: Options > Advanced > RememberPosForLongerThan

I understand. I was hoping you might have some suggestions as to possible causes. The videos are from around 45 mins to over 5 hours so I think **RememberPosForLongerThan** is unlikely to be the culprit. In any case, it was already at 0. 

The only other possibility is some kind of registry corruption which has been mentioned elsewhere in my search. Perhaps a backup and export before deletion and reinstallation may be the next option. Will report back on how it goes.

BTW, I just thought of something - Is there a practical limit to the number of entries in Recent File List? Would having too many entries adversely affect Remember File Position's functionality?

![mpchc2](https://user-images.githubusercontent.com/13828004/158193581-35c8d2e0-35be-4f01-b907-f810addfd3c9.jpg)
e

**Comment by noto10** [comment] 2022-03-14 16:36
Ok. I have just run a few tests. First, I deleted all registry entries of MPC-HC and did a clean uninstall and reinstall. Next, I checked Remember File Position in the newly installed MPC-HC and played a few videos. The last played positions were not saved.

After that, I created an INI file with the correct permissions and confirmed that the settings were being saved in the INI file. Then I played the same videos as I did the first time. This time the last played positions were saved.

I then unchecked the Save settings to .ini file setting which caused the file to be deleted. Subsequently, the last played positions went back to be unsaved.

Out of ideas at this point.

**Comment by clsid2** [comment] 2022-03-14 17:06
The history is stored in this key:
HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\MediaHistory

Has FilePosition value 0 for all subkeys? Or are the values perhaps huge? Correct value is measured in milliseconds.

**Comment by xLn2** [comment] 2022-03-14 20:27
Maybe unrelated but I had a weird experience about recent file list. My guess was that it was more likely sourced from yt-dl, I guessed it stopped responding and I terminated the process, or it couldn't process the address at first, then when I tried again, it lead to corrupted file history. I cleared recent file list and did not notice any further issue recently. If it is important stuff I can try to recreate this situation when I have time and will open new issue.
![resim](https://user-images.githubusercontent.com/3073922/158214663-9f024744-5c44-4cb7-8eb8-98dc6a96c7d4.png)

**Comment by noto10** [comment] 2022-03-15 08:48
I do not seem to have this subkey.

![mpchc3](https://user-images.githubusercontent.com/13828004/158339227-67e843a8-aef2-4876-a87f-b006818866ff.jpg)

**Comment by noto10** [comment] 2022-03-15 08:49
> The history is stored in this key: HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\MediaHistory
> 
> Has FilePosition value 0 for all subkeys? Or are the values perhaps huge? Correct value is measured in milliseconds.

I do not seem to have this subkey.

![mpchc3](https://user-images.githubusercontent.com/13828004/158340360-30a11acd-c5dc-47cf-905f-97c7a43b4190.jpg)

**Comment by clsid2** [comment] 2022-03-15 12:30
Try 1.9.19.63

**Comment by noto10** [comment] 2022-03-15 16:12
> Try 1.9.19.63

I am on 1.9.19.63

I have Media History subkey now. All FilePosition values are 0. For every file.

**Comment by clsid2** [comment] 2022-03-15 18:26
Are the subkey names seemingly random characters (= good, working hash) or the end of the filename (= bad, fallback method)?

If you change a FilePosition to 120000 (= 2 minutes) while player is closed, does the file resume correctly? Then I at least know that part is working for you.

I have still no idea what is wrong.

**Comment by noto10** [comment] 2022-03-15 19:00
> Are the subkey names seemingly random characters (= good, working hash) or the end of the filename (= bad, fallback method)?
> 
> If you change a FilePosition to 120000 (= 2 minutes) while player is closed, does the file resume correctly? Then I at least know that part is working for you.
> 
> I have still no idea what is wrong.

I have attached 2 screenshots showing the state of my registry entries with 0 for FilePosition for all files.

I tried your suggestion of manually setting a FilePosition to 120000 while the player is closed. This made the file resume correctly at the set position. However, after I closed the player and resumed at next opening, the FilePosition went back to 0 and the file started from the beginning again.

Could this be related to protected registry keys in any way?

![mpchc5](https://user-images.githubusercontent.com/13828004/158451077-94f99fe8-1d7e-474b-9652-fea8807cad80.jpg)
![mpchc4](https://user-images.githubusercontent.com/13828004/158451127-655e8768-b18b-429f-be21-4b77689c7412.jpg)
.

**Comment by clsid2** [comment] 2022-03-15 22:50
Writing to the registry is working fine. It is just somehow writing wrong value.

It updates the value every 30 seconds during playback, and also when closing the file. Can you set it to 120000 again, and then refresh (F5) the registry a few times during playback to see if the value gets updated correctly.

Position does get reset to 0 when file reaches 95% (or more) of the duration when closing the file. It assumes playback is "done" in that case and that the end credits are being played.

**Comment by adipose** [comment] 2022-03-16 02:09
I wonder if the recent patch to not load the media history when opening the recent menu has any impact?  Probably not, but just wondering.

**Comment by noto10** [comment] 2022-03-16 08:53
> Writing to the registry is working fine. It is just somehow writing wrong value.
> 
> It updates the value every 30 seconds during playback, and also when closing the file. Can you set it to 120000 again, and then refresh (F5) the registry a few times during playback to see if the value gets updated correctly.
> 
> Position does get reset to 0 when file reaches 95% (or more) of the duration when closing the file. It assumes playback is "done" in that case and that the end credits are being played.

I think I have isolated the place where the anomaly occurs.

Refreshing the registry (F5) while playing updates the FilePosition correctly as you can see in the screenshot. After stopping the player but _without_ closing it, I refreshed the registry one more time. At this point, the value of FilePosition was 1390138. I then closed the player and refreshed the registry again. The FilePosition value immediately reset to 0. So for some reason FilePosition resets the instant the player is closed.

![mpchc6](https://user-images.githubusercontent.com/13828004/158552468-5f29124b-8356-4829-910d-37a019ce7316.jpg)

**Comment by ale5000-git** [comment] 2022-03-16 08:56
@clsid2
Reset to 0 when file reaches 95% make sense for film/series but not for music videos (that may not have end credits).
Is it possible to remove the 95% if the media duration is less then 10 minutes?

**Comment by clsid2** [comment] 2022-03-16 12:38
Stopping before close is probably where bug is. I will check that out later today.

If a music video is 5 minutes, then last 5% is 15 seconds. Why wanting to resume 15 seconds before end? Certainly with music you want to restart, at least most will. So I see no reason to change that.

**Comment by clsid2** [comment] 2022-03-16 13:12
Pressing stop will reset position to begin. After thinking about it, it doesn't make much sense to remember the position before pressing stop. If you want to remember position, simply close the player directly or open a new file. Pressing stop can then be used to deliberately reset remembered position.

**Comment by adipose** [comment] 2022-03-16 15:45
Yes, I observed this behavior myself but I thought it was always this way.

I had to convince myself but eventually I decided the same as you. If you hit stop, you don't want to resume. If you close the player you may want to reopen it.

**Comment by noto10** [comment] 2022-03-16 18:32
> Pressing stop will reset position to begin. After thinking about it, it doesn't make much sense to remember the position before pressing stop. If you want to remember position, simply close the player directly or open a new file. Pressing stop can then be used to deliberately reset remembered position.

@clsid2 

In my memory, FilePosition getting reset after stopping was a recent change. MPC-HC had always been able to resume after stopping until sometime recently. So I went back and checked 1.19.15 through 1.19.19 and it was indeed the case. The regression happened somewhere along the development builds of 1.19.19.x 

Allow me to explain why I think remembering the position when stopping is logical and desirable:

I review many videos using a single window. There are many occasions when I do not finish a clip but need to stop at a particular place to continue at a later time. I may also pause a clip many times during playback and stop after a pause if I need to play another clip. In this way, there is a need to stop multiple clips without exiting the player. I only exit the player when I have finished using the program.

As you can see, if FilePosition does not remember after stopping, it would completely break how I use it as it would mean I have to exit the player each time I want to switch to a new clip.

I hope that makes sense.

**Comment by clsid2** [comment] 2022-03-16 19:09
You should pause instead of stop for your use case. Or do nothing at all and just open another file directly. There is no need to "stop" current file before opening another one.

I practically never use the stop button at all.

**Closed as completed** 2022-03-16 23:21 UTC

**Comment by noto10** [comment] 2022-03-17 18:17
> You should pause instead of stop for your use case. Or do nothing at all and just open another file directly. There is no need to "stop" current file before opening another one.
> 
> I practically never use the stop button at all.

I have tried it and it's really not intuitive to me. I guess my logical understanding comes from the perspective that Pause and Stop should have the same effect on FilePosition because regardless of which one, FilePosition should record the place where playback last ended, and both Pause and Stop effectively "ends" playback. 

Another analogy would be driving a car. Whether I pull into a parking lot but leave the engine running (Pause) or switches off the engine (Stop) does not change the car's absolute last known position. I may have intended to take a 5 minute break (Pause) with engine running to make a call but ended up parking the car (Stop) when my friend tells me he's picking me up. Either way, I would want to remember the location of my car so I can return to it later.

I appreciate you taking time to investigate this issue. I have been very happy with how MPC-HC works other than this regression. May I ask if this change will be reverted or if it is the new behavior of Remember File Position going forward? Of course, I would like to request for the change be reverted if possible.

**Comment by clsid2** [comment] 2022-03-18 14:49
I am not reverting it. Nor am I going to add am option for it.

**Comment by noto10** [comment] 2022-03-18 15:57
Thank you for the clarification.

**Comment by adipose** [comment] 2022-03-22 22:51
> > You should pause instead of stop for your use case. Or do nothing at all and just open another file directly. There is no need to "stop" current file before opening another one.
> > I practically never use the stop button at all.
> 
> I have tried it and it's really not intuitive to me. I guess my logical understanding comes from the perspective that Pause and Stop should have the same effect on FilePosition because regardless of which one, FilePosition should record the place where playback last ended, and both Pause and Stop effectively "ends" playback.
> 
> Another analogy would be driving a car. Whether I pull into a parking lot but leave the engine running (Pause) or switches off the engine (Stop) does not change the car's absolute last known position. I may have intended to take a 5 minute break (Pause) with engine running to make a call but ended up parking the car (Stop) when my friend tells me he's picking me up. Either way, I would want to remember the location of my car so I can return to it later.
> 
> I appreciate you taking time to investigate this issue. I have been very happy with how MPC-HC works other than this regression. May I ask if this change will be reverted or if it is the new behavior of Remember File Position going forward? Of course, I would like to request for the change be reverted if possible.

In general the only reason I think this is worth thinking about, is that the old behavior was different.  As a result, I'm wondering if there is any merit to allowing it.  Some points

1. If the playback is stopped, that doesn't mean you don't want to resume.
2. If the playback is paused, that does mean you likely want to resume.
3. In the past, stopping did not prevent you from resuming
4. If we do not reset the start position when you stop, then what is the straightforward way of clearing the current position?

Given that #2 gives you the option (as does starting a new video or simply closing the player), #1 may not be necessary.

To consider your car analogy, keep in mind that cars also don't have an option to forget their location and start from the beginning, next time.  But for video, it can be useful.  Consider this: you are watching a video you've seen before.  You grow bored and decide to stop watching.  You hit STOP.  A few weeks later you decide to watch the video.  Do you want to start where you left off?  Same scenario, you hit PAUSE.  You have clearly indicated you want the video to stay at that position.

So I guess the question is, what is the need?  The best I could think of was content someone wanted to hide.  They quickly hit stop to prevent anyone seeing it.  But they would like to resume later.  Well, in that event you could just kill the player instead, right?

If you have a good argument for the feature and clsid2 approves, I could add an advanced option to have the old behavior, but the more I think about it, the more it seems like we've actually added functionality.
