### ISSUE TITLE
Playback speed adjustment much improved

### ISSUE THREAD

**Issue by harmandmen** [clsid2/mpc-hc#1606] opened 2022-03-19 07:48 UTC
I just want to report that the latest release, 1.9.20, seems to have greatly reduced, in my PC, the occurrence of those lags I've been experimenting for a long time when changing the playback speed.

As soon as I started watching mp4 files with the new release I noticed that now the playback speed changes almost instantly (as expected) most of the time, while the lags occur only once in a while (more or less the opposite of what used to happen before).
Which, obviously, looks like a great welcome improvement to me.

I thought I'd report it, in case it might be of any interest to the developers.

**Comment by clsid2** [comment] 2022-03-19 12:03
Which version were you using before?

This is not something I have specifically fixed.

I am curious which change has resulted in this positive side effect. I assume your settings are still the same as before. Could you test if the old version still gives the problem? Just to confirm it was not fixed by an external factor, such as updating a driver. If old version still suffers from problem, then could you test the development builds in between the old and new version? Knowing which change is responsible could maybe help to further improve the situation.

**Comment by harmandmen** [comment] 2022-03-22 19:31
Thanks for your answer and advice, which pushed me to a more accurate analysis.

Actually, after directly comparing the new version and the previous one (1.9.19) with the same mp4 file, I must admit that the improvement, despite being present, is less marked than it seemed to me at first.
The lags are less frequent, but they still occur, still in an apparently random way. Sometimes the speed changes immediately, while other times I get the... usual sequence: the image disappears (black window), then after a few seconds the title bar shows "(Not Responding") and then, after another (variable) time lapse, the playback restarts.
As you may remember, this has been happening to me for a long time; sadly, despite trying to do so, I haven't been able, yet, to spot any certain reproducible cause/effect relationship. Obviously it's not a big issue, but I'd like to understand where it comes from.

I also noticed (maybe it can be useful information, I don't know) that a quite similar behaviour occurs when closing a video with the CTRL + C command: the video always stops immediately but sometimes the program remains _"not responding"_ for some (variable) time. The same happens also when, while playing a video with multiple audio tracks, I switch from an audio track to another (with the menu command or with the "A" keyboard shortcut).

**Comment by clsid2** [comment] 2022-03-22 22:38
Maybe [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) can reveal what is happening when it hangs.

Given that 99.9% of users don't have this issue, it is extremely likely it is caused by a factor outside of the player, and there is nothing I can do to fix it.

**Closed as completed by clsid2** 2022-03-22 22:38 UTC
