### ISSUE TITLE
使用暗色主题，菜单响应慢 Slow menu response with dark theme

### ISSUE THREAD

**Issue by DOSforever** [clsid2/mpc-hc#1598] opened 2022-03-16 13:29 UTC
如果使用暗色主题，无论是点击菜单栏或右键弹出菜单，菜单出现的响应很慢，有明显的延迟，但在非暗色主题下无此问题。我是从 1.9.8.92 版开始发现这个问题的，到现在的 1.9.19 版仍然存在。

If you use a dark theme, whether you click the menu bar or right-click the pop-up menu, the response of the menu appears very slow, there is a noticeable delay, but there is no such problem in the non-dark theme. I discovered this problem since version 1.9.8.92 and it still exists in version 1.9.19.

**Comment by clsid2** [comment] 2022-03-16 13:38
It is fast for me. Does it happen with a specific menu entry only?

**Comment by DOSforever** [comment] 2022-03-16 13:50
不，所有的下拉菜单和右键弹出菜单都是如此。

No, this is true for all drop-down menus and right-click pop-up menus.

**Comment by Alp1821** [comment] 2022-03-16 13:57
It is also fast for me both in light and dark theme. I have very low end pc and HDD. No SSD.

**Comment by clsid2** [comment] 2022-03-16 14:12
It is also fast for me with Chinese language.

If only file menu is slow, try this:
options > player > disable "open disc" menu

**Comment by clsid2** [comment] 2022-03-16 14:16
Is 1.9.8.75 fast?

**Comment by DOSforever** [comment] 2022-03-16 15:00
我没有用过 1.9.8.75 ，因为我是用 1.9.8.92 版才开始知道有暗色主题的，后来我再试了下之前最早使用的 1.9.8.0 版，使用英文界面，切换成暗色主题，仍然是这现象。我用的都是 portable 版。

I haven't used 1.9.8.75, because I only started to know that there is a dark theme with version 1.9.8.92, and then I tried the first version 1.9.8.0 I used before, using the English interface, switching to the dark theme, still this phenomenon. I am using the portable version.

**Comment by lifegpc** [comment] 2022-03-16 15:03
I don't have this issue for both English and Chinese.

**Comment by DOSforever** [comment] 2022-03-16 15:15
已关闭预览。即便是在不打开任何媒体文件的情况下也是如此。

Seek preview is disabled. Even without opening any media files.

**Comment by clsid2** [comment] 2022-03-16 15:19
You can get all old versions here:
https://github.com/clsid2/mpc-hc/releases

Dark theme fast first added in [1.9.0](https://github.com/clsid2/mpc-hc/releases/tag/1.9.0)

That was more than 2 years ago. Nobody has reported slowness problem before. We can't fix problem that we can not replicate.

**Comment by adipose** [comment] 2022-03-19 04:03
Maybe a submenu populating a lot of subtitles, recent files, or something, not sure.

Theme does rebuild the menus. There is some inefficiency in reloading menus at times. But it hasn't caused any major problems.

Can you send your settings and computer specs. Also a video comparing performance of classic vs themed.

**Comment by clsid2** [comment] 2022-03-19 11:55
He said it was slow for all menu items, so it can't be due to a long list.

@DOSforever
Do you have any software installed that modifies the Windows Start menu or how Windows looks?

**Comment by adipose** [comment] 2022-03-19 16:09
From his description it's unclear but I interpreted it as being slow to display when clicking on the menu bar or right clicking. I thought maybe building up the entries is going too slow.

**Comment by clsid2** [comment] 2022-03-26 13:29
Closing this. We are unable to reproduce.

If anyone can give steps and conditions to reproduce the problem, then please comment.

**Closed by clsid2** 2022-03-26 13:29 UTC
