### ISSUE TITLE
on win7 x86 .srt file breaks 1.9.12

### ISSUE THREAD

**Issue by ronkwann** [clsid2/mpc-hc#1125] opened 2021-05-31 11:18 UTC
as title, x86 1.9.12 freezes after i "Load Subtitles" .srt file

roll back to 1.9.11 fixes the problem

**Comment by clsid2** [comment] 2021-05-31 12:38
Please test the development builds that were in between 1.9.11 and 1.9.12

**Comment by clsid2** [comment] 2021-05-31 19:40
It is working fine for me.

**Comment by ronkwann** [comment] 2021-06-01 08:14
> 
> 
> Please test the development builds that were in between 1.9.11 and 1.9.12

the development builds as shown here https://github.com/clsid2/mpc-hc/releases
are all x64, i am not able to use them.

i just gave x86 1.9.12 another go, still the same.  i took the following steps;
1) install x86 1.9.12 , reset all settings
2) "Open" .mp4 file
3) "Load Subtitles" .srt file
4) video still running, but no subtitles show up
5) double click (full screen) on the video, mpc-hc window freezes, sound continues to run for a bit
6) mpc-hc window as "Not Responding", force close

i try with a couple different set of files (mp4/srt), all crashes the first time, but when you open the same .mp4 again after crash, some videos show up with the subs without manual "Loading Subtitles".  but some will crash every single time when you try to load the subs.

**Comment by clsid2** [comment] 2021-06-01 10:40
Loaded subtitles files are remembered in the recent file list. So that is why it shows up on next load.

After loading the subtitle, does the subtitle show up as selected here?
Menu > Play > Subtitles

Does it also freeze if you don't go to fullscreen?

I will try to reproduce again later in a virtual machine.

**Comment by ronkwann** [comment] 2021-06-01 11:07
> 
> 

> After loading the subtitle, does the subtitle show up as selected here?
> Menu > Play > Subtitles

Yes.  

> 
> Does it also freeze if you don't go to fullscreen?

it does.

to be more precise, i load the .srt and video will freeze immediately, sound will go on for about another 30 seconds then stop, but the time counter on bottom right goes on.  all until i try to go to full screen or resize the window or click one of the control buttons , then mpc-hc will go to "not responding"



> I will try to reproduce again later in a virtual machine.

much thanks.

**Comment by clsid2** [comment] 2021-06-01 12:11
Open the Windows Task Manager (Ctrl+Shift+Esc)
When MPC-HC freezes, right-click on mpc-hc.exe in the task manager and "create dump" file in the menu.
Zip/rar/7z the dump file to make it smaller.
Upload it somewhere for me. For example http://www.sendspace.com

Then I can analyze where it hangs in the code.

**Comment by ronkwann** [comment] 2021-06-01 13:34
> 
> 
> Open the Windows Task Manager (Ctrl+Shift+Esc)
> When MPC-HC freezes, right-click on mpc-hc.exe in the task manager and "create dump" file in the menu.
> Zip/rar/7z the dump file to make it smaller.
> Upload it somewhere for me. For example http://www.sendspace.com
> 
> Then I can analyze where it hangs in the code.

done, 7zip-ed the file;
https://gofile.io/d/S7PlPd

**Comment by clsid2** [comment] 2021-06-01 19:23
Here are some x86 dev builds to test:
https://www.sendspace.com/file/760g4c

**Comment by ronkwann** [comment] 2021-06-02 00:32
> 
> 
> Here are some x86 dev builds to test:
> https://www.sendspace.com/file/760g4c

these 3 work, no freeze no crash
mpc-hc_1.9.11.14
mpc-hc_1.9.11.33
mpc-hc_1.9.11.49

this one video freezes as soon as i load a .srt
mpc-hc_1.9.11.59

**Comment by clsid2** [comment] 2021-06-02 00:44
Good. Try this build:
https://www.sendspace.com/file/qcizbp

**Comment by ronkwann** [comment] 2021-06-02 00:59
> 
> 
> Good. Try this build:
> https://www.sendspace.com/file/qcizbp

just tried, video freezes as soon as i load a .srt

**Comment by clsid2** [comment] 2021-06-02 01:08
Does it work when you drag&drop the .srt onto the video window?
Which video renderer are you using?
What is your screen resolution?

**Comment by ronkwann** [comment] 2021-06-02 01:24
> 
> 
> Does it work when you drag&drop the .srt onto the video window?

it does not. same freeze and crash.

> Which video renderer are you using?

this one?
Direct Show Video -> Enhanced Video Renderer(custom presenter)
Audio Renderer -> 1. System default
Subtitle Renderer -> Internal Subtitle Renderer

> What is your screen resolution?

1024 x 768
i am using a dell d520 laptop

**Comment by clsid2** [comment] 2021-06-02 01:33
I was unable to reproduce a hang in a Virtual Machine.

Could you export your settings? Maybe that will help to reproduce.
Options > Miscellaneous > Export

**Comment by ronkwann** [comment] 2021-06-02 01:40
here it is;
https://www.sendspace.com/file/wtyrkz

**Comment by clsid2** [comment] 2021-06-02 14:13
You don't have any weird settings, so that isn't the problem.

Here are some more versions to test:
https://www.sendspace.com/file/xx2jl5

I am still puzzled what might be the root cause of the problem. So thanks for your patience with testing. The versions above should hopefully confirm where the problem started.

**Comment by ronkwann** [comment] 2021-06-02 15:09
mpc-hc_1.9.12.50.exe  works, "Load Subtitles" no freeze no crash.

mpc-hc_1.9.12.51.exe  this one has sound but NO VIDEO at all, only black screen, becomes "Not Responding" as soon as load subtitles, but the sound keeps going on and on until i "End Process" using Task Manager.

mpc-hc_1.9.12.51_modified.exe  video freezes as soon as i "Load subtitles", becomes "Not Responding" when i press a control button or resize the window, sound stops around 30 seconds after

i am happy to be of any help.

**Comment by clsid2** [comment] 2021-06-02 23:24
Here is a debug build:
https://www.sendspace.com/file/a9j6n6
With the included Dbgview.exe tool you can generate a log file of what is happening internally.

**Comment by ronkwann** [comment] 2021-06-03 01:13
generated log files;
https://www.sendspace.com/filegroup/D%2BEzNgkhGuzUy4OG%2FaQJmg

both builds freeze and crash after a loading subtitle, i noticed clicking the "X" close control on mpc-hc after crash won't actually stop the app from running.  instead, right after i click "X", mpc-hc.exe will remain running in the background and occupied 9X% cpu for about 1 min, then fall to around 50% cpu continuously until i manually "End Process"

**Comment by clsid2** [comment] 2021-06-03 12:46
That was useful. The hang should be fixed now. But subtitles may not work yet because something goes wrong with the texture creation. Maybe your graphics driver doesn't like certain sizes.

Another debug build to get more details about the failure:
https://www.sendspace.com/file/bt1448

We are getting close to a solution now.

**Comment by clsid2** [comment] 2021-06-03 13:16
This one rounds texture size to a multiple of 16.
https://www.sendspace.com/file/hf3qc1

**Comment by ronkwann** [comment] 2021-06-03 13:30
> 
> 
> That was useful. The hang should be fixed now. But subtitles may not work yet because something goes wrong with the texture creation. Maybe your graphics driver doesn't like certain sizes.
> 
> Another debug build to get more details about the failure:
> https://www.sendspace.com/file/bt1448
> 
> We are getting close to a solution now.

log file available here;
https://www.sendspace.com/file/hd06e5

freeze and crash are gone when loading subtitles with this build

subtitles not showing up on the default video window after load, but it will show up once i resize(larger or smaller) or maximize(but not minimize) or full screen the window

**Comment by ronkwann** [comment] 2021-06-03 13:46
> 
> 
> This one rounds texture size to a multiple of 16.
> https://www.sendspace.com/file/hf3qc1

log file available here;
https://www.sendspace.com/file/87uh4q

i noticed subtitles will show up immediately if i open from " File -> Recently Files ".  but the same set of files if i use " File -> Open File " then " Load Subtitles", subtitles will only show up after i resize(larger or smaller) or maximize(but not minimize) or full screen the window

i understand both my machine and win7 x86 are their last legs, thank you very much for your patience and help.

**Comment by clsid2** [comment] 2021-06-03 15:55
Hopefully everything is working now:
https://www.sendspace.com/file/gxpauc

**Comment by ronkwann** [comment] 2021-06-04 02:42
log file available here;
https://www.sendspace.com/file/x8enq3

sorry to report when i try to open a .mp4 file, it prompts:

"Error creating EVR Custom renderer
CreateDevice failed
Error code: 0x8876017C
DX9AllocatorPresenter failed

D3DERR_OUTOFVIDEOMEMORY "

and then the next prompt:

"The selected video renderer has failed to load.
blah blah blah...
Do you want to use the basic video renderer by default?"

i click "yes" and the video can still be shown, but "File -> Subtitles" is grayed out

**Comment by clsid2** [comment] 2021-06-04 11:07
Your graphics chip uses shared memory, which means most of the memory it uses is your normal RAM. Open the Windows Task Manager (Ctrl+Shift+Esc) and check the amount of free memory. Closing some unneeded background applications might help to fix the outofmemory issue.

**Comment by ronkwann** [comment] 2021-06-04 13:19
i have a little over 1.5G of free ram as we speak, and it's still the same (Error creating EVR Custom renderer...) when i try to load a .mp4 file with your last debug build

**Comment by clsid2** [comment] 2021-06-04 16:24
I fixed another bug:
https://www.sendspace.com/file/q4ncp1

**Comment by ronkwann** [comment] 2021-06-05 06:20
"Error creating EVR Custom renderer" is gone now.

but i noticed video stuttering after subtitles loaded successfully, i can see a spike using "Display Statistics" before every line of sub is drawn.  there's no spike when not loading subtitles.

no sub loaded.
https://ibb.co/PjW3wd0

sub loaded.
https://ibb.co/tBxzj16

**Comment by clsid2** [comment] 2021-06-05 13:20
I assume these spikes did not occur with 1.9.11?
Do the spikes also occur when playing in fullscreen?

**Comment by clsid2** [comment] 2021-06-05 14:19
Also test these settings:
Options > playback > output > evr buffers = 4
Options > subtitles > sub pictures to buffer = 5 or 10

**Comment by clsid2** [comment] 2021-06-05 17:11
Debug builds do have lower performance than normal builds. So that is the most likely reason for the spikes. Good change it will be working good in next release build, which should be available soon.

**Comment by ronkwann** [comment] 2021-06-06 02:54
> 
> 
> I assume these spikes did not occur with 1.9.11?

Confirm this did not occur with 1.9.11 release

> Do the spikes also occur when playing in fullscreen?

Yes, also occur when playing in fullscreen

**Comment by ronkwann** [comment] 2021-06-06 02:58
> 
> 
> Also test these settings:
> Options > playback > output > evr buffers = 4
> Options > subtitles > sub pictures to buffer = 5 or 10

it works magic, problem solved.

thanks again for your time and patience

**Closed as completed** 2021-06-06 17:27 UTC
