### ISSUE TITLE
Bad sound with "Speex" audio codec.

### ISSUE THREAD

**Issue by somebody2979** [clsid2/mpc-hc#1836] opened 2022-09-08 04:36 UTC
It is not a very popular codec, but MPC-HC has problems with this audio codec from version 1.9.18 to the current one (1.9.23).
Version 1.9.17 and earlier sounded fine.

**Comment by Aleksoid1978** [comment] 2022-09-08 05:25
Upload sample file.

**Comment by clsid2** [comment] 2022-09-14 00:23
http://samples.ffmpeg.org/A-codecs/speex/speex_openacm.avi
http://samples.ffmpeg.org/A-codecs/speex/testingSpeex.flv

@nevcairiel
I narrowed this down to https://github.com/Nevcairiel/LAVFilters/commit/2fdaad482b5ffa16e27c9696942612fe86e5e432 or the ffmpeg update done on same day. MPC-BE internal decoder still works fine, so ffmpeg is probably not at fault. Also now that there is a native decoder for speex, maybe no more need for libspeex?

**Comment by Nevcairiel** [comment] 2022-10-11 12:24
I can't reproduce any issues with the latest FFmpeg update anymore.

**Comment by clsid2** [comment] 2022-10-11 13:35
Yes, fixed now. Thanks.

**Closed as completed by clsid2** 2022-10-11 13:35 UTC
