### ISSUE TITLE
Rectangular border around subs overlap when they're transparent

### ISSUE THREAD

**Issue by TB54** [clsid2/mpc-hc#2007] opened 2023-01-29 15:46 UTC
When you choose a rectangular border for the subtitles, and that the color of this border in partly transparent, the transparency of the two lines rectangle are added, resulting in a darker area where they overlap:

https://i.imgur.com/islzbt8.png

It would be better if they merged, with one single rectangular-border color.

**Comment by clsid2** [comment] 2023-01-29 16:31
Duplicate of #1803

**Closed as completed by clsid2** 2023-01-29 16:31 UTC
