### ISSUE TITLE
DVB Subtitles not available

### ISSUE THREAD

**Issue by JGallium** [clsid2/mpc-hc#2842] opened 2024-06-13 00:32 UTC
in MPC-HC v2.3.0 DVB subtitles are not available on any multiplex/frequency (the option to select them is greyed out). This is the case in both Windows 10 Build 22H2 and Windows 11 Build 23H2

Last version where I did not have problems is v2.1.5

edit: Note that this problem also happened with a release in 2023 which was eventually fixed after being reported on the k-lite codec forums  https://codecs.forumotion.net/t4330-dvb-subtitles-not-working-works-fine-in-vlc

**Comment by adipose** [comment] 2024-06-13 19:54
I will test this out.

**Comment by adipose** [comment] 2024-06-14 00:08
It's caused by the removal of these lines:

```
    if (CComQIPtr<IAMStreamSelect> pSS = m_pGB) {
        ASSERT(false);
        addStreamSelectFilter(pSS);
    }

```

In [this](https://github.com/clsid2/mpc-hc/commit/872a55d4073f31e2f9274523df0787556bbbd60c) commit.

I don't fully understand the commit, but I can say that this code isn't ever finding IAMStreamSelect for DVB:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/535ba886-81bd-4cfb-a529-d86272991f67)

Also, if the `pSS` line is the only thing working, we should probably remove the ASSERT.

**Comment by adipose** [comment] 2024-06-14 00:10
@clsid2 , maybe take a look.

**Comment by JGallium** [comment] 2024-06-14 00:12
Nice Find!

I don't have the tools installed to compile an exe myself, but I can test any new versions that get uploaded

**Comment by adipose** [comment] 2024-06-14 00:13
I can make you a test build.

**Comment by JGallium** [comment] 2024-06-14 00:13
ok, great, wanna do it now?

**Comment by adipose** [comment] 2024-06-14 00:14
I will upload in a bit.  I am on an old branch testing it at the moment.

**Comment by JGallium** [comment] 2024-06-14 00:15
ok, sure no hurry, I'm pretty free until next week

**Comment by adipose** [comment] 2024-06-14 00:38
https://mega.nz/file/5UoSRSab#zS6yA4cSr0gaFlNq4-8znnGG1Ip8gYJgH8kPkxfsdbI

**Comment by JGallium** [comment] 2024-06-14 01:06
That fixes it for me, Thanks!

EDIT:  Note that  if I just run the bare .exe file it doesn't work, but if I unzip the whole archive and double-click the .exe from there it does work.

(I'm using an Astrometa DVB-T2 USB dongle in Windows 10/11 to receive Freeview digital TV in the UK)


I hope this change can get rolled out in the official release and the K-Lite Codec packs soon.

Great stuff, should I close this myself?

**Comment by adipose** [comment] 2024-06-14 01:52
You can leave it open, but if my PR is accepted you can close it.

The exe and libraries are part of one build so they should be used together.

**Closed as completed** 2024-06-14 12:20 UTC
