### ISSUE TITLE
Video length is incorrectly reported for VFR videos

### ISSUE THREAD

**Issue by yesimanoob** [clsid2/mpc-hc#800] opened 2020-12-08 14:38 UTC
Am using a fresh, clean install of MPC-HC v1.9.8 and attempting to view a VFR HEVC MKV file. 

Though the file plays without issue, the total video length is reported as longer than the it actually is (thus the time bar is incorrect as well). For example, the video is supposed to be 46min but MPC-HC thinks it is an hour long. Playback of the video is fine until it reaches 46 minutes and then it hangs. Similarly, clicking on the time bar beyond 46m causes playback to hang. This hang is of course expected because the video is only 46 minutes long, but the program allows the user to attempt to access a time index beyond the end of the video.

I've tried the file on MPC-BE and it has the same issue. However, the file works as expected in PotPlayer, VLC, mpv, and even Windows Media Player. Mediainfo reports the correct length as well.

**Comment by clsid2** [comment] 2020-12-08 15:26
I can't do anything without a sample file.

**Comment by clsid2** [comment] 2020-12-08 15:42
You can probably fix the file by remuxing it with MkvToolNix.

**Comment by yesimanoob** [comment] 2020-12-08 16:04
The file was already originally created with mkvmerge v51.0.0.

Here is a sample: [video](https://mega.nz/file/ujYzhCSD#hvKeFAJTGhWtNNJhsXuUchMwx5uHd-EIiK_cv29LDrA)

**Comment by clsid2** [comment] 2020-12-08 16:13
It correctly says 46:59 duration here.

Try with latest development build, which has updated codecs compared to 1.9.8:
https://github.com/clsid2/mpc-hc/releases

**Comment by yesimanoob** [comment] 2020-12-08 16:22
I just tried with the development build, `MPC-HC.1.9.8.26.x64`, portable version. The issue still occurs. Being the portable version I assume that means all settings are default and I haven't done something to break the application?

![Runlength](https://user-images.githubusercontent.com/71625323/101509995-b51acf00-39bc-11eb-8c7d-0d4e403b81cc.PNG)

**Comment by yesimanoob** [comment] 2020-12-08 16:27
I just tried with the development build, `MPC-HC.1.9.8.65.x64`, portable version. The issue still occurs. Being the portable version I assume that means all settings are default and I haven't done something to break the application?

![Runlength](https://user-images.githubusercontent.com/71625323/101510798-b6003080-39bd-11eb-8a44-494ad72557e8.PNG)

**Comment by clsid2** [comment] 2020-12-08 16:45
Your video uses HEVC 4:4:4 RExt profile. Hardware acceleration is not possible for that profile. You need to use Main profile and 4:2:0.

**Comment by clsid2** [comment] 2020-12-08 16:47
It uses same settings as your installed copy. Make sure the internal Matroska source filter is enabled.

**Comment by clsid2** [comment] 2020-12-08 16:48
I am currently using an even newer version of the internal codecs here. So you may need to wait until next update if it doesn't work yet with the dev build.

**Comment by yesimanoob** [comment] 2020-12-08 23:37
Yes, the internal Matroska filter is enabled (by default it seems) and the issue still occurs.

Can you try the build with the older codecs posted to GitHub and see if that regression causes the bug to occur on your end?

**Comment by clsid2** [comment] 2020-12-09 00:34
It works for me with older build as well. I don't know what is wrong on your end.

1.9.8.75 is available now.

**Comment by yesimanoob** [comment] 2020-12-09 00:53
Tested 1.9.8.75 in a fresh Windows 10 VM, the length issue doesn't repro. It does repro with the new build on my main machine, however. As far as I can tell I am literally using a stock install with no external filters enabled.

Do you have any suggestions for options I can try changing to see what triggers this strange bug?

(Also, what is your recommended configuration setup for MPC-HC? As mentioned, I simply use a stock install with no external filters)

**Comment by clsid2** [comment] 2020-12-09 00:57
Very weird.

Try resetting settings on your main machine.
Options > Miscellaneous > Reset

**Comment by yesimanoob** [comment] 2020-12-09 01:53
I've reset the settings, but the issue still occurs on both the dev build and latest stable build. :(
Is it perhaps because I'm using HW (DXVA) video decoding?

Edit: I tried disabling HW decoding in the internal LAV video filter setting ("Hardware decoder to use" => "none"), restarting MPC-HC, but that didn't have any effect.

**Comment by clsid2** [comment] 2020-12-09 02:24
The duration is determined by the splitter. Video decoder does not have any effect on it.

Menu > Play > Filters > LAV Splitter Source (internal) > Properties
It should show version 0.74.1.92

**Comment by yesimanoob** [comment] 2020-12-09 06:35
It is indeed that version. I don't see any settings for the splitter that look like they'd have an effect on duration, and it doesn't look like a different splitter can be used, so I'm not sure if there's anything that I have changed to cause this issue to occur.

Is there any other debug data I can provide which would be useful in determining the cause?

**Comment by clsid2** [comment] 2020-12-09 12:42
There is no debugging ability in the splitter.

I don't know what could cause this. So unless someone else can reproduce this, I am going to give up.

**Comment by xLn2** [comment] 2020-12-09 19:22
> Here is a sample: [video](https://mega.nz/file/ujYzhCSD#hvKeFAJTGhWtNNJhsXuUchMwx5uHd-EIiK_cv29LDrA)

Example video seems deleted. Can you provide it again? I will also try if it would happen again.

**Comment by yesimanoob** [comment] 2020-12-10 15:31
@clsid2 I figured out what the issue is, and it has nothing to do with VFR. Rather it is an issue with muxing.

When originally muxed in mkvmerge the `--default-duration`  was not explicitly set. The documentation I found says that when not set it defaults to 25fps. I know nothing about video containers and formats, but I assume this is stored somewhere and MPC-HC calculates duration by using that `mkvmerge_defined_fps_num * total_frame_count`. However, when inspecting the file via mediainfo it is able to report the actual framerate, likely reading it from a different location, and is thus able to display the correct duration. The same is likely the case with the other players I tested with (PotPlayer, VLC, mpv, Windows Media Player).

I tested this by creating two muxes of the same video/audio streams, with and without that setting and confirmed that that is how to repro the issue.

I suppose you can argue that it is an error caused by misconfiguration elsewhere, but given that other players are handling it correctly there must be a solution to be had within MPC-HC?

edit: it may sound odd, but `--default-duration` is set with an fps number, so, for example this is what I used in the tests mentioned above with a CFR video: `--default-duration 0:29.97fps`

**Comment by clsid2** [comment] 2020-12-10 16:51
The duration is determined by the splitter. The player is not involved.

The sample file you uploaded for me has correct duration set in the file.
![ccs03e01_props](https://user-images.githubusercontent.com/4704996/101802505-cb856f80-3b0f-11eb-9c3b-8775282926d8.png)
Can you upload a file that is handled incorrectly?

--default-duration is the duration of a single frame (in nanoseconds). 41708333ns equals 23.976 fps.

**Comment by yesimanoob** [comment] 2020-12-11 13:59
Wow, so this is bizarre. I went back and played around with the settings some more in an attempt to prepare some sample files and discovered something that I can't understand, but can replicate.

I am using MKVToolNixGUI v51.0, and do the following:
1. Launch MKVToolNixGUI
2. Open Multiplexer tab
3. Drag-drop hevc video file into the window (in this case, CFR encoded with fmmpeg)
4. Drag-drop aac audio file into the window
5. Do not change any settings
6. Press "Start multiplexing button"
7. Open output file in MPC-HC

Doing this produces a file that has the incorrect duration displayed in MPC-HC. But here is the strange part. Do it again (without restarting MKVtoolNix GUI), simply change the output file name, press the multiplex button. That file which is produced the second time has it's duration correctly displayed in MPC-HC.

It is bizarre, but I've reproed it twice with two different sets of video/audio files. It is baffling to the point that I'm sure you won't believe me. :(

Is there a way to get MKVToolNix GUI to display the mkvmerge cli command it uses for each mux job?

**Comment by clsid2** [comment] 2020-12-13 14:09
Report this bug to MKVToolNix.

**Comment by yesimanoob** [comment] 2020-12-14 13:47
I still think there is a problem with MPC-HC given that videos which show the correct length in other players do not display it in MPC-HC. Perhaps you can blame the splitter, but there still seems to be a problem, mkvtoolnix aside.

**Comment by yesimanoob** [comment] 2020-12-14 13:48
Feel free to close-wontfix if you disagree :(

**Comment by clsid2** [comment] 2020-12-14 15:14
If you have another sample that has wrong length in MPC-HC, then I gladly take a look at it to see if splitter behavior can be improved. Your original sample was not broken.

**Comment by yesimanoob** [comment] 2020-12-15 16:17
Try this:
[incorrect](https://mega.nz/file/KrImFZ7B#ghb0iVgWDLFPaWQGyz9MPYebmXKjcDCHkpG1QAqKgvI)
[correct](https://mega.nz/file/vuZiDJoB#TRFgWKe8E0VzT0kqpsz1fuSpqI_DxLmrDjwuAbsl3R0)

**Comment by clsid2** [comment] 2020-12-15 20:51
Both files show same correct duration here.
1:31:44

**Comment by ale5000-git** [comment] 2020-12-16 18:17
@yesimanoob: It is possible that you have a broken codec installed in your system.

Try open the incorrect file in GraphStudioNext (both 32 and 64-bit) to see what codec get used.

**Comment by yesimanoob** [comment] 2020-12-17 11:58
@ale5000-git thank you for the suggestion.

I'm not sure what I'm supposed to be looking for, but both versions of the video show the same output in both 32 and 64 bit versions of GraphStudioNext. Notably none show video codecs, only audio. Also, the duration is correctly displayed for both versions of the file.

![image](https://user-images.githubusercontent.com/71625323/102485110-81b9fd80-40aa-11eb-8ba6-1502ae76a499.png)

**Comment by clsid2** [comment] 2020-12-17 14:15
Right-click on that first block > Properties > Filter.

Which filter is it?
If it is Haali Splitter, then you need to uninstall it. To properly render in GraphStudioNext, you need to install the appropriate filters. Here is what you would get with K-Lite installed:
![duration](https://user-images.githubusercontent.com/4704996/102498784-b1511180-407a-11eb-9559-727691fbdb31.png)

**Comment by BreakPoints** [comment] 2020-12-22 00:20
> There is no debugging ability in the splitter.
> 
> I don't know what could cause this. So unless someone else can reproduce this, I am going to give up.

I am able to reproduce on a few files that I have and I don't believe this was an issue many versions ago. I've got an HDR episode of Planet Earth II in which the MediaInfo page says the duration is "49 min 22 s" and MPC-HC seek bar/status bar says "57:36".

I'll see if I can find something smaller and less copyrighted to share that also has the issue

**Comment by clsid2** [comment] 2020-12-22 01:03
You can send (torrent) link to clsid2@users.sourceforge.net
I don't care about copyright, as I will delete the file after testing playback.

But first get latest [development build](https://github.com/clsid2/mpc-hc/releases/tag/1.9.8.26) (1.9.8.92) and verify that it uses the internal LAV Splitter (Menu > Play > Filters) during playback.

**Comment by BreakPoints** [comment] 2020-12-22 02:51
It's still happening on the Dev build but I've found out what the issue is in my case. There's a subtitle track that runs too long and that's used to set the length of the whole file. Clicking past the video/audio ending will just end playback.

Do you still want a link?

@yesimanoob could you check the file properties in MPC-HC and under MediaInfo look for subtitle tracks that match the incorrect length?

**Comment by clsid2** [comment] 2020-12-22 15:29
That could be it. The duration is determined by the longest track. I can ask LAV developer to ignore sub tracks in this case.

A sample would still be useful.

**Comment by BreakPoints** [comment] 2020-12-22 21:08
Link sent to your email. Let me know if you need anything else.

**Comment by clsid2** [comment] 2020-12-23 00:31
Which of the six episodes has the issue?
The external subtitle files suggest all of them are longer than 50 minutes.

**Comment by BreakPoints** [comment] 2020-12-23 09:47
I did state in my email that episode 1 has the issue but I think they all do. No episode should be longer than 50 minutes

**Comment by clsid2** [comment] 2020-12-23 16:04
I am still downloading the file. But with the partial file MediaInfo and VLC give same (wrong) duration as MPC-HC. All give 57:59 for the first episode.

**Comment by clsid2** [comment] 2020-12-23 17:00
MkvToolNix says the file has errors in the file structure.
If I remux the file and remove the Arabic sub then it has correct duration.

**Comment by BreakPoints** [comment] 2020-12-23 19:27
Hmm, if the incorrect length is also shown in VLC then this may be a separate issue to the one reported by @yesimanoob. Downloading the incorrect.mkv from the comment on the 15th I also get the correct length returned. This is on 1.9.8 Stable also.

In regards to my issue; if this is standard behaviour for media players then it could be argued that this isn't an issue at all and just an implementation detail. I would argue that showing a length that is never able to be reached is incorrect.

**Comment by clsid2** [comment] 2020-12-23 22:51
I have asked the splitter developer to take a look at your file.

You can fix it by remuxing it with MkvToolNix and removing the Arabic subtitle track.

**Comment by yesimanoob** [comment] 2021-01-04 10:10
Yes, that seems to be it. However, in my case there are some additional scenarios that trigger the issue:
1. It was detecting external subs and basing the time off of that, rather than the internal ones only
2. It was detecting external audio tracks with similar names (which had not been trimmed yet) and basing the time off of that

**Comment by clsid2** [comment] 2021-01-05 12:28
External subs should not have any effect on duration.

You can disable loading of external audio track if desired.
Options > Playback > Auto-load audio files
By default it loads files with same base filename as the video. Similar to how subtitles are loaded.

Ultimately the files that have issues can be considered broken. LAV Filters will likely get a workaround to deal with this in the future by ignoring duration of embedded subtitles tracks. But since it is an external component, I will close this issue for now as there is nothing to fix in the player itself.

**Closed as completed by clsid2** 2021-01-05 12:28 UTC
