### ISSUE TITLE
MPC Video Renderer: Bug reports, feedback, and discussion

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2870] opened 2024-06-24 11:41 UTC
In this topic you can discuss issues with MPC Video Renderer.

**Answers to frequently asked questions**

Read this first:
[FAQ](https://github.com/clsid2/mpc-hc/issues/2869)

**Official bug tracker**

https://github.com/Aleksoid1978/VideoRenderer/issues

That is also the place to make feature requests.

**Comment by MadokaAyukawa** [comment] 2024-07-02 19:44
I have R set to Reload Subtitles. I produce and edit subtitles. After an edit I will tap R to reload the subtitles in MPC-HC to check that it looks correct. This worked fine for many years with EVR (Custom presenter) with either the internal subtitles handler or libass. This also works fine with MPCVR and the internal subtitle handler.

However, after a few reloads using MPCVR and libass, the video will freeze in full screen or windowed mode. The audio will still play. I will have to have Windows close the program. It can happen on the first reload or after one or two reloads.

![image](https://github.com/clsid2/mpc-hc/assets/44476321/ac4d4ac5-cd48-4d0d-aa3d-31653e81f746)

**Comment by clsid2** [comment] 2024-07-02 20:58
It is due to call to `ConnectionMediaType()` in `CMainFrame::UpdateSubtitleColorInfo()`. Triggers a deadlock in MPCVR.
Also happens without libass.

Edit: fixed

**Comment by Raccffy** [comment] 2024-07-04 20:40
Playing a video with BT.2020 transfer primaries and BT.2020 non-constant matrix coefficients cause input format text go out of the background.

More specifically, second indented line in the "Input format" block is very long.

![Zero is out of bounds.](https://github.com/clsid2/mpc-hc/assets/165374321/77b09e69-8e01-4f2c-84de-60032781c44e)

**Comment by Dantrigger** [comment] 2024-07-22 07:51
Quick question, does the renderer  support Dolby Vision playback for BDMV rips? Or DV is only  supported in MKV and MP4 formats?

**Comment by clsid2** [comment] 2024-07-22 12:35
Try it and find out.

It does not support DV variants that use extension layer.

**Comment by Wepeell** [comment] 2024-07-23 02:41
When I use MPCVR with Hardware Device to use in LAV Video Decoder set to Automatic (Native), 4K 60 FPS videos only play at around 40 FPS and causes the video to get out of sync with the audio. If I set it to my specific graphics card (and forces copy-back) it seems do play fine. With madVR both of these settings perform the same. Is this expected behavior?

**Comment by Dantrigger** [comment] 2024-07-23 02:50
> Try it and find out.
> 
> It does not support DV variants that use extension layer.

Thanks for the reply, I hadn't realized that CTRL+J worked to show video statistics. And as I thought, BDMV rips with enhancement video layer only play the HDR10 layer. Looks like there is still no solution to get full DV Profile 7 support in PC, and by the looks of it, it will never happen.

**Comment by clsid2** [comment] 2024-07-23 11:21
> When I use MPCVR with Hardware Device to use in LAV Video Decoder set to Automatic (Native), 4K 60 FPS videos only play at around 40 FPS and causes the video to get out of sync with the audio. If I set it to my specific graphics card (and forces copy-back) it seems do play fine. With madVR both of these settings perform the same. Is this expected behavior?

In Windows Settings App, in advanced display settings, you can specify the preferred GPU that should be used by MPC-HC (and other individual apps).
You did not mention which GPUs you have, so I can't comment on the problem itself. Likely your integrated one has poor performance.

**Comment by Wepeell** [comment] 2024-07-23 12:50
> In Windows Settings App, in advanced display settings, you can specify the preferred GPU that should be used by MPC-HC (and other individual apps). You did not mention which GPUs you have, so I can't comment on the problem itself. Likely your integrated one has poor performance.

I have an RTX 2070 Super and a Ryzen 3700X which doesn't have any integrated graphics so I only have the one 2070 Super to select as my device. In the Windows settings it only gives me "Power saving" and "High performance" options for the 2070 and they both perform as described with D3D11 Automatic (Native) selected in LAV. D3D11 Copy-Back works fine but I was under the impression that Native is supposed to perform better than Copy-Back.

**Comment by clsid2** [comment] 2024-07-23 13:02
That one should work fine with native mode. Maybe try different version of NVIDIA driver.

Press Ctrl+J and make a screenshot.

**Comment by Wepeell** [comment] 2024-07-23 17:55
The first few seconds plays fine but then the frame rate drops and the sync offset shoots up. 

![Screenshot 2024-07-23 194527](https://github.com/user-attachments/assets/5765345e-06dc-4c1f-b77f-68bb8c2ca0e0)

I don't know much about video playback so maybe I have a misconfiguration somewhere. 

![Screenshot 2024-07-23 194622](https://github.com/user-attachments/assets/c43a75bf-b41a-4f52-8531-8c42eb5f614a)
![Screenshot 2024-07-23 194638](https://github.com/user-attachments/assets/436bab2c-d3f7-4546-86f9-38729e88fa81)

I'm only 1 or 2 updates behind the latest Nvidia driver but I'll try updating and if it doesn't fix anything I can just use copy-back for the time being.

**Comment by Allen-Kwan** [comment] 2024-07-26 08:04
Hello, I'm having troubles with my AMD driver which causes MPC-HC 2.3.3 to display a black screen when it tries to play a video.

I'm trying to disable hardware acceleration and can only find references to old versions of MPC where there was a "Video Renderer" option.  This option doesn't seem to exist now (I can only see Audio Renderer)  Is there anyway to disable hardware acceleration in this current version?

Thank you.

**Comment by Epidemilk** [comment] 2024-07-29 20:29
I'm getting weird crashes in fullscreen mode. Windows 11, NVIDIA 4060. Displays completely cut out, unresponsive to mouse/keys, sometimes the audio will keep playing, and I have to force power down.

Even out of fullscreen, sometimes the video will freeze and audio continues, but at least then I can just close it and try again.

It's been problematic for the last few versions- what settings should I tinker with?

**Comment by clsid2** [comment] 2024-07-29 20:43
If graphics driver crashes you need to try different version of the driver.

Win+Ctrl+Shift+B is Windows shortcut for restarting driver.

**Comment by Epidemilk** [comment] 2024-07-30 19:12
I'm on the most current NVIDIA driver, not sure what else I should be trying?

**Comment by clsid2** [comment] 2024-07-30 20:45
Most current driver is not necessarily the best one. NVIDIA drivers are full of bugs. There are literally dozens of previous drivers that you can try.

**Comment by Epidemilk** [comment] 2024-07-31 20:13
I sniffed around a little, went in my display settings, changed some power management setting I know forget and turned off vertical sync, seems okay now!

**Comment by Joe2500** [comment] 2024-08-02 03:50
how do i hide the file name that appears for several seconds when opening a video? i can't find anything related to it in the settings.

**Comment by clsid2** [comment] 2024-08-02 12:01
options > player > user interface > uncheck show OSD

**Comment by fcueto** [comment] 2024-08-09 18:46
When I play DV content using mpc-hc 2.3.4 it is working and improves image quality considerably, but... it stops working in full-screen mode unless the seekbar is showing.
- Prefer DV over PQ and HLG is unchecked
- Passthrough to display is checked
- Convert to SDR unchecked
- Windows HD is "Allow turn on/off"

**Comment by clsid2** [comment] 2024-08-09 20:56
Convert to SDR should never be unchecked. It only converts when passthrough is not possible.

For problem:
Make screenshot with Ctrl+J overlay enabled.
Post issue here:
https://github.com/Aleksoid1978/VideoRenderer/issues

**Comment by fcueto** [comment] 2024-08-10 13:46
> Convert to SDR should never be unchecked. It only converts when passthrough is not possible.
> 
> For problem: Make screenshot with Ctrl+J overlay enabled. Post issue here: https://github.com/Aleksoid1978/VideoRenderer/issues

I did

**Comment by xenrohachi** [comment] 2024-08-21 22:49
I recently ran into a similar issue and it ended up being image scaling in the nvidia 3d settings. Even if it’s only enabled on one game/profile and not universally, it’ll still cause HDR to work only when the seek bar is active.

**Comment by APoL0xx** [comment] 2024-09-02 21:55
In mouse settings the "Player Menu" shortcut corresponds to "Player Menu (full)" and vice versa, if you could fix this would be nice.

**Comment by IIIelKot** [comment] 2024-09-06 09:45
I have a question about HDR playback. I have HDR in Windows enabled permanenty, monitor report that it's in HDR mode, games in HDR run without "screen go black for a (few) second", HDR video in windowed mode does the same. But when i switch to fullscreen mode - "screen go black", when MPC ui is displayed over (osd, seekbar) - "screen go black", when it dissappears - "screen go black", when Windows displayed over (win+g, alt+tab) - "screen go black". And all that time Ctrl+J indicates that the videoframes are in HDR.
Can something be done with that behavior?

**Comment by clsid2** [comment] 2024-09-06 10:39
I can only suggest to complain to your graphics driver vendor about it.

**Comment by KayasamiX** [comment] 2024-09-09 18:54
The Player does not emulate the colors well, for example I am opening a song by Lepoca and the video looks very strange, I have not touched the brightness and contrast settings

![Captura de pantalla 2024-09-09 145223](https://github.com/user-attachments/assets/5e0a3051-a80d-45d8-9c69-7f526a6a654c)

**Comment by KayasamiX** [comment] 2024-09-09 20:17
I don't know much about this so do I have to contribute?
![image](https://github.com/user-attachments/assets/37dfd741-4810-4373-b55f-acf010bbccbe)

**Comment by KayasamiX** [comment] 2024-09-09 23:18
Oh, well, What can I do so that the colors of the video appear correctly? For example, I downloaded this music::
![image](https://github.com/user-attachments/assets/e5ab3f1e-1c7f-4a15-af57-d4e7f1140110)

but when I watch the video, the colors don't look correct, this happens to me with any other video
![image](https://github.com/user-attachments/assets/925dd284-de79-49cf-8b8d-54b07f1f7d0b)

Sorry to be a bit silly about this. :>

**Comment by User1X1** [comment] 2024-09-15 01:27
MPC-HC (x86) 2.3.5 

Double click on video still activates fullscreen even if it is not designated in the keyboard options.

**Comment by DarthVengeant** [comment] 2024-09-23 07:41
Video's are aligned with black bar on bottom once I go full screen, meaning the video is pushed up top with all the black below it, not in the middle where it should be with black on top and bottom. Something is off with alignment here. I thought it was just mp4 files, but now it is also mkv after installing 2.3.5. I don't know how to fix this. I've looked through all the settings and this is perplexing me. Please help? VLC, WMP, and other programs don't do this, just MPC. I have the newest version 2.3.5 64. I also have an issue where when I minimize a video it goes to the hidden icons tray, and I don't want it to do that. I want it to minimize to taskbar and stay there. Help? Thanx.

**Comment by maratnugmanov** [comment] 2024-09-23 10:32
I have a monitor with integrated audio attached via USB-C (it works the same with HDMI). I am not playing on my PC and need audio only for system sounds basically. When my PC goes to sleep after some inactivity the player cannot continue playing sound until I reopen the file. It's a series of lessons so one of them is opened all the time. Is this something that could be addressed? Or maybe more information is needed? Thanks, I appreciate your software and using it for years now.

**Comment by SSoM** [comment] 2024-09-24 20:05
MPC-HC.2.3.5.27.x64. Windows 10. Video refuses to play. No error message, just black screen. Video track is AV1.

**Comment by wojtulace** [comment] 2024-10-14 08:25
How to make MPC display the current playback speed?

**Comment by Salem226** [comment] 2024-10-14 11:39
i have this problem with all vedios showing in pictures
all vedios have much shadows
using widows 10
i need solution
thanks in advance

![1](https://github.com/user-attachments/assets/c323762d-4878-44b5-aaa4-ab6250314b2a)
![2](https://github.com/user-attachments/assets/4d467cc7-6e22-4cc6-997f-c4514df1ee85)

**Closed as completed** 2024-10-14 11:52 UTC

**Comment by Salem226** [comment] 2024-10-14 12:23
> Press Ctrl+J to show debug overlay and make new screenshot.
> 
> Disable RTX HDR and SuperRes.
![3](https://github.com/user-attachments/assets/e145be61-94c9-436d-87ad-dad4b78525ee)

![Screenshot 2024-10-14 152535](https://github.com/user-attachments/assets/b1930ce9-5faf-428f-b7b0-d9488634061b)

**Comment by Salem226** [comment] 2024-10-14 12:24
> Disable RTX HDR and SuperRes

How ?
first time to use  MPC

**Comment by Salem226** [comment] 2024-10-14 12:38
> You are currently not using MPC Video Renderer. Options > Playback > Output
> 
> Dark video is likely bug in your Intel graphics driver.
> 
> Uninstall MPC-HC and install K-lite Codec Pack Standard. That will automatically do proper configuration for MPC-HC and correct some bad Intel settings.

link for this program?

**Comment by Salem226** [comment] 2024-10-14 12:43
> https://files2.codecguide.com/beta/K-Lite_Codec_Pack_1862_Standard.exe

the same problem happenes

**Comment by clsid2** [comment] 2024-10-14 12:54
Look in Intel graphics settings. Maybe something is wrong there.

I can not help you any further.

If problem only happens with this specific video, then the file is probably just badly encoded.

**Comment by Salem226** [comment] 2024-10-14 12:56
> Look in Intel graphics settings. Maybe something is wrong there.
> 
> I can not help you any further.
> 
> If problem only happens with this specific video, then the file is probably just badly encoded.

who can help me?
