### ISSUE TITLE
DVB TV tuner. There is a signal, does not find channels

### ISSUE THREAD

**Issue by ruboard** [clsid2/mpc-hc#1354] opened 2021-10-17 12:28 UTC
Specs: http://www.beholdtv.com/products/t8/
![0](https://user-images.githubusercontent.com/79255903/137626924-89542505-50af-45a6-afd2-5458bdcfdffa.JPG)
![6](https://user-images.githubusercontent.com/79255903/137627601-53a562ac-ba84-42f6-ab44-ede6219479ef.jpg)
![1](https://user-images.githubusercontent.com/79255903/137626921-3a47ef05-44fe-4b91-b25c-a21785238471.JPG)
![2](https://user-images.githubusercontent.com/79255903/137626920-ba04185f-c849-437a-8190-d7ca5925683b.JPG)

![3](https://user-images.githubusercontent.com/79255903/137626922-90a28aed-0f89-45a4-8b98-c5bac432c420.JPG)
![4](https://user-images.githubusercontent.com/79255903/137626923-737717b3-5bdd-4fb5-8c8b-944f5ff68f0c.JPG)

the program and driver works great
the player does not find any DVB-C (no crypt) channel, although there is a signal
What additional information can I provide to get hope for support?

p.s. please write easier, I use a google translator

**Comment by adipose** [comment] 2021-10-23 19:44
Do I understand right that you have a channel at 362000?

Channel scan started at 286000.  8000 bandwidth.  It will never get to 362000.  358000 and 366000 will be tried.

If I understood correctly, try scanning starting (and ending) at 362000 to see if you get anything.

**Comment by ruboard** [comment] 2021-10-24 08:23
No, it doesn't help. I tried so you suggested. All the same, you can see that the signal is present but the channels are not found.
I tried both 64 and 32 version of the player. (With default settings. portable)
![ScreenGif](https://user-images.githubusercontent.com/79255903/138586241-ac8c0902-df88-46d5-8129-ae67faca7eaf.gif)
to no avail

**Comment by ruboard** [comment] 2021-10-24 15:43
**The problem was cleared up. The value is not fixed in the filter settings "symbol rate"
The default is 6875
TV operator requires 6750**

![Снимок](https://user-images.githubusercontent.com/79255903/138601564-94ca8532-6406-44a8-bac0-d677a400f15d.jpg)
**is there a way to capture this value?**

**Comment by adipose** [comment] 2021-10-24 17:03
It can be set and retrieved. Does it have to be changed every time you reopen mpchc?

**Comment by ruboard** [comment] 2021-10-24 17:29
every time I change channels, the symbol rate is reset to the default.
I understand that without introducing this parameter into the player, nothing will work?!
very strange that it is not in the player. This is one of the main parameters DVB

**Comment by adipose** [comment] 2021-10-25 19:46
I'm not sure about that, but maybe 99% of the time, the symbol rate default is the same as what the operator expects.  Perhaps in the driver, you could also change the default, somehow.

I've made a test build that simply hard codes the symbol rate to 6750, to see how it works for you. If it works well, I could have the channels save the symbol rate.

https://mega.nz/file/xF5XHIYI#bBq5OYD8D1RCvunoZm4CHi-lOr3m17jEgXrsiAxj0e4

**Comment by ruboard** [comment] 2021-10-26 14:58
> I've made a test build that simply hard codes the symbol rate to 6750, to see how it works for you. If it works well, I could have the channels save the symbol rate.

earned immediately!
low bow, and huge thanks!
I'm waiting for the corresponding line in the list of changelog next release)

if useful;
API & SDK http://www.beholdtv.com/support/downld.htm#4
soft http://www.beholdtv.com/files/btv_v528.Zip
driver http://www.beholdtv.com/files/drv_v5520.zip

Filters currently loaded:
  - BDA MPEG2 Transport Information Filter
  - MPEG-2 Sections and Tables
  - LAV Audio Decoder (internal)
  - MPC Audio Renderer
  - Расширенный рендер видео (EVR custom pre...
  - LAV Audio Decoder (internal)
  - LAV Video Decoder (internal)
  - MPEG-2 Demultiplexer
  - Behold TV T8: DVB-C Capture [Slot 4]
-   **Behold TV T8: DVB-C Frontend [Slot 4]**
  - Microsoft Network Provider

the selected filter is configured through bhkspex.dll http://file.sampo.ru/ts4n95

**Comment by adipose** [comment] 2021-10-27 02:34
https://mega.nz/file/UY5nAApa#9hoyk-LxQVk-ixR1QHzWvIvD3g3ekMBar33Yok-Jl5s

Here's a test build with the symbol rate feature enabled.

**Comment by adipose** [comment] 2021-10-27 02:42
https://github.com/clsid2/mpc-hc/pull/1366

**Comment by ruboard** [comment] 2021-10-27 15:02
> Here's a test build with the symbol rate feature enabled.

the setup works fine, finds all possible channels, but none shows (black screen). When you call the panel with the filter, you can see that there is a value set by the setting (6750)

**Comment by adipose** [comment] 2021-10-27 16:01
https://mega.nz/file/4YYwHZiD#crFiZsoD9R1pyWp5MlU0RryU0OCEkV8ddUmF0WixQGc

**Comment by adipose** [comment] 2021-10-27 16:02
Not sure if it will help, but I posted another build with updated filters.

**Comment by ruboard** [comment] 2021-10-27 16:29
> Not sure if it will help, but I posted another build with updated filters.

helped, it works!
after the first channel search with the appointed symbol rate, it does not show any channels, but after the first restart of the player, it shows all previously found channels.  And there is no sound on all channels

**Comment by adipose** [comment] 2021-10-27 21:33
Not sure of the cause.  Setting the symbol rate is a very minor change--in my testing, it didn't even affect my ability to read channels, whether I set it or changed it.

However, in latest builds of mpc-hc, I'm having trouble decoding the stream, whether I touch the symbol rate or not.  So maybe an unrelated problem.

**Comment by clsid2** [comment] 2021-10-27 21:48
Did decoding issue start after 1.9.16? Maybe related to LAV update?

**Comment by adipose** [comment] 2021-10-28 04:51
I don't think so, but it's possible.  The stream I was testing with still works, but many other streams I tried do not. It may be an issue with my receiver, as recently it's started bluescreening when using it for very long.

**Comment by adipose** [comment] 2021-10-29 00:23
@ruboard, I cannot purchase the receiver you have, there.  Any chance you would send me one from Russia?

**Comment by adipose** [comment] 2021-10-29 00:35
> 
> 
> > Not sure if it will help, but I posted another build with updated filters.
> 
> helped, it works! after the first channel search with the appointed symbol rate, it does not show any channels, but after the first restart of the player, it shows all previously found channels. And there is no sound on all channels

Just to understand, you previously had sound on channels, but with this build, you do not?  I can't understand why the change I made would cause that.  The filters are slightly different version.

What happens if you take latest MPC build and manually set the symbol rate? Do you get audio?

**Comment by adipose** [comment] 2021-10-29 01:47
https://mega.nz/file/tc4CEAwS#Cb75CgIoYiTKn-epgpb0b4y1-BDPKQjZ85bJFSYH7_g

Here's another build.  No changes, but I updated my VS build tools to a newer version.  I doubt it will make any difference, but we can rule that out.

And here's another build, without the symbol rate feature, to test latest source, and see if it works any different:

https://mega.nz/file/1coUXISa#YwPDFcqY88wk8Ya-1kz6JFj5OAWyL0RYFRsQY2hNcsA

**Comment by ruboard** [comment] 2021-10-29 13:22
>  I cannot purchase the receiver you have, there. Any chance you would send me one from Russia?
  
unfortunately beholder stopped producing tuners a long time ago. And nobody sells used ones. The T8 is nowhere to be found.

**Comment by ruboard** [comment] 2021-10-29 13:54
> https://mega.Nz/file/tc4CEAwS#Cb75CgIoYiTKn-epgpb0b4y1-BDPKQjZ85bJFSYH7_g
finds and shows channels. no sound
Filters currently loaded:
  - BDA MPEG2 Transport Information Filter
  - MPEG-2 Sections and Tables
  - Расширенный рендер видео (EVR custom pre...
  - LAV Video Decoder (internal)
  - MPEG-2 Demultiplexer
  - Behold TV T8: DVB-C Capture [Slot 4]
  - Behold TV T8: DVB-C Frontend [Slot 4]
  - Microsoft Network Provider
  
> https://mega.Nz/file/1coUXISa#YwPDFcqY88wk8Ya-1kz6JFj5OAWyL0RYFRsQY2hNcsA
does not find channels until you set a value in the filter panel and in the search. Next, it finds channels, but does not show until you specify a value in the filter again. Is there sound
  - BDA MPEG2 Transport Information Filter
  - MPEG-2 Sections and Tables
  - MPC Audio Renderer
  - Расширенный рендер видео (EVR custom pre...
  - LAV Audio Decoder (internal)
  - LAV Video Decoder (internal)
  - MPEG-2 Demultiplexer
  - Behold TV T8: DVB-C Capture [Slot 4]
  - Behold TV T8: DVB-C Frontend [Slot 4]
  - Microsoft Network Provider

**Comment by adipose** [comment] 2021-10-29 16:47
Great, thank you for testing.  I have no idea why, but I will look through the code again to try to see what could cause the issue.

**Comment by adipose** [comment] 2021-10-29 18:28
https://mega.nz/file/Ud5CxILC#oU-IMeif3caAHXTtScC01UfmdUY1Vjv0yTMjO1ypJH4

Found one bug that could affect loaded channels.  Hopefully that's the problem.

**Comment by ruboard** [comment] 2021-10-29 20:34
> Found one bug that could affect loaded channels. Hopefully that's the problem.
super, everything started right away, set the value, found the channels, there is sound

**Comment by clsid2** [comment] 2021-10-31 15:43
Patch has been merged.

**Closed as completed by clsid2** 2021-10-31 15:43 UTC
