### ISSUE TITLE
Scale volume control slider relative to control button size

### ISSUE THREAD

**Issue by rainman74** [clsid2/mpc-hc#2987] opened 2024-08-10 13:32 UTC
Why has the slider for the volume control become so small in the current versions 2.3.3 and 2.3.4?

I use 3440x1440 and 140% DPI.

![image](https://github.com/user-attachments/assets/113a975f-fdd7-4e96-885b-4191f1a07556)

**Comment by adipose** [comment] 2024-08-10 14:14
Hmm, what scale for the toolbar do you have?

**Comment by clsid2** [comment] 2024-08-10 14:36
Yes, buttons look larger than standard.

**Comment by rainman74** [comment] 2024-08-10 16:32
> Yes, buttons look larger than standard.

Look above, 40 pixels

**Comment by adipose** [comment] 2024-08-10 17:07
Thanks. I didn't realize because I can't read the labels.

I don't think we changed anything there.  Did the issue start with the volume percentage showing?

**Comment by adipose** [comment] 2024-08-10 17:22
Also can you show a screenshot from 2.3.2?

**Comment by rainman74** [comment] 2024-08-10 21:01
> Also can you show a screenshot from 2.3.2?

Previously, the volume slider scaled with the controls:
![image](https://github.com/user-attachments/assets/bafa2777-75f2-45d6-a230-bc73e0681482)

**Comment by adipose** [comment] 2024-08-11 02:18
> > Also can you show a screenshot from 2.3.2?
> 
> 
> 
> Previously, the volume slider scaled with the controls:
> 
> ![image](https://github.com/user-attachments/assets/bafa2777-75f2-45d6-a230-bc73e0681482)
> 
> 

Visually it looks like you have different toolbar scaling in that screenshot. I will see if I can reproduce it.

**Comment by adipose** [comment] 2024-08-15 17:48
I went back to 2.0 and the volume control does not scale with the toolbar height.  In the screenshots where it appears to scale correctly, you appear to be using the default toolbar size, and where it does not, you appear to be using a larger one (40).

If you check below, you'll see that on version 2.3.3 or so, I actually increased the size of the volume bar in the modern look.  But it has never scaled with the toolbar.  The main problem with scaling it is, the widget assigned to the space uses a fixed width, while the toolbar buttons scale width and height.  If the height of the volume control is going to change, it needs to get wider, too.

Toolbar Height 24

On version 2.0.0:

![image](https://github.com/user-attachments/assets/9299c533-4268-4b57-98f5-b9f2c876d8b7)

2.3.1:

![image](https://github.com/user-attachments/assets/14519192-24d3-4930-a273-8bb8a6d12408)

2.3.4:

![image](https://github.com/user-attachments/assets/0a559371-61bc-42a1-b5ea-89eb85279fc4)

Toolbar height 40:

2.3.1

![image](https://github.com/user-attachments/assets/846b833c-569e-4f67-93c5-244f48ad8781)

2.3.4

![image](https://github.com/user-attachments/assets/70fd95ea-e9df-493b-a065-c0a6d6edfc43)

**Comment by clsid2** [comment] 2024-08-15 19:14
DPI scale the whole volume slider? Both width and height.

**Comment by adipose** [comment] 2024-08-15 19:15
> DPI scale the whole volume slider? Both width and height.

It should be scaled because it's a control that's being painted in a custom way.  It just doesn't scale with the toolbar buttons.

**Comment by clsid2** [comment] 2024-08-15 19:26
Base its size on the button size?

SVG buttons are dpi scaled, PNG/BMP are fixed size.

**Comment by adipose** [comment] 2024-08-15 19:27
Yeah, I can do that.  I was thinking maybe it should be part of the toolbar with some space allocated.  It's no longer drawn at all like a slider.

**Comment by clsid2** [comment] 2024-08-15 19:41
Yeah, whatever you think is best. A new custom widget for modern theme would be fine. Then use old slider for classic theme only.

**Comment by rainman74** [comment] 2024-08-15 21:13
> I went back to 2.0 and the volume control does not scale with the toolbar height. In the screenshots where it appears to scale correctly, you appear to be using the default toolbar size, and where it does not, you appear to be using a larger one (40).
> 
> If you check below, you'll see that on version 2.3.3 or so, I actually increased the size of the volume bar in the modern look. But it has never scaled with the toolbar. The main problem with scaling it is, the widget assigned to the space uses a fixed width, while the toolbar buttons scale width and height. If the height of the volume control is going to change, it needs to get wider, too.

sorry I meant 1.9.x

**Comment by adipose** [comment] 2024-08-15 22:28
1.9.0 looks the same.

![image](https://github.com/user-attachments/assets/f8e34f1e-4b7d-4040-9f6d-a219c9fe0caf)

**Comment by rainman74** [comment] 2024-08-16 00:21
> 1.9.0 looks the same.

Then I was wrong and perhaps I only noticed that it was smaller because of the new text specification in percent.

**Comment by adipose** [comment] 2024-08-17 23:17
https://github.com/clsid2/mpc-hc/pull/3006

**Closed as completed** 2024-08-19 17:44 UTC

**Comment by rainman74** [comment] 2024-08-30 14:22
![image](https://github.com/user-attachments/assets/07ea1e7b-c0de-4d6e-8390-5dae2eff6898)

Excellent! 👍

**Comment by nosystemworks** [comment] 2024-10-25 08:11
While on the topic of adjusting the volume control slider - is it possible to remove the percentage text and keep only the slider like it was before?

**Comment by clsid2** [comment] 2024-10-25 11:30
No
