### ISSUE TITLE
Getting "File in Use" message when trying to delete video with shift+suppr

### ISSUE THREAD

**Issue by Uberlime** [clsid2/mpc-hc#545] opened 2020-07-23 13:21 UTC
Strangely doesn't happens for all files but like 80%, tried running mpc as admin, i use madvr, issue wasn't there last version, when i use "what is locking this file" it shows MPC-HC64.exe, thx in advance for any insight.
I suspect the "Assigned Delete as a default key binding for "Move to recycle bin" action" change to have messed up with my settings smh...

**Comment by Uberlime** [comment] 2020-07-23 13:38
Rolled back to 1.9.3 & everything works fine...
Also it's a bad idea to run as admin as it disables drag & drop.

**Comment by clsid2** [comment] 2020-07-23 18:34
You can't delete a file that is in use during playback. You must close the file first (Ctrl+C) or exit the player. The keybinding change is not the cause of your problem.

If you did close the player, but the mpc-hc64.exe process is still active in the Task Manager, then you need to check why it isn't closing properly. Might be caused by a third part filter that you are using.

**Comment by Uberlime** [comment] 2020-07-25 12:59
> You can't delete a file that is in use during playback. You must close the file first (Ctrl+C) or exit the player. The keybinding change is not the cause of your problem.
> 
> If you did close the player, but the mpc-hc64.exe process is still active in the Task Manager, then you need to check why it isn't closing properly. Might be caused by a third part filter that you are using.

I don't mean to be a d, but you can, & always could till latest version, for me. File is playing I press shift+suppr => file is sent to recycle bin, (if you google it it's actually a feature that is widely researched & for me made an important part of this player's appeal) repeatable ad infinitum, with player going to "home" mode, pardon my french. 
Latest build removed this possibility 4 me smh, on most files, so i rolled back. Fact, I'm pretty sure u can check. 
Anw, ty for the concern & answer, looking forward to an eventual fix & cordial regards 4 all the hard work.

**Comment by clsid2** [comment] 2020-07-25 13:53
This is not the fault of the player. The internal filters are causing the file to be "in use". Solution is disable them and use external filters. Delete works if using "File Source (Async)" as the file source filter. If using external LAV Filters, this means that you need to set preferred splitter to "use merit" with Codec Tweak Tool.

**Comment by clsid2** [comment] 2020-07-25 14:18
Just use the delete functionality of the player. That closes the file before deleting it. If you press PageDown afterwards it will even move to next file in the folder.

**Comment by Uberlime** [comment] 2020-07-27 12:58
> Just use the delete functionality of the player. That closes the file before deleting it. If you press PageDown afterwards it will even move to next file in the folder.

It's like you're not reading me properly : Up to 1.9.4  => everything works fine, shift+suppr deletes file, even in use, with any filters, internal or external, when upgrade to 1.9.5 & so on => doesn't work anymore.
Even if the file is closed in MPC, i can't move it to the recycle bin from the playlist, using the context menu, same file in use message.
What surprises me is that not more ppl are signaling this issue & that it's apparently so hard for you to understand or believe me. Have u tried to replicate it ? It takes but a minute.
Also, how can it not be the fault of the player, when the only change i make between the two situations is upgrading the player ?!!!
It's no big deal anw since 1.9.4 is largely enough for my needs & it keeps the functionality intact. I'll test it on another computer when I've access to1.

**Comment by clsid2** [comment] 2020-07-27 19:22
I fixed an issue where it could loop back to the same playlist entry. Try this version:
https://github.com/clsid2/mpc-hc/releases/download/1.9.6.7/MPC-HC.1.9.6.32.x64.zip

**Comment by BoomerangAide** [comment] 2020-08-03 10:18
I think I have the same issue.
On previous versions (1.9.1, 1.9.2 or slightly more recent), after finishing watching a playlist, I cleared it and deleted the folder with the video files afterward.
But when I tried it just now, it said a file (the last one in the playlist) was in use, and prevented the deletion until I closed the player.
Could it be "Clear Playlist" no longer properly unload the video?

I'm posting this since 1.9.7 doesn't report such an issue to be fixed and the comment just before seems to be a version before 1.9.7, so I assume it would not work and produce some regression.Maybe I'm wrong about that?

**Comment by clsid2** [comment] 2020-08-03 12:09
1.9.7 contains a fix for this. But there may be more issues. Try it and let me know.

**Comment by BoomerangAide** [comment] 2020-08-04 18:50
The issue is still there with 1.9.7
I tried to load another playlist, the video from the new playlist opened, but the file was still locked from deletion.
Only completely closing mpc hc unlocked it.

edit: I just thought, could it be related to "Open Folder containing the file" ? Since I did use that to go toward the folder containing the videos to delete.

edit2: Tried to experiment with the playlist I'm currently watching, by renaming the folder instead of deleting, but there was no lock.
Until I get another meaningful experience, another thing I can think of, is that my recent playlists (causing the issue) may have contained .mp4 or .mkv with chapters and/or subtitles.
If that is important, it may take me a while before experiencing it again.

**Comment by clsid2** [comment] 2020-08-04 19:54
That just opens Explorer. That should not matter.

In the options of internal LAV Splitter, enable the tray icon. Does you see two icons when the problem occurs? That could mean that previous file wasn't closed successfully.

I am not able to reproduce it.

**Comment by BoomerangAide** [comment] 2020-08-09 14:09
Okay, changed my schedule for my next playlist to be one containing mkv files, opened first video, cleared the playlist (causing the tray icon to disappear), then tried to rename the folder containing the videos, and it failed with "file already open in another program" (since it has same requirement as deleting all files in folder).
I hope this will help locate the issue.

edit: oh right, tried it just in case: if displaying tray icons also for LAV video and LAV audio (in addition to splitter), they do all disappear on clearing the playlist.

**Comment by clsid2** [comment] 2020-08-09 19:07
I add a few files to playlist.
Play first file.
Right-click on playlist -> clear
This stops playback and closes file.
I leave the player open.
Renaming the folder that contains the files works just fine.

I this what you were doing?

**Comment by BoomerangAide** [comment] 2020-08-10 05:57
Yes, this is it. Only that in my case, the renaming won't work. Did you try with mkv with subtitles and chapters (what I tried last), or with .avi (what I confirmed to not cause the issue) ?

**Comment by Uberlime** [comment] 2020-08-10 10:35
lol, Clsid, ever the dedicated, haven't tried 1.9.7 yet, gratitude nonetheless @BoomerangAide gl with ur experiences XD!

**Comment by clsid2** [comment] 2020-08-10 12:39
I have been able to reproduce now.

1) Play any file with embedded subs. Sub format does not seem to matter since it happens with both ASS and PGS.
2) Close file with Ctrl+C
3) Try to rename the file (or its parent folder)

Problem occurs only when using LAV Splitter Source. It does not happen with File Source (Async) + LAV Splitter.

@nevcairiel
Possible bug (in FFmpeg) where file handle isn't closed?

**Comment by clsid2** [comment] 2020-08-11 18:57
Fixed.

**Closed as completed by clsid2** 2020-08-11 18:57 UTC

**Comment by BoomerangAide** [comment] 2020-10-19 11:56
I can confirm moving a file, after starting playing the next one, in conditions that would not have worked before, worked properly in 1.9.7.96
Thanks
I hope it won't reopen the issue.
