### ISSUE TITLE
Subtitles not detected

### ISSUE THREAD

**Issue by syffer72** [clsid2/mpc-hc#1723] opened 2022-05-23 17:28 UTC
Hello,

I've an MKV movie which has some sub tracks (13 exactly, PGS format) which are not detected by MPC-HC.
The same file works perfectly in MPC-BE for example, and you can select the tracks, and they're displayed as they should be.
Never had this issue before, tried rollbacking to 1.9.20 (I'm using the latest 1.9.21.2) but didn't improve this situation.
The subtitles context menu is greyed out as if there was no subs at all.
I tried opening the file in mkvtoolnix and it detects perfectly the subs like MPC-BE.

The "MediaInfo" menu of MPC-HC does list all sub tracks perfectly.

**Comment by syffer72** [comment] 2022-05-23 17:31
Here are some details of the MediaInfo of 2 tracks: 

Text #1
ID                             : 6
ID in the original source medi : 4768 (0x12A0)
Format                         : PGS
Muxing mode                    : zlib
Codec ID                       : S_HDMV/PGS
Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
Duration                       : 2 h 55 min
Bit rate                       : 34.3 kb/s
Count of elements              : 4834
Stream size                    : 43.1 MiB (0%)
Language                       : English
Default                        : No
Forced                         : No
Original source medium         : Blu-ray

Text #2
ID                             : 7
ID in the original source medi : 4769 (0x12A1)
Format                         : PGS
Muxing mode                    : zlib
Codec ID                       : S_HDMV/PGS
Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
Duration                       : 2 h 54 min
Bit rate                       : 21.7 kb/s
Count of elements              : 3548
Stream size                    : 27.1 MiB (0%)
Language                       : French
Default                        : No
Forced                         : No
Original source medium         : Blu-ray

**Comment by clsid2** [comment] 2022-05-23 18:02
First check with the header editor of MkvToolNix to see if those subtitle tracks are not marked as disabled. It is very likely that this is the cause of your problem.

If that is not the case, then I need a link to this file. Otherwise there is nothing I can do to help.

**Comment by syffer72** [comment] 2022-05-23 19:24
Thank you for your quick answer !
Well you're 100% right, the tracks (and some audio as well) were just disabled, I don't know why, might be a muxing mistake I guess.
I didn't know you could mux it and not show it, it is not very obvious in mkvtoolnix either as there is no column showing if it enabled or not, just a menu on the right allowing to disable or enable the tracks !
Seems MPC-BE does not take this option into account and force enable all tracks I guess :).
Is there such a parameter in MPC-HC ?

Thanks a lot anyway, issue closed !

**Comment by clsid2** [comment] 2022-05-23 19:36
The correct behavior is to hide disabled tracks. That is the only behavior available.

**Closed as completed by clsid2** 2022-05-23 19:36 UTC
