### ISSUE TITLE
Brightness resets from -100 to 0 when jumping to the next item in playlist

### ISSUE THREAD

**Issue by bviktor** [clsid2/mpc-hc#159] opened 2019-11-12 19:50 UTC
Options/Miscellaneous/Brightness is the option, set it to -100, have some videos in your playlist. When the current item is finished and MPC-HC switches to the next video, brightness goes back to 0. As a bonus, the control shows it stayed at -100 but it's clearly visible it's not on -100.

One more bonus: if it's anything above -100, i.e. -99, it doesn't happen. Only if you set it to -100. Speaking of corner case...

**Comment by clsid2** [comment] 2019-11-13 13:01
-100 is working correctly here when moving to next file in playlist. I tried all compatible renderers. It might be a driver problem. For example Intel has some adaptive brightness option.

**Comment by bviktor** [comment] 2019-11-13 13:03
Did you try with manual switching or waited for the first video to run out and automatically jump to the next one? It happens in the latter case for me.

I can reproduce it on all my PCs though, not sure if any of them has anything other than Intel. In any case, Intel is like 60% of all PCs so some workaround would come handy.

**Comment by clsid2** [comment] 2019-11-13 13:15
Does it also happen if you press PageDown (next file) or Ctrl+E (reload file)?
Does +100 have same issue?
And contrast/hue/saturation?

**Comment by bviktor** [comment] 2019-11-13 23:28
Actually, sorry, I was wrong. It also happens to me on manual switching.

PgDn goes to the next chapter, not the next file. When it switches chapters, brightness stays at -100, but when it's the final chapter and it goes to the next file, it resets to 0.

Same with Ctrl+E. It resets brightness to 0.

Contrast and saturation don't behave like this, but hue does. Weird.

**Comment by bviktor** [comment] 2019-11-13 23:28
I'll try to test with an NV GPU asap. Possibly tomorrow at work.

**Comment by bviktor** [comment] 2019-11-13 23:33
Haven't mentioned yet, but MPC-HC is 1.7.13 x64, OS is Win10 x64, v1909 right now, but it behaved like this since forever (even in official MPC-HC before it hit the dust). Intel driver is always kept up-to-date via Intel DSA, and it has always been behaving like this over the years.

I have 3 PCs at home, one with an Intel HD 530, two with an Intel UDH 605, it works the same on all of them.

**Comment by clsid2** [comment] 2019-11-15 14:20
Try with latest version: 1.8.8
https://github.com/clsid2/mpc-hc/releases

**Comment by bviktor** [comment] 2019-11-23 23:12
Thank you. Unfortunately there's no change, it still resets. Can really no one reproduce this? :\

**Comment by adipose** [comment] 2019-12-08 19:00
@bviktor I couldn't reproduce this in casual testing.

Can you provide:

1. Video of it happening
2. Windows version, build, etc.
3. Any tweaks, video drivers, codec packs, etc. you might have installed
4. Export MPC-HC settings
5. Upload videos that can cause the issue.  If any video works, it should be easy to find a couple small ones.

If possible, test on a clean install of windows or VM to verify it's not 3rd party software.  Since no one else is experiencing this, it is likely something you are doing different--but that doesn't mean it's not a bug.

**Comment by clsid2** [comment] 2019-12-09 15:29
I have been able to reproduce it on a laptop.

**Comment by bviktor** [comment] 2019-12-09 16:05
Awesome, I just wanted to start a clean install of a Windows (to make sure it's not something specific to my setup), but then I won't do that :D

**Comment by clsid2** [comment] 2019-12-09 17:14
Fixed

**Closed as completed by clsid2** 2019-12-09 17:14 UTC

**Comment by bviktor** [comment] 2019-12-13 22:44
Awesome :) Is there any docs how to build mpc-hc? I'd love to give it a spin.

**Comment by clsid2** [comment] 2019-12-14 15:23
https://github.com/clsid2/mpc-hc/blob/develop/docs/Compilation.md
