### ISSUE TITLE
video stutter as a presentation glitch

### ISSUE THREAD

**Issue by mustafa811811** [clsid2/mpc-hc#744] opened 2020-11-14 07:16 UTC
thanks for the reply .. i tried both methods and they didn't work .. 1st i set the power mode in the Nvidia control panel to maximum performance then restart and 2ndly checked the disable fullscreen optimization on the exe itself but still it wouldn't be fixed 

but anyway i noticed that this doesn't occur when the windows hdr is ON so does this give you any clues ?!

this issue persisted despite upgrading the display drivers every 2 weeks

_Originally posted by @mustafa811811 in https://github.com/clsid2/mpc-hc/issues/733#issuecomment-727156903_

**Comment by clsid2** [comment] 2020-11-14 12:39
I can not fix this. This is not a bug in the player.

It is fault of the driver and how it interacts with madVR. When the menu/controls are displayed it switches out of HDR mode. Enabling HDR permanently in Windows avoids those switches.

You need to hope this gets fixed in the diver or hope that madVR gets updated to use Windows HDR directly instead of using NVIDIA HDR mode.

So right now your options are to either enable HDR in Windows, or to disable HDR passthrough in madVR settings and use Tonemapping with PixelShaders instead.

If you enable exclusive fullscreen in madVR, then madVR will draw the seekbar instead of the player. That can also help to prevent the issue.

**Closed as completed by clsid2** 2020-11-14 12:39 UTC
