### ISSUE TITLE
Freeze/hang on seek

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#455] opened 2020-06-11 19:05 UTC
I have changed decoder to D3D11 and it seems to freeze/hang a lot when seeking. 1.7.18 is a lot less prone to this problem but it still occurs. Not sure what other information I could provide so please let me know what is needed to diagnose this.

Edit: previously I thought issue was related to changed made in build 1.9.4.21, but I was mistaken

**Comment by clsid2** [comment] 2020-06-11 20:37
If it only happens with certain videos, then I need to know what they have in common.

Does it freeze permanently, or just for a short moment?

**Comment by clsid2** [comment] 2020-06-11 20:46
Does 1.9.4.18 have the same problem?

**Comment by ghost** [comment] 2020-06-11 21:47
I have made a mistake - I was hasty in reporting the issue. In addition to update I have also changed some settings. I did some testing and it seems issue occurs only when using D3D11 decoder. I have edited original post to correct my mistake.

I have tried several versions of MPC-HC and it is reproducible even with 1.7.18, but a lot harder. It can take over a minute of fiddling with seek bar to trigger the hang. With 1.8.5 issue can be reproduced fairly quickly and on 1.9.4.21 it hangs in under a second.

Videos I'm having issues with are short (under 20 seconds) and low resolution (approx 480p). It did happen once with a full length movie but I cannot reproduce this.

Freeze is permanent. CPU usage drops to 0% and only Task Manager can kill it.

**Comment by clsid2** [comment] 2020-06-11 23:19
Then the bug may be outside of the player. Which video renderer are you using? And which GPU?

Does it also happen with D3D11 copyback? If you select a hardware device in LAV Video then it switches to copyback mode.

**Comment by ghost** [comment] 2020-06-12 05:29
madVR with GeForce GTX 1070.

Good catch! I could not reproduce this issue on D3D11 copyback nor on D3D11 native with EVR renderer. It seems this occurs only when using madVR with D3D11 native.

Closing the issue as chances are this is madVR bug.

**Comment by clsid2** [comment] 2020-06-12 14:01
D3D11 will always use copyback with EVR. Native mode only works in combination with madVR or MPC Video Renderer.

You could try the latest beta version of madVR:
http://madshi.net/madVRhdrMeasure113.zip

**Comment by ghost** [comment] 2020-06-12 17:02
Beta version has same issue.
Out of interest I have also tried MPC Video Renderer and it works just fine, so I think it's madVR issue.

**Comment by clsid2** [comment] 2020-06-12 18:26
When it hangs. Open the Windows Task Manager, right-click on mpc-hc64.exe, and select "create dump". Zip the .dmp file and upload it somewhere. I can then notify the madvr developed about it. He might be able to pinpoint the bug with the dump.

**Comment by ghost** [comment] 2020-06-13 08:38
Here it is: https://www61.zippyshare.com/v/yL4749I3/file.html

**Comment by clsid2** [comment] 2020-06-13 12:03
Call stack:
![d3d11_hang_call_stack](https://user-images.githubusercontent.com/4704996/84568223-2ebf6080-ad7e-11ea-9024-162375ab5aeb.png)

@nevcairiel @madshi
It hangs on lock **m_csReceive** from CTransformFilter of baseclasses.

madshi, I have also send you a PM on doom9 about another crash in madVR.

**Comment by clsid2** [comment] 2020-06-15 21:47
I have gotten another dump where it also hangs in DeliverEndFlush after seeking. In that case no hardware acceleration was used.

**Comment by clsid2** [comment] 2020-06-21 20:37
Test this new version:
https://github.com/clsid2/mpc-hc/releases/download/1.9.5.6/MPC-HC.1.9.5.10.x64.zip

**Comment by ghost** [comment] 2020-06-21 20:53
Issue still occurs when using D3D11 native with madVR 0.92.17. Here's the new dump: https://www114.zippyshare.com/v/XVe1MvFR/file.html

**Comment by clsid2** [comment] 2020-06-21 21:28
@nevcairiel
Could you check out the dump above? Looks like a locking issue between two lav threads.
CLAVVideo::EndFlush() => wait on lock
CDecD3D11::get_d3d11_buffer() => pDec->m_pAllocator->GetBuffer()

Here are pdb files for the 1.9.5.10 build:
https://www.sendspace.com/file/7llul4

**Comment by Nevcairiel** [comment] 2020-06-21 21:58
Thousands of people use LAV with D3D11/madVR, and I've never heard of this problem nor seen it myself.

Without a clear reproduction case, I can't fix it.

If everything in the graph behaves properly, this should never be possible to hang anyway. On BeginFlush the renderer is supposed to release all frames, allowing the decoder to unblock and finish whatever its working on - and it won't receive any new frames until after EndFlush has already concluded.

The data flow in LAV Video is pretty clear, its likely something else in the graph doing it.

**Comment by clsid2** [comment] 2020-06-21 22:43
Loaded modules only show LAV and madVR 0.92.17. No other filters.

The EndFlush() thread is waiting on lock owned by get_d3d11_buffer() thread. Seems wrong?

There was a similar issue in the past as well, which was fixed in madVR:
http://forum.doom9.net/showthread.php?s=8dd3f6a69eabd3b237b239861fa58a64&p=1817413#post1817413

@eggpa 
Are you also able to trigger the freeze if you reset madVR settings to defaults?

**Comment by Nevcairiel** [comment] 2020-06-21 22:56
get_d3d11_buffer is likely on the receive thread - eg. the thread doing all data processing. Flushing runs on a UI thread when you trigger a seek.

BeginFlush is supposed to tell the renderer to stop what its doing and  release all frames. Once all frames are released, LAV gets them back and GetBuffer can unblock. The receive thread then eventually finishes doing what it does, and sleeps until EndFlush is called and new data arrives.

The only thing this entire process relies on is the renderer properly handling BeginFlush.

**Comment by clsid2** [comment] 2020-06-21 23:18
Thanks for clarifying. So problem might be in madVR.

**Comment by ghost** [comment] 2020-06-22 17:40
I have reset madVR settings and the issue went away.

After some fiddling I think I can reproduce it relatively consistently. Setting CPU queue to 128 and enabling some heavy processing (ex.: very high NGU or RCA) seems to re-enable this issue. Additionally, it reproduces only on some videos (reasons unknown).

Here is a test video and madVR settings which allow me to reproduce this issue: https://www57.zippyshare.com/v/4m4GdrZp/file.html

Another thing to note: without high CPU queue seeking can hang up to 2 seconds, but it's not permanent.

**Comment by Nevcairiel** [comment] 2020-06-22 18:04
Setting the queue that high is really not recommended. DXVA/D3D11 has a limit lower then that and weird things can happen if its that high.

**Comment by clsid2** [comment] 2020-06-22 18:18
When seeking, all those queues need to be flushed. So if seeking is still slow, then your queues might still be too high.

Maybe it is a good idea for @madshi to internally limit queue sizes to sane max values in case of DXVA/D3D11 native decoding.

**Closed as completed by clsid2** 2020-06-22 18:18 UTC

**Comment by ghost** [comment] 2020-06-22 18:34
I can agree with seeking being slow because of queues, but DXVA2 works fine with same queues. Additionally, at 128 it hangs permanently, not temporarily. There is bigger issue than just performance.

**Comment by SigHunter** [comment] 2022-01-22 12:21
> I can agree with seeking being slow because of queues, but DXVA2 works fine with same queues. Additionally, at 128 it hangs permanently, not temporarily. There is bigger issue than just performance.

thanks to your comment, I finally found why d3d11+madvr crashes for me on every seek. I had a CPU queue size of 128, set it to 24 and it works. finally I can switch from dxva2 native to d3d11 native decoding
