### ISSUE TITLE
Subtitles are being skipped randomly

### ISSUE THREAD

**Issue by Zero3K** [clsid2/mpc-hc#755] opened 2020-11-21 21:39 UTC
MPC-HC (Nightly, 64-bit)
------------------------

Build information:
    Version:            1.9.8.26 (df5df0168-dirty)
    Compiler:           MSVC v19.26.28806
    Build date:         Nov  7 2020

LAV Filters:
    LAV Splitter:       0.74.1.87
    LAV Video:          0.74.1.87
    LAV Audio:          0.74.1.87
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    GPU:                NVIDIA GeForce GTX 750 Ti (driver version: 25.21.14.1735)

When I play a video with built in subtitles (such as any new video from [SubsPlease]), the subtitles are being skipped randomly and will only show up when I rewind to a point before the line is spoken (which then shows the subtitle).

**Comment by clsid2** [comment] 2020-11-21 22:37
Give link to a video that you have tested. I want to test with an exact same video as you.

**Comment by Zero3K** [comment] 2020-11-21 23:01
https://nyaa.si/view/1305056

**Comment by Zero3K** [comment] 2020-11-21 23:02
It only happens with the Internal Subtitle Filter.

**Comment by clsid2** [comment] 2020-11-21 23:34
I got the file but I did not notice any skipped subs.

Test if disabling the option "Allow dropping some subpictures if the queue is running late" makes a difference for you.

**Comment by lifegpc** [comment] 2020-11-21 23:54
Sometimes MPC-HC will missing some entries of subtitle (have same timestamp), but after reload subtitles, it works fine.

**Comment by clsid2** [comment] 2020-11-22 00:12
Can you make a screenshot?

**Comment by Zero3K** [comment] 2020-11-22 00:13
How would a screenshot help? Disabling that option doesn't help. The issue was happening when I had "D3D Fullscreen" checked and was watching it in full screen.

**Comment by clsid2** [comment] 2020-11-22 00:26
I need a way to reproduce. A screenshot of a spot where something is missing could help. It has timestamp at which it happens and I can see what is missing. Then I can focus on that spot.

**Comment by Zero3K** [comment] 2020-11-22 00:28
Well, if its not missing for you then how would a screenshot of it missing help? What are your Output settings?

**Comment by Zero3K** [comment] 2020-11-22 00:29
Here are mine:

![Output Settings](https://user-images.githubusercontent.com/6194332/99890672-e317b980-2c2f-11eb-986f-430b212f8890.png)

**Comment by clsid2** [comment] 2020-11-22 00:29
Does it also happen without D3D Fullscreen?

**Comment by Zero3K** [comment] 2020-11-22 00:39
No. I noticed the issue at the 7:19 mark when it was enabled and I was in full screen. I think it is random.

**Comment by Zero3K** [comment] 2020-11-22 00:42
It also happened in the video available at https://nyaa.si/view/1299894.

**Comment by clsid2** [comment] 2020-11-22 13:23
@lifegpc
Can you confirm if it only happens with D3D fullscreen on your computer as well?

**Comment by lifegpc** [comment] 2020-11-22 13:29
It happened in normal window.(with dx9
Such as this.
![image](https://user-images.githubusercontent.com/41434272/99905105-a4eec880-2d09-11eb-9ad8-98cf1fa7cd51.png)

**Comment by lifegpc** [comment] 2020-11-22 13:32
![image](https://user-images.githubusercontent.com/41434272/99905175-39592b00-2d0a-11eb-8e8a-6d745935a479.png)
The output page.
![image](https://user-images.githubusercontent.com/41434272/99905185-52fa7280-2d0a-11eb-9262-5bae58d0ec99.png)

**Comment by clsid2** [comment] 2020-11-22 14:08
I assume this is not a regression and happened in old versions as well?

This is also during normal continuous playback right? Because it is important to know that if a sub if missing directly after seeking, it can be because the embedded subtitle data was stored somewhere before the seek point. A properly muxed Matroska file (made with fairly recent MkvToolNix) contains Cue Point data, that helps the splitter find that subtitle data.
https://matroska.org/technical/cues.html

**Comment by Zero3K** [comment] 2020-11-23 23:52
It doesn't happen in 1.7.13. I tried to replicate it with both D3D Fullscreen on and off but couldn't do so.

**Comment by clsid2** [comment] 2020-11-24 16:16
Then also tests the versions after that.

**Comment by Zero3K** [comment] 2020-11-24 18:33
That's too many versions to test. Maybe its an issue with how its buffering the subtitles.

**Comment by clsid2** [comment] 2020-11-26 13:41
You don't need to test every version. These ones are most interesting: 1.7.14 (new Windows SDK) / 1.8.9 + 1.9.0 (added Dark Theme)

**Comment by BRK0** [comment] 2020-11-30 05:50
It happening to me too , it seems to happen only in fullscreen (some subs randomly don't appear) , internal subtitles , when i just maximize the player and play it ,the subtitles appear while the same moment in fullscreen the subs are missing.
i have attached my Output options ( haven't really changed them from default settings)  ![image](https://user-images.githubusercontent.com/7081791/100573484-eda41400-32fd-11eb-9b6f-1e8b86bbdfe3.png)

**Comment by clsid2** [comment] 2021-02-23 22:04
Might be fixed in 1.9.9.45 development build.

Otherwise test with this setting:
Options > Subtitles > Sub pictures to buffer = 0

**Comment by Zero3K** [comment] 2021-02-25 05:50
This issue is fixed in that version.

**Comment by clsid2** [comment] 2021-02-25 11:50
For anyone who still has the issue on some files:
Lower the "Maximum Texture Resolution" subtitle setting to improve subtitle rendering performance.
Set subpictures buffer to 0 to further reduce chance of subtitle being skipped.

Skipped subs should only occur with Anime videos with complex animated subs, where some subs aren't rendered fast enough. If it happens with a simple SRT subtitle, then there could be another problem.

**Closed as completed by clsid2** 2021-02-25 11:50 UTC
