### ISSUE TITLE
Inductor noise coming from my GFX card when using madVR renderer

### ISSUE THREAD

**Issue by Gorrrg** [clsid2/mpc-hc#658] opened 2020-10-11 16:38 UTC
This is not fixable, so technically not an issue with MPC, rather it's by design of how madVR works.

But I'm curious why when using the madVR renderer my gfx card would make a chirping noise. Any ideas? Is it because of how madVR does VSync or something?

**Comment by Jadelor** [comment] 2020-10-11 17:06
Everything that uses the GPU for a lot of computation should get a GPU with chatty coils going: GPU heavy games, CUDA computation, even the Windows SAT test. I understand it's a byproduct of power demand.

**Comment by Gorrrg** [comment] 2020-10-11 17:54
I can start to hear my gfx card when I let certain games reach ~400fps by reducing the settings, disabling frame limiting and standing in a low polygon area, but I don't think that in particular correlates with GPU load but rather refresh rate.

**Comment by clsid2** [comment] 2020-10-11 19:36
Some of the algorithms in madVR perform a large number of shader passes. So in that aspect the load is actually similar to running a game at high framerate.

The issue is unrelated to MPC-HC, so closing this issue.

**Closed as completed by clsid2** 2020-10-11 19:36 UTC
