### ISSUE TITLE
Display full language

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1106] opened 2021-05-21 07:38 UTC
Sample: https://www.youtube.com/watch?v=5vT7-XhtQWo

Screenshot: ![screen](https://user-images.githubusercontent.com/15793015/119100414-37052e80-ba18-11eb-83cb-784b6d15c40a.png)

This is a minor improvement request.
This video contains both English and English (Canada), is it possible to display "English (Canada)" instead of only English please?

**Comment by clsid2** [comment] 2021-05-21 13:00
There is no support for such extended language codes. I am not interested in adding it either at this moment. The language should be obvious enough already.

**Comment by cw2** [comment] 2021-09-08 07:03
Possible duplicate of #927.

**Closed as completed** 2022-02-16 01:03 UTC
Labels: PatchFromAnotherDeveloperRequired
