### ISSUE TITLE
takes 3-5 seconds to open some videos

### ISSUE THREAD

**Issue by kiravv** [clsid2/mpc-hc#1638] opened 2022-04-01 17:54 UTC
- file size doesn't influence 
- file type doesn't influence (one movie series file opens immediately, second - takes 5 sec)
- repeated reopening doesn't influence

**Comment by clsid2** [comment] 2022-04-01 18:38
Are you using Windows 11 insider build? That has a bug in defender that causes slow video opening.

Otherwise it is caused by bad driver or something else on your system. Not a bug in the player, so I can't help you.

**Comment by kiravv** [comment] 2022-04-02 08:48
No. Not an insider build (

**Comment by VladWinner** [comment] 2022-04-03 07:36
@clsid2 Please pin this links in Readme for Windows 11 Dev/Beta users (maybe at the end of "System Requirements" section):
https://www.ghacks.net/2022/03/28/windows-defender-is-causing-videos-to-open-slowly-in-windows-11-beta-heres-how-to-fix-it/
https://www.reddit.com/r/Windows11/comments/tmndv7/comment/i22tajy/
And also mark this issue with "wontfix" tag.

**Closed as completed** 2022-04-05 13:50 UTC
