### ISSUE TITLE
Adding files brings player in focus/to front

### ISSUE THREAD

**Issue by t3mp3z** [clsid2/mpc-hc#2124] opened 2023-05-17 04:55 UTC
Issue when adding files(drag & drop) to playlist brings player in focus/to front (even when playlist is detached)
It works on a ancient version (1.6.6) but it seems that this have been removed somewhere along the line.

#265 This ticket seems to be relevant but I can't seem to find any similar settings in the latest version.

**Comment by adipose** [comment] 2023-05-20 03:22
https://github.com/clsid2/mpc-hc/pull/281

Found the PR.  Looks like we dropped the advanced option.

I think your scenario was not quite what we were fixing.

**Comment by clsid2** [comment] 2023-05-20 11:08
That other issue was about adding from command-line (Explorer).

Simply clicking on the playlist to give it focus, also brings player to front. There is nothing in the code that does that. They simply belong together. It is a controlbar, not a separate window. So I am inclined to say this is simply how it works.

**Comment by adipose** [comment] 2023-05-21 03:38
> That other issue was about adding from command-line (Explorer).
> 
> Simply clicking on the playlist to give it focus, also brings player to front. There is nothing in the code that does that. They simply belong together. It is a controlbar, not a separate window. So I am inclined to say this is simply how it works.

I agree.  The two windows behave as one, so if one is visible and the other is not, it's just due to other windows covering it.  That means mpc-hc does not have focus, and thus the playlist doesn't, either.  So we should close this as not fixable.

However, a separate window for playlist would solve this, and might be a feature worth considering.  I'm trying to decide what the use cases would be.  This issue for one, but playing audio might be another.

**Comment by t3mp3z** [comment] 2023-05-21 12:21
> > That other issue was about adding from command-line (Explorer).
> > Simply clicking on the playlist to give it focus, also brings player to front. There is nothing in the code that does that. They simply belong together. It is a controlbar, not a separate window. So I am inclined to say this is simply how it works.
> 
> I agree. The two windows behave as one, so if one is visible and the other is not, it's just due to other windows covering it. That means mpc-hc does not have focus, and thus the playlist doesn't, either. So we should close this as not fixable.
> 
> However, a separate window for playlist would solve this, and might be a feature worth considering. I'm trying to decide what the use cases would be. This issue for one, but playing audio might be another.

Ok, I see.
Usecase for this is mostly for audio files and tv series where you need traverse through different folders.
Example, adding the last episode of s01 and then add a couple of s02 epsiodes which (usually) are located in different folders.

I don't see why this shouldn't be possible, because the workaround for this would be to change the "On Top" setting from default?

**Comment by adipose** [comment] 2023-05-21 16:12
> > > That other issue was about adding from command-line (Explorer).
> 
> > > Simply clicking on the playlist to give it focus, also brings player to front. There is nothing in the code that does that. They simply belong together. It is a controlbar, not a separate window. So I am inclined to say this is simply how it works.
> 
> > 
> 
> > I agree. The two windows behave as one, so if one is visible and the other is not, it's just due to other windows covering it. That means mpc-hc does not have focus, and thus the playlist doesn't, either. So we should close this as not fixable.
> 
> > 
> 
> > However, a separate window for playlist would solve this, and might be a feature worth considering. I'm trying to decide what the use cases would be. This issue for one, but playing audio might be another.
> 
> 
> 
> Ok, I see.
> 
> Usecase for this is mostly for audio files and tv series where you need traverse through different folders.
> 
> Example, adding the last episode of s01 and then add a couple of s02 epsiodes which (usually) are located in different folders.
> 
> 
> 
> I don't see why this shouldn't be possible, because the workaround for this would be to change the "On Top" setting from default?
> 
> 

mpc-hc can be in the bg, but how do you interact with a window without focus?

The other issue used a methodology of adding files to the Playlist without interacting with it. That bypasses the need for focus.

**Comment by clsid2** [comment] 2023-05-21 18:20
The solution would be to use the "Add to MPC-HC playlist" entry in the Explorer context menu in this situation. That doesn't give the player focus.

**Closed as not planned by clsid2** 2023-05-21 18:20 UTC

**Comment by t3mp3z** [comment] 2023-05-21 18:58
> > > > That other issue was about adding from command-line (Explorer).
> > 
> > 
> > > > Simply clicking on the playlist to give it focus, also brings player to front. There is nothing in the code that does that. They simply belong together. It is a controlbar, not a separate window. So I am inclined to say this is simply how it works.
> > 
> > 
> > > 
> > 
> > 
> > > I agree. The two windows behave as one, so if one is visible and the other is not, it's just due to other windows covering it. That means mpc-hc does not have focus, and thus the playlist doesn't, either. So we should close this as not fixable.
> > 
> > 
> > > 
> > 
> > 
> > > However, a separate window for playlist would solve this, and might be a feature worth considering. I'm trying to decide what the use cases would be. This issue for one, but playing audio might be another.
> > 
> > 
> > Ok, I see.
> > Usecase for this is mostly for audio files and tv series where you need traverse through different folders.
> > Example, adding the last episode of s01 and then add a couple of s02 epsiodes which (usually) are located in different folders.
> > I don't see why this shouldn't be possible, because the workaround for this would be to change the "On Top" setting from default?
> 
> mpc-hc can be in the bg, but how do you interact with a window without focus?
> 
> The other issue used a methodology of adding files to the Playlist without interacting with it. That bypasses the need for focus.

You don't for the most part.

But if your file explorer covers a part of the player when adding files by dragging&dropping into your playlist, at this time you don't always want mpc to steal focus from file explorer when you still adding files to the list? 
And if you do you simply put mpc as "Always on top"


> The solution would be to use the "Add to MPC-HC playlist" entry in the Explorer context menu in this situation. That doesn't give the player focus.

Ok, thanks it seems to work!

**Comment by adipose** [comment] 2023-05-21 19:10
> 
> You don't for the most part.
> 
> But if your file explorer covers a part of the player when adding files by dragging&dropping into your playlist, at this time you don't always want mpc to steal focus from file explorer when you still adding files to the list? And if you do you simply put mpc as "Always on top"

The point I was making is, once you drop files on the window, that window has to be in the foreground to accept them.  That's just windows ui basics.  You can't click on, drop files, etc. on a window that's not focused without it gaining focus.  So once you've done that, you've "asked" the OS to put that window in the foreground.

This isn't an "always on top" situation, this is a "you are using the window so it has to be on top" situation.

The only approach I can think of is that the window could return focus to explorer after a drag-and-drop, but that's simply counter to how windows works.

Try it for yourself.  Open two explorer windows and drag a file from window 1 to window 2.  The focus will change to window 2.  This isn't stealing focus, it's changing focus based on where the last action occurred.  If an action you take moves focus to a window you don't want to interact with, that's up to you as the user to click back on the window you do want to work with.

**Comment by t3mp3z** [comment] 2023-05-21 21:15
> > You don't for the most part.
> > But if your file explorer covers a part of the player when adding files by dragging&dropping into your playlist, at this time you don't always want mpc to steal focus from file explorer when you still adding files to the list? And if you do you simply put mpc as "Always on top"
> 
> The point I was making is, once you drop files on the window, that window has to be in the foreground to accept them. That's just windows ui basics. You can't click on, drop files, etc. on a window that's not focused without it gaining focus. So once you've done that, you've "asked" the OS to put that window in the foreground.
> 
> This isn't an "always on top" situation, this is a "you are using the window so it has to be on top" situation.
> 
> The only approach I can think of is that the window could return focus to explorer after a drag-and-drop, but that's simply counter to how windows works.
> 
> Try it for yourself. Open two explorer windows and drag a file from window 1 to window 2. The focus will change to window 2. This isn't stealing focus, it's changing focus based on where the last action occurred. If an action you take moves focus to a window you don't want to interact with, that's up to you as the user to click back on the window you do want to work with.

No that's not correct. Because then it wouldn't have worked in a previous version and in other software?
In most cases that would be the correct behavior yes, but not in this case.

I have indeed tried this and been using it since forever. There are serveral different applications that this works to some degree and to name them from the top of my head: Sublime Text, Notepad++, Terminal(new cmd) and several media players (including an older version of mpc-hc)
Dragging a file(media  players) or a text (text editors) into the background app doesn't make it steal focus (unless first file for some playlists).

Windows Explorer is not the best example because its not the same use case. Try using another media player, Microsofts own windows media player for example.
Dragging files from file explorer into the player list does not put wmp on top of your file explorer?

**Comment by adipose** [comment] 2023-05-21 23:13
> > > You don't for the most part.
> > > But if your file explorer covers a part of the player when adding files by dragging&dropping into your playlist, at this time you don't always want mpc to steal focus from file explorer when you still adding files to the list? And if you do you simply put mpc as "Always on top"
> > 
> > 
> > The point I was making is, once you drop files on the window, that window has to be in the foreground to accept them. That's just windows ui basics. You can't click on, drop files, etc. on a window that's not focused without it gaining focus. So once you've done that, you've "asked" the OS to put that window in the foreground.
> > This isn't an "always on top" situation, this is a "you are using the window so it has to be on top" situation.
> > The only approach I can think of is that the window could return focus to explorer after a drag-and-drop, but that's simply counter to how windows works.
> > Try it for yourself. Open two explorer windows and drag a file from window 1 to window 2. The focus will change to window 2. This isn't stealing focus, it's changing focus based on where the last action occurred. If an action you take moves focus to a window you don't want to interact with, that's up to you as the user to click back on the window you do want to work with.
> 
> No that's not correct. Because then it wouldn't have worked in a previous version and in other software? In most cases that would be the correct behavior yes, but not in this case.
> 
> I have indeed tried this and been using it since forever. There are serveral different applications that this works to some degree and to name them from the top of my head: Sublime Text, Notepad++, Terminal(new cmd) and several media players (including an older version of mpc-hc) Dragging a file(media players) or a text (text editors) into the background app doesn't make it steal focus (unless first file for some playlists).
> 
> Windows Explorer is not the best example because its not the same use case. Try using another media player, Microsofts own windows media player for example. Dragging files from file explorer into the player list does not put wmp on top of your file explorer?

Well, you're right.  Do you know when the behavior changed in mpc-hc?

**Comment by adipose** [comment] 2023-05-21 23:18
![image](https://github.com/clsid2/mpc-hc/assets/3324395/6054d668-c20e-4896-aabe-c1c2cf9d2fa2)

It's caused by `SetForegroundWindow()` here.  Not sure if we really need that or not.

Separately, if you drop on the video window, it will take focus, too:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/d1ee2d43-50f4-40f9-9b8e-669d2bf83fd7)

Either or both of these could theoretically be configurable, and Windows Media Player doesn't take focus in either case, in my testing.

**Comment by t3mp3z** [comment] 2023-05-22 15:25
> Well, you're right. Do you know when the behavior changed in mpc-hc?

I believe somewhere around 1.6.7 (not sure) I can do some own testing and get back to you!
And thank you for taking time to investigate this issue!
 
> It's caused by `SetForegroundWindow()` here. Not sure if we really need that or not.
> 
> Separately, if you drop on the video window, it will take focus, too:
> 
> Either or both of these could theoretically be configurable, and Windows Media Player doesn't take focus in either case, in my testing.

if you drop a file directly on the video window and it take focus, I can understand this behavior and it make sense (play this file instead).
But if dropping into the playlist the files should just add to the list and not put in focus.

if this could be a config setting, that would be awesome!

**Comment by t3mp3z** [comment] 2023-05-22 15:36
> > Well, you're right. Do you know when the behavior changed in mpc-hc?
> 
> I believe somewhere around 1.6.7 (not sure) I can do some own testing and get back to you! And thank you for taking time to investigate this issue!

Found it: 
>"1.6.7 - 25 April 2013"
> +Ticket #2987, Playlist improvements:
>   -Put MPC-HC on top and give the focus to the playlist after a drag and drop
