### ISSUE TITLE
Subtitles are misplaced in screenshots

### ISSUE THREAD

**Issue by Cheeerd** [clsid2/mpc-hc#1816] opened 2022-08-18 17:39 UTC
https://nyaa.si/view/831686
In files from here when you use japanese pgs subtitles, if you took a screenshot, then the subtitles on the screenshot are shifted to the right.
Perhaps this has something to do with the fact that in the opening, subtitles are shown outside the frame on the right, when viewed with a screen width greater than the width of the frame.

Example:
Screenshot of screen:
![scr](https://user-images.githubusercontent.com/21987340/185458488-057c95c8-a674-45b0-b0ea-e4e0a6016c01.png)
Screenshot by player:
![Sephirotic  Evangelion - 01  MULTI BD 1080p 8bits 5 1 AAC 6B1607E9 mkv_snapshot_01 50 148](https://user-images.githubusercontent.com/21987340/185458547-8beb88a7-2c95-4c91-9990-d7778ad16282.jpg)
Opening:
![scr op](https://user-images.githubusercontent.com/21987340/185459207-64d70b7b-f605-4436-8450-4cc477780d95.png)

**Comment by clsid2** [comment] 2022-08-18 17:50
Duplicate of #968

**Closed as completed by clsid2** 2022-08-18 17:50 UTC
