### ISSUE TITLE
[1.9.10] ISR randomly dropping subtitle lines

### ISSUE THREAD

**Issue by AkazaAkarinn** [clsid2/mpc-hc#985] opened 2021-03-09 23:28 UTC
I upgraded from 1.9.7 to 1.9.10 today and started experiencing issues with subtitles dropping from several different videos. They seemed to be happening in the same locations of the video, but happen randomly. If you let the video play it will eventually drop lines, but if you seek back the missing lines will show up. The best example I have is https://nyaa.si/view/1354699 at the 01:45 mark, but only if you let the video play from the beginning. It also happens on the [Erai-raws] version of this episode. To make sure it wasn't an issue with that episode I tried it in VLC and version 1.9.7 and had no issues. I also went back to older episodes and had this happening in https://nyaa.si/view/1351119 and an episode from another series https://nyaa.si/view/1353676. Like I said before, you have to let the video playout for the dropped lines to occur. If you try to seek to where the problem areas are the issue doesn't happen.
This is what my subtitle settings look like. These are what I had for 1.9.7 and restored them after updating
![MPC Subtitles](https://user-images.githubusercontent.com/73498740/110552233-f2e6db00-8104-11eb-912e-013fb1ee84cd.png)

**Comment by clsid2** [comment] 2021-03-09 23:50
Can you test these versions?
https://github.com/clsid2/mpc-hc/releases/download/1.9.7.34/MPC-HC.1.9.7.66.x64.exe
https://github.com/clsid2/mpc-hc/releases/download/1.9.7.34/MPC-HC.1.9.7.74.x64.exe
Problem might have started between these two.
If not, also test these two:
https://github.com/clsid2/mpc-hc/releases/download/1.9.8.26/MPC-HC.1.9.8.33.x64.exe
https://github.com/clsid2/mpc-hc/releases/download/1.9.8.26/MPC-HC.1.9.8.42.x64.exe

**Comment by AkazaAkarinn** [comment] 2021-03-10 00:25
Tested all of them and had no issues. I also went ahead tested 1.9.9 and had no issue either.

**Comment by GoldenSW** [comment] 2021-03-10 09:59
I was about to start a topic here about the same issue when I saw this. 
For me, it is also happening in anime. When multiple text lines are supposed to render at the same time on different parts of the screen (ex. dialogue and background signs or two persons talking at the same time with one line being at the bottom and one at the top) at least one of them is not being displayed.
Other possibly helpful info:
When I override the style `Subtitle Track -> Default Style` every line is displayed, but of course not as intended.
Every necessary font is attached in the mkv.
I'm on 1.9.10 and madvr 92.17, RTX 2080, driver 461.72, Windows 10 20H2.

**Comment by clsid2** [comment] 2021-03-10 12:41
Test with 1.9.9 and if that one still works ok, then both please test these versions between 1.9.9 and 1.9.10:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.9.1

**Comment by GoldenSW** [comment] 2021-03-10 13:14
What apparently fixed it for me was setting `Sub pictures to buffer` to 0. If you still need help testing this further, I'll try those versions later.

**Comment by clsid2** [comment] 2021-03-10 13:43
That is the new default value. But if previous versions worked correctly for you with buffer 10, then there is still a regression. So please test those development versions with buffer 10.
With buffer enabled it can happen that a sub is skipped if it is not rendered fast enough. I actually made a change that should make this occur less often. But if in your cases it happens more, there could be a new issue.

**Comment by GoldenSW** [comment] 2021-03-10 17:52
@clsid2 After testing a number of times with the buffer set to 10, I can safely say the problem appeared in 1.9.9.45. Hope this helps!

**Comment by clsid2** [comment] 2021-03-10 19:13
Try this one:
https://github.com/clsid2/mpc-hc/releases/download/1.9.10.16/MPC-HC.1.9.10.19.x64.exe

**Comment by GoldenSW** [comment] 2021-03-10 19:35
Tried it, same issue.

**Comment by AkazaAkarinn** [comment] 2021-03-10 20:36
Can confirm the issue first appears with 1.9.9.45. Tested 1.9.10.19 and the problem is still present.

**Comment by Smagjus** [comment] 2021-03-12 21:58
I didn't do too much testing yet but it seems to happen mostly when mutliple different dialogues possibly with different timings are on the screen at the same time. Then only a single one is displayed. Seeking indeed helps to bring them back.

**Comment by clsid2** [comment] 2021-03-12 23:08
I can reproduce with https://nyaa.si/view/1354699 at 01:45.
Subtitle line on top is shown, subtitle line on bottom is skipped ("I'm back!").

I will have a look at it again later.

**Comment by clsid2** [comment] 2021-03-12 23:34
Should be fixed in 1.9.10.26

**Comment by fesh0r** [comment] 2021-03-13 00:16
Can confirm this build fixes the issue for me with the examples given and a couple of others where the same issue occured

**Closed as completed** 2021-03-13 01:00 UTC
