### ISSUE TITLE
Options screen messed up on Windows 11 for RTL language

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#1454] opened 2021-12-18 02:26 UTC
![mpc_settings_win11_hebrew](https://user-images.githubusercontent.com/4704996/146625746-e00b4931-152b-4641-9916-9c98de9b45f7.png)

@adipose
Options screen is transparant, except for small portion in top left, which is rendered correctly. Maybe a drawing bug?

Only happens on Windows 11. No issue on Windows 10 21H2 and below.
Hebrew language selected in the screenshot.
Dark/classic theme does not matter.
DPI at 100%. So probably not related to scaling.
Tested in VirtualBox.

Edit:
It also does not capture clicks on the area that is transparent. Clicks are captured by the window or desktop behind. This applies even to the titlebar of the options window. Only the left part of it is working.

**Comment by clsid2** [comment] 2021-12-18 02:45
Found workaround:
Right-click on .exe > Compatibility > Change High DPI Settings > Override high DPI scaling behavior

Strange since I used standard DPI.

**Comment by AI-IMED** [comment] 2021-12-19 09:17
@clsid2
I tried this method

> Right-click on .exe > Compatibility > Change High DPI Settings > Override high DPI scaling behavior

 and it will not work to solve the problem, I'm using the Arabic language.

**Comment by adipose** [comment] 2022-01-09 02:59
I haven't got around to testing this on Windows 11, yet. My primary machine is still on 10.

**Comment by adipose** [comment] 2022-01-24 03:28
I have reproduced it, now.  Screen is transparent and clicks pass right through.  It may be a sizing issue...

**Comment by adipose** [comment] 2022-01-24 03:30
![image](https://user-images.githubusercontent.com/3324395/150717471-c44facfd-3254-4fe0-ae43-c70ee2b89973.png)

Note that the options screen is the exact "width" as the player window.  Somehow, it doesn't seem to know its own active size.

**Comment by adipose** [comment] 2022-02-09 21:10
I tested some old builds, and it was working until the PerMonitorV2 patch:

https://github.com/clsid2/mpc-hc/commit/0f87b644a41deb480b312d341dc05ad4b1bc7d41

This is a pretty big patch, but it might simply be based on PerMonitorV2 having a bug on Windows 11.  Not sure yet.

**Comment by adipose** [comment] 2022-02-09 22:52
Disabling PerMonitorV2 fixed the problem.  Was not a problem on Windows 10.  Maybe to do with transparency.

**Comment by clsid2** [comment] 2022-02-09 23:20
Disabling this line in translations.cpp make it display the full options window.
```SetWindowsHookEx(WH_CBT, RTLWindowsLayoutCbtFilterHook, nullptr, GetCurrentThreadId());```
However, it is then rendered left-to-right on Win11.

**Comment by adipose** [comment] 2022-02-10 01:04
Right, I discovered the same thing.  But it feels like a Windows bug, because all that does is render things in reverse, and all the other logic is supposed to be the same for sanity's sake.

So far I have confirmed that the width which appeared to be related to the main window width doesn't seem to change even if I change the menu to force a different size...so maybe it was entirely a coincidence, but I'm not sure.

**Comment by adipose** [comment] 2022-02-11 00:54
RTL dialogs (and propertypage) are fine, if it is set in advance.  It breaks when it is changed dynamically.  I also checked in presubclasswindow, and it fails there as well.

**Comment by adipose** [comment] 2022-02-11 00:59
And it happens even if you don't set RTL.  So it must be a bug with SetWindowLongPtr.

**Comment by adipose** [comment] 2022-02-12 00:50
When I tried to reproduce this issue with a minimal case, I couldn't.  So perhaps there is something in mpc-hc that's causing the issue.

**Comment by adipose** [comment] 2022-02-14 21:52
Oops, I can reproduce it easily.  Just forgot PermonitorV2.  Guess I will submit to microsoft....see you in 5 years.

**Comment by clsid2** [comment] 2022-02-14 23:12
Damn, I was afraid it would be a MS bug. Luckily it doesn't happen in Win 10 21H2.

**Comment by adipose** [comment] 2022-02-14 23:49
https://techcommunity.microsoft.com/t5/report-an-issue/propertysheet-bug-with-setwindowlongptrw-gwl-exstyle-and/m-p/3165663#M8176

Reported here.

**Comment by clsid2** [comment] 2022-02-14 23:55
Nice work.

**Comment by adipose** [comment] 2022-02-17 17:35
I found a workaround by using propsheet callbacks.  

https://github.com/clsid2/mpc-hc/pull/1558

**Closed as completed** 2022-02-17 22:38 UTC
