### ISSUE TITLE
Problem opening .rar files

### ISSUE THREAD

**Issue by Titanos** [clsid2/mpc-hc#225] opened 2020-01-11 23:02 UTC
After downloading the latest version (1.9.0) i can't seem to open .rar files, or rather some open with a thumbnail of the movie and jerky sound in the background, and others do not start at all.

I tried resetting all the settings and also tried with different renderers but the results were the same. Reverted back to a older version (1.7.x) and the issue was gone. Is there any way to solve this?

**Comment by adipose** [comment] 2020-01-11 23:18
Can you upload the RAR file? I updated the source to support all RAR formats, and tested with several different RARed videos.  But maybe something is broken in your scenario.

What video renderer are you using?

**Comment by Titanos** [comment] 2020-01-12 02:48
This is odd indeed, i have tried both the x64 and x86 versions, standalone and installer and get the same exact results. And it's the same with all movies that are packed in multiple rars. I open the first rar-file as usual, but get a thumbnail and audio in the background. I have tried with both madVR and EVR (CP) as a renderer. This is on a newly installed windows with brand new hardware. Alltho i had the same issue on my previous computer also. I guess i could upload one of the .rar files, but i get the same issue with all of them, and i tried a whole bunch that used to open without issues before.

**Comment by adipose** [comment] 2020-01-12 03:13
Can you please upload your config? If it happens with all rars it must be something that you have setup differently than me.

**Comment by Titanos** [comment] 2020-01-12 03:36
Absolutely, is it the "export settings" file you need? In that case i uploaded it here --> https://gofile.io/?c=lgiaEC

**Comment by adipose** [comment] 2020-01-12 05:24
@Titanos 

I could not reproduce your issue.  Can you tell me your results with the following suite of tests:

https://mega.nz/#!YJQDhQxC!mNgyJKPEfclwhjahuj0voFtAF00i-yaOJvPpoZwGzEk

I also tested on a 5GB file split into a few hundred rars with no problem, but for now try these.

**Comment by Titanos** [comment] 2020-01-12 05:33
I get a warning that the data stream could not be rendered. Also pasting the results below:

RAR File Source::Output

Media Type 0:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0


Media Type 1:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0

**Comment by Titanos** [comment] 2020-01-12 05:40
They all opened with the same sequence of a weel turning. Is that how it was intended?

**Comment by Titanos** [comment] 2020-01-12 05:44
Also i should mention that i open the files by right clicking and choosing to open with MPC-HC. That is when the issue happens. If i instead open up MPC-HC and open a file via quick-open, then it starts as intended.

**Comment by adipose** [comment] 2020-01-12 05:58
@Titanos 

Yes, the video is always the same.

Do I understand your last comment correctly?  Are your RARs working ok when using quick open, or just those that I sent?

The error you got above likely is you tried to play the RAR directly, instead of extracting it (inside are several more RARs).

**Comment by Titanos** [comment] 2020-01-12 06:44
I didn't get that the files were inside the rar at first! Yes all the RARs i have tried so far have opened up correctly via quick open but not if i right click an choose "open with".  The ones you sent me opened up correctly, both ways tho. I downloaded a couple of movies just now to confirm, and the issue was still there.

**Comment by adipose** [comment] 2020-01-12 06:58
Well, maybe it is a big request, but maybe you can send me the smallest video that's giving you an issue?

**Comment by adipose** [comment] 2020-01-12 08:06
Right-click open is working fine for me, as well, even on large videos.  Strange...

**Comment by Titanos** [comment] 2020-01-12 08:57
Dear god..  just figured out what caused the issue. For some reason, windows seems to sort the files differently?! the .rar file ends upp somwhere at the bottom and the first file .r00 is the one i've been trying to open up. with the correct sorting i now get the right order and can open the files again. I'm so sorry for wasting your time, thank you so much for the effort!

**Comment by Titanos** [comment] 2020-01-12 09:30
Alltho it's worth pointing out that the earlier versions 1.7.x can start the media by opening any of the archives. I just tested it and it seems to work with all of the .rxx files. The 1.9.0 version seems to only work with the .rar file.

**Comment by adipose** [comment] 2020-01-12 18:27
This makes me laugh. The .rxx naming convention has been deprecated for over a decade, in favor of .part1.rar, .part2.rar, etc. (which sorts correctly).  R00 comes alphabetically before RAR, in ascii sort (0 is ascii 0x30 and A is 0x41).  Check out this comment from the unrar source:

![image](https://user-images.githubusercontent.com/3324395/72223618-be3dba80-3525-11ea-9368-6ce5a36793bd.png)

Eugene has trouble understanding why the ripping community continues to rename the rar files to the old extensions, even when using the new formats...!  Me too!

**Comment by Titanos** [comment] 2020-01-12 23:13
Ok that explains why it was sorted last instead of first ^^ Indeed a weird choice if there is a better alternative!

One question tho, doesn't the RARFileSource filter allow for opening media via any of the rar files and not just the .rar one?

**Comment by adipose** [comment] 2020-01-13 04:27
> Ok that explains why it was sorted last instead of first ^^ Indeed a weird choice if there is a better alternative!

It's not an alternative, it's what RAR does when creating archives.  The only way to get the old names is to use a VERY old (I think at least 15 years actually) version of RAR, or else rename afterwards.

> One question tho, doesn't the RARFileSource filter allow for opening media via any of the rar files and not just the .rar one?

I tested on older versions of mpc-hc, and no, it doesn't work when opening .r00.  Probably because it doesn't realize it's a rar.  The newer format could be made to rewind to the first file.  The old "RARFileSource," which was custom built and did not use the unrar library, did have code to find the first archive, but it's no longer there in the version I built.

I'll take a look at it.

**Comment by adipose** [comment] 2020-01-13 05:22
@Titanos 

Here's a test build which supports rewinding to the first archive in the set.  Note that for the normal naming convention (xxx.part01.rar, xxx.part02.rar), this just works, since they all have the ".rar" extension.  But for the old convention, where every extension was different (which is why it's BAD in the windows world with file associations--but smart in DOS when it was created and filenames were 8 chars max), MPC-HC simply doesn't know that the other extensions are RARs at all.  But I added .r00 to the list since it is alphabetically first.

https://mega.nz/#!ZAoQyIwJ!8WTWc0uX7Vk3AkVr7HeIAHQBCc_9pAnt7DRLy_0nfhU

**Comment by Titanos** [comment] 2020-01-13 09:08
> It's not an alternative, it's what RAR does when creating archives. The only way to get the old names is to use a VERY old (I think at least 15 years actually) version of RAR, or else rename afterwards.

Ok, i see now, so some of the rippers/uploaders use really old versions of RAR or for some reason rename the archives? Seems a bit backwards lol.

> I tested on older versions of mpc-hc, and no, it doesn't work when opening .r00. Probably because it doesn't realize it's a rar. 

I tested with version 1.7.13 and it seems to open the media from any of the archives i tested. 

> Here's a test build which supports rewinding to the first archive in the set. Note that for the normal naming convention (xxx.part01.rar, xxx.part02.rar), this just works, since they all have the ".rar" extension. But for the old convention, where every extension was different (which is why it's BAD in the windows world with file associations--but smart in DOS when it was created and filenames were 8 chars max), MPC-HC simply doesn't know that the other extensions are RARs at all. But I added .r00 to the list since it is alphabetically first.
> 
> https://mega.nz/#!ZAoQyIwJ!8WTWc0uX7Vk3AkVr7HeIAHQBCc_9pAnt7DRLy_0nfhU

Great! This one works the way im used to :) But if a update comes out, i guess the ability would be overwritten if i were to update?

**Comment by clsid2** [comment] 2020-01-13 16:34
The fix will be included in next release.

**Closed as completed by clsid2** 2020-01-13 16:34 UTC

**Comment by adipose** [comment] 2020-01-13 21:12
Here's a test build with some improvements (I think there was a bug with .rar that was renamed, as well).

https://mega.nz/#!xQAykYLY!ZkSpjDTo9ArjlrrSPBAup-AynXTLKibsMfrWA2eIBWc

If 1.7.13 worked with .rNN files, I am a bit surprised.  But I didn't go back that far.  I tested 1.8.6, which is from before I created the new library.  So if it stopped working before then, perhaps someone removed code for .rNN.  I think .rar and .r00 is probably enough, considering NO modern RAR files should be named the old way... ;)

**Comment by adipose** [comment] 2020-01-13 21:22
OK, scratch that.  It was using the RAR4 signature to recognize .rNN.  I've updated it to recognize the RAR5 signature as well.  So now the file can be named whatever you want and it should work.  However it still will need the first volume to be named ".rar" or "part01.rar" to successfully find it.

I'm not going to bother with a test build for that.  It seems to work fine.

**Comment by Titanos** [comment] 2020-01-14 23:56
> OK, scratch that. It was using the RAR4 signature to recognize .rNN. I've updated it to recognize the RAR5 signature as well. So now the file can be named whatever you want and it should work. However it still will need the first volume to be named ".rar" or "part01.rar" to successfully find it.
> 
> I'm not going to bother with a test build for that. It seems to work fine.

Good to hear! Appreciate the effort :) Will this be coming out in the next update?

**Comment by adipose** [comment] 2020-01-15 00:01
> > OK, scratch that. It was using the RAR4 signature to recognize .rNN. I've updated it to recognize the RAR5 signature as well. So now the file can be named whatever you want and it should work. However it still will need the first volume to be named ".rar" or "part01.rar" to successfully find it.
> > I'm not going to bother with a test build for that. It seems to work fine.
> 
> Good to hear! Appreciate the effort :) Will this be coming out in the next update?

Yes, it was already merged to develop.
