### ISSUE TITLE
Exiting Before Video Load Completes Leads to Unclosed Process

### ISSUE THREAD

**Issue by CryptokidFH** [clsid2/mpc-hc#2761] opened 2024-04-30 17:21 UTC
When closing MPC quickly enough, if a file is in the process of being loaded, MPC will not correctly quit, and must be closed via task manager.

This can be reproduced by either:
- Having MPC as the default player, double clicking a video file in explorer to open it
- After the main player opens and the window is still black / the video hasn't started playing, close the player
- The window will be gone but the process still visible in task manager

Or

- Open MPC directly instead of with a file
- Open a video file (or, if a video is still recognized in a playlist from the previous session, hitting play to load that one)
- Again closing the player while it's still black / the video hasn't finished loading results in an improperly quit process

An easy way to tell if this has happened is by checking the tray to see if you have any filters stuck open there. If I'm using MadVR for example, I can see it's present in the tray after this occurs. If its happened more than once I'll have multiple copies of MadVR there. The issue however is not constrained to just that filter and I've reproduced this with just the default one too.

**Comment by clsid2** [comment] 2024-04-30 17:42
I can't fix this problem because I can not consistently trigger it with debugger.

Do not store settings in INI when using MadVR. That significantly increases chances of delay/hang when opening.

**Comment by adipose** [comment] 2024-05-09 22:50
I wasn't able to reproduce this at all.  In the event that it does close mid-load, it is caught by this code:

`if (WaitForSingleObject(m_evOpenPrivateFinished, 5000) == WAIT_TIMEOUT) { // TODO: it's really dangerous, decide if we should do it at all`

It then terminates the graph thread.  MADVR disappears from the tray.

How did you get it to crash?

**Comment by clsid2** [comment] 2024-05-10 22:35
Try 2.2.1.25 development build. That will terminate the process when the graph thread does not respond when aborting during graph construction.

But if Madvr is already in graph, then graph building might already be complete, and hang is in other part of the code. Has the window already been resized to video proportions when closing is initiated?

**Closed as not planned** 2024-05-13 20:44 UTC
