### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by Spuner** [clsid2/mpc-hc#47] opened 2018-11-27 14:09 UTC
The playlist does not show the file name. And if you open several files, the names are shown only starting from the second file ...

Player Version: 1.8.3
OS: Windows 7 Pro SP1 x64 (DPI 125%)

![6c958be201067fa55cc11a7965f3fc7f](https://user-images.githubusercontent.com/30773815/49150808-71018800-f327-11e8-9209-0c73cb005524.png)

**Comment by clsid2** [comment] 2018-11-27 17:43
It is displayed correctly here.

Options > Miscellaneous > Reset

**Comment by Spuner** [comment] 2018-11-27 18:08
Sorry but that didn't help.

**Comment by Spuner** [comment] 2018-12-02 14:48
No more ideas?

**Comment by clsid2** [comment] 2018-12-03 15:12
Nothing that you can do yourself. It might be a DPI related bug. This is not high priority for me right now, so you need to hope someone else can contribute a fix.

**Comment by Spuner** [comment] 2018-12-04 12:54
You already release updates for a very long time... Is this error so complicated to fix it?

**Comment by Hrxn** [comment] 2018-12-04 21:08
Yes, it's "difficult" to fix if this issue is actually caused by the underlying libraries of the operating system used to display the UI.

Did you at least try to change you DPI/scaling settings to see if that is the cause?

**Comment by Spuner** [comment] 2018-12-04 22:15
> Did you at least try to change you DPI/scaling settings to see if that is the cause?

Changed, even on other computers looked - everywhere, the problem is present.

**Comment by Spuner** [comment] 2018-12-04 22:54
> Well, then the issue is probably neither MPC-HC nor the DPI settings.
Because the playlist is displaying correctly for me and @clsid2 ..

Well, I understand you - if the developer is doing well, then the problem does not exist. Great logic ;)

**Comment by clsid2** [comment] 2018-12-05 14:19
Are you using a Chinese/Korean/Japanese version of Windows? Those have a weird GUI rendering bug that can may be the cause of this.

**Comment by Spuner** [comment] 2018-12-05 14:20
> Are you using a Chinese/Korean/Japanese version of Windows?
No, English version.

**Comment by BobPNyaa** [comment] 2019-03-26 04:07
I have seen this bug also and can reproduce it. Did some testing and it only occurs when files are already on the list and MPC-HC is closed and reopened. Starts showing the second file from the current file in the list in black but the current file can be seen in red if the scroll bar is backed up. So it is a case of the list being scrolled one file too many on reopening. Occurs both docked and undocked.

**Comment by Pentaphon** [comment] 2019-06-14 12:06
Thanks, @BobPNyaa

**Comment by adipose** [comment] 2019-11-12 15:08
@Spuner 

I cannot reproduce this bug @ 125% on Windows 7 using latest builds. Can you try this and report back:

https://www.sendspace.com/file/3wsrqn

Also a video of the behavior cropping up on a fresh install would be good, if it's still happening.

**Comment by adipose** [comment] 2019-11-12 19:56
@Spuner, @BobPNyaa, @clsid2 
Don't bother testing it, as I could not duplicate on 1.8.3, either.

Here is what I could reproduce. If the playlist is long enough, when opening a new instance, the current item in the playlist is not always visible, like this:

![image](https://user-images.githubusercontent.com/3324395/68704703-94761080-0541-11ea-8136-eca2e6e1ecaf.png)

It seems to always scroll one line more than it should to put that item at the top.

I have a fix for this issue, and I wouldn't be surprised if it fixes your issue, as well.  Your issue seems to be a case of over-scrolling where no scrolling is required at all.  But without more help, I probably can't reproduce that issue. Hopefully this fix is all that's required.

It now looks like this:

![image](https://user-images.githubusercontent.com/3324395/68705621-3cd8a480-0543-11ea-9d37-2a05107eb35d.png)

Or shamelessly plugging the dark theme:

![image](https://user-images.githubusercontent.com/3324395/68705687-5da0fa00-0543-11ea-8823-b11c8742807e.png)

Here's a PR for this issue: https://github.com/clsid2/mpc-hc/pull/160

**Comment by adipose** [comment] 2019-11-13 22:33
@clsid2 

Haven't heard back from Spuner, but if you want to provide a test build he could test it out when he sees the message.

**Comment by Spuner** [comment] 2019-11-13 23:54
I recorded a video. Look -> https://radikal.ru/video/TX0qkUiJOGf

**Comment by adipose** [comment] 2019-11-14 05:13
Great video. Can you please confirm:

1. OS version/build (nvmd, I see 7601 in the about box)
2. Any custom themes
3. Any other customizations/tweaks for windows

The reason I ask is I am doing exactly the same as you on Win7SP1x64 without the same results. But I notice you have square corners on your windows, which is atypical for Win7.  If you could export your settings for mpc I can also try that.

**Comment by adipose** [comment] 2019-11-14 05:43
While you are at it, try this build:

https://mega.nz/#!BM4AiShK!LpkU6LBJzKUQxUnwGRMjftZrIegH0r68dJ0r5j4Ubfk

If it fixes the issue we can rest easy.  But after seeing your video I don't know if my fix is likely to help or not, since it deals with already existing playlists, while you are creating brand new playlists by dragging and dropping.

**Comment by adipose** [comment] 2019-11-14 06:01
And if you could export this registry key:

![image](https://user-images.githubusercontent.com/3324395/68830681-245eac00-0661-11ea-91f6-0ed6d88977c0.png)

**Comment by adipose** [comment] 2019-11-15 01:24
@Spuner In case you didn't see the last 3 message, tagging your name here.

**Comment by adipose** [comment] 2019-11-15 07:36
@Spuner I was able to repro a similar issue by tweaking the default icon height in windows:

![image](https://user-images.githubusercontent.com/3324395/68925221-69eda880-0737-11ea-9a72-11dd23e801e2.png)

It's generally not wise to change these as most UI of windows doesn't respond nicely.  But if I can fix this issue, maybe it will fix yours.

**Comment by adipose** [comment] 2019-11-15 09:14
@clsid2; @Spuner 

Ok, I really got something this time.  See https://github.com/clsid2/mpc-hc/pull/162

Test build here:

https://mega.nz/#!dIYTVIzY!YTUcDC1FYON-ATE0rnWZX3Kf9sZhG2lKyeYsEOblbo0

**Comment by Spuner** [comment] 2019-11-17 00:09
**adipose**, yes, now everything is fine.

**Comment by adipose** [comment] 2019-11-17 00:29
@clsid2 great, let's close this one

**Comment by Spuner** [comment] 2019-11-17 00:31
**adipose**, will this bug be fixed in future versions of MPC-HC?

**Comment by adipose** [comment] 2019-11-17 00:38
Yes, fix was already merged into the development code.

**Comment by Spuner** [comment] 2019-11-17 00:42
**adipose**, thanks. I will wait )

**P.S.** then, I close the topic.

**Closed** 2019-11-17 00:43 UTC
