### ISSUE TITLE
Media properties window anchoring and flashing issues

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2819] opened 2024-05-31 23:36 UTC
There is 3 main issues about Media Properties window

- Unanchored objects

- Flashing Tab Titles while window is moving

- Moving a part of window to offscreen cause visual glitch that static text box borders appearing.

1. Anchoring object needed for consistency (not sure correct terminology about Positions at anchoring but devs better understand situations)

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/d8b3932b-e0c6-4cf6-99aa-9f56a5cda1fd)
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/99523613-0da9-4931-95fe-73f6a41ce2b0)
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/148c0011-9e03-427d-b226-bcc5c69e3e2f)

2. Flashing tab titles

![mpc-hc64_7vjDN0gPBy](https://github.com/clsid2/mpc-hc/assets/3073922/16f8157b-c4b1-475d-acc2-d6532c982c9f)

3. When part of window being on offscreen, it causes glitches (move the window to offscreen i.e right corner)
It may be Mpc-hc global issue, also effect Subtitle downloader and Main Window.

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/af077c8a-5297-4e3e-ba5d-c7f247f86ee1)
Moving window right bottom offscreen cause additional separator. But when sound icon show up it disappears.

![resim](https://github.com/clsid2/mpc-hc/assets/3073922/af586d4b-4828-4f0f-8cf4-d92298a2d6a8)

Subtitle downloader status bar has issue when part of window being at offscreen. That causes the progress bar and other elements to disappear in the status bar.

**Comment by adipose** [comment] 2024-06-04 00:02
https://github.com/clsid2/mpc-hc/pull/2823

1. Resources tab supported
2. Flicker fixed

Not following everything else, but see how this is.

**Comment by adipose** [comment] 2024-06-04 00:20
The off-screen thing is confirmed.  Not sure what causes that but it appears to be related to theming, as it doesn't occur with native widgets.

The flicker continues on unthemed widgets.  The problem seems to be restricted to the resizable dialogs, and is probably a bug in the erasebackground code.  I fixed it by double-buffering, but in the native draw I need a better solution.

**Comment by xLn2** [comment] 2024-06-04 00:33
Some pictures don't representing case so here is another one, probably these changes will break some strings translations. 
Resized by left corner and top corner to left and top.
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/11aa54c9-b2da-48bd-a238-df1013accacb)

**Comment by adipose** [comment] 2024-06-04 00:39
Wow.  I did not even know it could be resized from the other corners.  I don't think it was meant to be possible based on where they draw the resize grabber.  Maybe a Windows change...

**Comment by adipose** [comment] 2024-06-04 01:02
OK that should be handled now.

**Comment by xLn2** [comment] 2024-06-04 02:20
I'm not sure if it helps to diagnose the source of the problem, but here is something that might be relevant to # 3.
File > Save Image...
Change image format to BMP/PNG and again JPG
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/6de9c0f9-2d6d-472b-8bd3-8f06fb1300f5)

Drag window's related part to offscreen and it will fix
![resim](https://github.com/clsid2/mpc-hc/assets/3073922/4195c9bc-0cc4-42f9-a923-33d8477c3688)

**Comment by adipose** [comment] 2024-06-04 19:24
> I'm not sure if it helps to diagnose the source of the problem, but here is something that might be relevant to # 3. File > Save Image... Change image format to BMP/PNG and again JPG ![resim](https://private-user-images.githubusercontent.com/3073922/336281395-6de9c0f9-2d6d-472b-8bd3-8f06fb1300f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjkyNDIsIm5iZiI6MTcxNzUyODk0MiwicGF0aCI6Ii8zMDczOTIyLzMzNjI4MTM5NS02ZGU5YzBmOS0yZDZkLTQ3MmItOGJkMy04ZjA2ZmIxMzAwZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTkyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM2NjM3MjllZjc1NTEwYzEwMWExNDgzOTM3NzRkN2I5OWNkMzc1YmZkN2U1OThlNTMyNjM4MGJiZmY1MjcyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k2SiVQ-BARq8Z87NktTGJZgKGhdczDGDfkiO16tWJJE)
> 
> Drag window's related part to offscreen and it will fix ![resim](https://private-user-images.githubusercontent.com/3073922/336281539-4195c9bc-0cc4-42f9-a923-33d8477c3688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjkyNDIsIm5iZiI6MTcxNzUyODk0MiwicGF0aCI6Ii8zMDczOTIyLzMzNjI4MTUzOS00MTk1YzliYy0wY2M0LTQyZjktYTkyMy0zM2Q4NDc3YzM2ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMTkyMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEyMDMwOGRmMWU5MjcyMzlhN2Q3YzFlYjM1MzBkNDYwMjhjNGExMmIyNzI5NmJlYzhkOTRmNzYxODE1MjFjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VI0dFpo_JYjNFsQxieRxRvtbDze4ags1KLLRhgac_DE)

The edit border glitch is fixed now.  I'm not sure what you think this has to do with it, but when I toggle back and forth from PNG to JPEG, "Quality" comes back each time.

**Comment by xLn2** [comment] 2024-06-04 20:00
MPC-HC (64-bit)
---------------
Build information:
    Version:            2.2.1.55 (da42c4d6b)

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    GPU:                Intel(R) HD Graphics 630 (driver version: 31.0.101.2128)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit 120 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      1254

__________

I just guess; moving objects from offscreen to current screen might trigger drawing behavior, at Subtitle downloader window's status bar some drawing is almost having done but seems like something is blocking it. These could be irrelevant issues.

![mpc-hc64_YOqLdXbezM](https://github.com/clsid2/mpc-hc/assets/3073922/7c7b13d7-e028-45a5-abe4-7aa748fd7ccd)

![firefox_Tv0OqIzFai](https://github.com/clsid2/mpc-hc/assets/3073922/84a1e0de-c862-4b59-8e39-63c0a5196d30)

**Comment by adipose** [comment] 2024-06-04 20:12
You can enter a new issue for the save dialog.  But I am unable to reproduce it.

**Comment by adipose** [comment] 2024-06-06 17:33
@clsid2 , I think all issues described here are fixed (except save dialog which has new issue now).

**Closed as completed** 2024-06-06 18:37 UTC
