### ISSUE TITLE
Volume bar does not fill to full length when 100% on dark theme

### ISSUE THREAD

**Issue by Pentaphon** [clsid2/mpc-hc#192] opened 2019-12-29 21:39 UTC
I hope it's not intentional because it always looks like it is 90-95% there when it should be full at 100%.

**Comment by OveR1337XD** [comment] 2019-12-30 00:10
Can confirm it looks like its 95% of volume when on max 100%.
![mpc](https://user-images.githubusercontent.com/3746977/71564479-2a89da00-2aa1-11ea-9818-d7b4f901e4fa.png)

**Comment by THEtomaso** [comment] 2019-12-30 04:05
> it looks like its 95% of volume when on max 100%

..and like 5%, when it's on 0.

**Comment by clsid2** [comment] 2019-12-30 12:44
This is a limitation of the CSliderCtrl class that is currently used to draw the volume slider. Normally the "thumb" where you can click on to move the slider is covering that first and last part of the slider. Some additional modifications are needed to workaround this issue.

**Comment by adipose** [comment] 2019-12-30 18:17
I can confirm the issue.  It was easy to fix, but now I've noticed that the tooltip also assumes some things that don't apply to the modern volume ctrl.  I'm working on it.

**Comment by adipose** [comment] 2019-12-31 08:27
Fixed in https://github.com/clsid2/mpc-hc/pull/198

**Closed as completed** 2020-01-01 01:42 UTC
