### ISSUE TITLE
MPC-HC skips to the end of the video when it encounters a glitch

### ISSUE THREAD

**Issue by Unix-Kernel** [clsid2/mpc-hc#1235] opened 2021-08-01 18:39 UTC
Is there a setting in MPC-HC to continue playing a video when it encounters a glitch that causes the player to skip to the end of the video without having to "remux" it?.

I have tested the same video with the following four players and they skip the glitch and continue playing it : VLC, SMPlayer, PotPlayer, and Nova.

My 12-year old standalone hardware media-player is able to continue playing the video when it encounters a glitch/error.

**Comment by clsid2** [comment] 2021-08-01 21:30
It only skips to the end when the internal codecs say that the file has reached the end. So apparently the error was severe enough it couldn't be skipped over by the splitter.

There is nothing I can do for you without an actual file that shows this behavior.

**Comment by NanaMizukiAnother7** [comment] 2021-08-01 23:08
I think that it might be a duplicate of #1195.

**Comment by clsid2** [comment] 2021-08-01 23:47
No, that is a different issue.

**Comment by Unix-Kernel** [comment] 2021-08-02 01:21
Last week, I tested 34 video-files with glitches in which MPC-1.7, MPC-1.9, and MPC-BE-1.5 would not continue playing the videos after the glitches and skipped directly to the end of the video-file, whereas the other four players that I mentioned including the standalone 12-year-old hardware-player were able to continue playing them after the glitches. 

Apparently, none of the versions of MPC are concerned with the severity of the glitches since it is not able to resume playing them without skipping directly to the end of the video. It sounds to me that the internal codecs for MPC are not able to compensate enough to resume/continue playing as the other five players. 

I only have one video left with a glitch and it is 15.7GB in size and since the glitch is around 2-minutes before the end of the video, mkvtoolnix is able to split that portion into just 332MB, however, since mkvtoolnix actually "remuxes" the file, it also "repairs" the glitch so that all three versions of MPC are able to play the file to the end without skipping; hence, my initial question of: without having to "remux" it. I'm open to suggestions of splitting the mkv-file without any remuxing involved or I can upload the entire 15.7GB file somewhere in split-archives.

**Comment by ale5000-git** [comment] 2021-08-02 09:42
You can split with DGSplit that can be found here: https://web.archive.org/web/20140810142259/http://neuron2.net/dgsplit/dgsplit12.zip

The original site apparently no longer host it (I'm not sure what happened) but fortunately there is Wayback Machine.

**Comment by Unix-Kernel** [comment] 2021-08-02 15:35
@ale5000-git 

Unfortunately, that tool will not work as it outputs only the first chunk with video/audio as all other chunks are empty without any video/audio. I also tried the "segment" method and the output file segments for that are also empty with no video/audio. 

Every tool/utility that I came across and tested processes the file with some type of transcoding/converting/remuxing, etc.

**Comment by clsid2** [comment] 2021-08-02 15:47
Splitting is not really an option when the problem is located at the end of the file.

Do you know the cause of the glitch? Is the file damaged or is it an incomplete downloaded file?

**Comment by Unix-Kernel** [comment] 2021-08-02 16:14
Indeed, if the glitch would have been within the first two minutes of the video instead of the last two minutes than "DGSplit" would have been perfect.

Byte-size damages. All the other 34 video files had damages in different areas of the videos where mvktoolnix's remuxer provided warnings and repaired them in those specific areas. 

When any of those videos are processed/transcoded/remuxed in anyway, then it is no longer an issue for MPC, however, without processing the videos, MPC will skip to the end of the video when it encounters a glitch for "any" video file, whereas those other five players will skip those glitches almost unnoticeable and continues to play them.

**Comment by ale5000-git** [comment] 2021-08-02 17:03
@clsid2: If we pick the first 200MB and the last 200MB and binary merge them, doesn't it at least minimally work?

**Comment by clsid2** [comment] 2021-08-02 17:56
That won't work.

Here is a debug build:
https://www.sendspace.com/file/mboc0o
Run dbgview.exe to generate a log. Maybe it reveal a clue of what happens in the splitter.

To be honest, I am not going to spend a lot of time hunting down this bug, since I probably won't be able to fix it and it involves a damaged file.

**Comment by Unix-Kernel** [comment] 2021-08-02 18:51
That's ok, .....when I started this post, I was only hoping that there was some type of "persistent" setting or configuration that I could change to force MPC in continuing to play the videos when it encounters file-structure issues without having to remux those files; so there is really nothing to fix in MPC's code as the issue is with the files that require re-muxing.

**Comment by ale5000-git** [comment] 2021-08-02 19:07
Every damage is different, there are infinite cases although there may be damaged videos that are similar.
The codec of MPC-HC should already handle many cases and ignore "errors" but probably you got the ones not handled.
Every player may use different codecs (or not it depends how it is programmed) so this is why there are different behaviours.

Without a test files it is really hard discover why.

**Comment by Unix-Kernel** [comment] 2021-08-02 20:44
Ok, that debug build you posted---> 1.9.14.28 (6fa8319df) is able to continue playing the file after encountering the damaged section and it plays the video properly all the way to the end. 
Something is different in that build version from the three that I have. 
I will continue to use this build to test future damaged files.

I just retested with these three versions and they will skip to the end when it encounters the glitch.

MPC-HC 1.9.14 (4488e7d5a)
MPC-HC 1.7.11 (b989276ec)
MPC-BE 1.5.8.6302

**Comment by clsid2** [comment] 2021-08-02 20:59
Test the same version non-debug:
https://github.com/clsid2/mpc-hc/releases/download/1.9.14.14/MPC-HC.1.9.14.28.x64.zip

**Comment by Unix-Kernel** [comment] 2021-08-02 21:07
Yeap, it froze at the glitch and skipped to the end using that one you just posted just like my other three versions of MPC; something is different with the debug version that allows it to continue playing it properly to the end. 
If you figure out what that difference is than that would most likely be the reason.

**Comment by clsid2** [comment] 2021-08-02 23:06
The debug version uses a different compiler for the FFmpeg code. Visual Studio instead of GCC. Plus compiler optimizations are disabled. It doesn't bring us closer to a solution, as I have no clue at all what is different in the compiled code.

Does the dbgview.exe log show anything at the time the glitch should appear?

**Comment by Unix-Kernel** [comment] 2021-08-03 01:32
Nope, I tried it on two different systems and dbgview would not show anything. I also downloaded and tried it with "dbgview64" and "dbgview64a" and nothing would show with those on either system.

I'm just going to use the debug version from now on.

**Comment by clsid2** [comment] 2021-08-03 11:28
Debug build has bad performance, so not recommended for daily usage.

It is weird that dbgview doesn't work.

**Comment by Unix-Kernel** [comment] 2021-08-03 15:44
No  but it does work on a 32bit-OS.

**Comment by clsid2** [comment] 2021-08-03 17:59
I have 64-bit OS myself, and it works fine.

**Comment by Unix-Kernel** [comment] 2021-08-03 21:15
It doesn't matter anyway since this is apparently not a bug. The difference is between the debug version and the non-debug version of MPC and it is obvious that the debug-version is optimized to continue playing damaged files like all the other mentioned software players and a hardware media-player from 2009.

**Comment by clsid2** [comment] 2021-08-03 21:36
No, behavior should theoretically be identical for debug and non-debug builds. Only difference should be performance.

If you ever encounter the problem with a file small enough to upload, then feel free to at it here. Then I can take a look at what exactly goes wrong.

**Closed as completed by clsid2** 2021-08-03 21:36 UTC

**Comment by Unix-Kernel** [comment] 2021-08-03 22:53
Yes, I will provide a small video file when I come across it.

By the way, I had forgotten that I had an application called "Faststone Image Viewer 7.5" which has it's own built-in player but relies and requires external filters; (I only have the lav and haali-media-splitterr) installed so when I use their internal player which uses both of those filters, it is able to continue playing the video properly through the damaged section of the video until the end.
 
I noticed that when using the debug version of MPC that it is also using the (lav and haali-media-splitter) while playing as it is showing both near the taskbar during playback of the video, however, when I use the non-debug versions, it does not use either of those filters. I have tried to manually add the haali to the non-debug version of MPC but that still did not work to force it to play through the damaged area, therefore; based on this conclusion, I believe that it has something to do with the specific video filter that it uses.

**Comment by ale5000-git** [comment] 2021-08-04 12:29
Can it be because you are using a long dead codec (haali-media-splitter)?
Can you reproduce the problem also using LAV splitter + LAV video + LAV audio?

**Comment by Unix-Kernel** [comment] 2021-08-04 15:20
I just tested with the debug version of MPC-1.9.14.28 on a separate second system that had no filters and no codecs and it failed to play through the damaged section because it was not using the haali filter as it did on the first system; therefore, the haali filter was the sole reason the debug version was able to play properly through the damaged section. 

On that same system that has no filters or codecs installed; I tested with "portable versions" of "smplayer-21.1", "potplayer-1.7", and "vlc-3.0" which use their own internal filters/codecs", and they are able to play through the damaged section properly until the end of the video. Unless those three players default to the 12-yr internal haali filter for mkv files, than I have no clue as to which filter they use for mkv files.

The current default filter(s) for MKV files that MPC-1.7, MPC-1.9, and MPC-BE-1.5 uses will not support playing through damaged sections of a video.

I also tested with both MPC-1.7 and MPC-1.9 using "LAV splitter + LAV video + LAV audio" and they will not play through the damaged section of the video.

After all the above testing on the second system, I used the portable version of "FastStone Image Viewer 7.5" configured to use only the latest Lav filters-0.75.1 and it was not able to play through the damaged section of the video, which explains why FastStone is able to play it properly on the first system since I have it configured to use the haali-video-filter and it is able to play properly through the damaged section.

I also use Nova Video Player-5.15.16(2021) on two Firestick-4K which is able to play properly through the damaged section of the video and I doubt the developer is using an old haali filter from 2009. 

If those four players are able to support proper playback of damaged MKV files using the LAV filters than I have no idea as to how they are configured/optimized to do so, and if that is the case, then I don't see any reason as to why MPC could not be configured/optimized to do the same, otherwise, these four players (the 3 portable ones + Nova) are using different filters for MKV files.

**Comment by ale5000-git** [comment] 2021-08-05 06:51
Many times the problem is in the splitter and not in the video decoder although it depends.

Have yout tried the latest portable version of MPC-HC (1.9.14.28) with default settings? (So without changing any options)
This: https://github.com/clsid2/mpc-hc/releases/download/1.9.14.14/MPC-HC.1.9.14.28.x64.zip

While the video is playing go inside MP-HC to Play => Filters => Copy filter list to clipboard
and then paste it here.

**Comment by Unix-Kernel** [comment] 2021-08-05 12:44
That version (1.9.14.28) fails to play through the damaged section as I stated on my previous post, including the other two versions of MPC (1.7 and BE-1.5).

There is no doubt that the reason MPC will not play through damaged areas of any videos is due to the "default filters" that it uses.

MPC-1.9.14.28
Filters currently loaded:
  - Default DirectSound Device
  - Enhanced Video Renderer (custom presenter)
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)

**Comment by ale5000-git** [comment] 2021-08-06 06:46
Try to "Copy filter list to clipboard" also for the debug build where it work so we can see if there is any difference beside Haali.

**Comment by clsid2** [comment] 2021-08-06 11:45
LAV Splitter uses its own unique Matroska parser. Comparing it with other players/splitters is pointless and irrelevant.

Fact is that the file is broken and possibly improving the behavior of the splitter with such damaged files is only possible with a sample file.

**Comment by ale5000-git** [comment] 2021-08-06 12:03
I was asking the filter list to be sure, because if the filter list is the same then may be also a compiler optimization that break code in release build (although it may be unlikely).

**Comment by Unix-Kernel** [comment] 2021-08-06 19:57
Ok, so I managed to get it working on all three versions of MPC (MPC-BE-1.5.8, MPC-1.7.11, and MPC-1.9.14.28-non-debug).

I did so my "unchecking" the "internal matroska filter" from the "Source Filters" list for all three and adding only the "External Filter"---> "Haali Media Splitter".

Now all three versions will play through damaged sections of the video file properly.

**Comment by ale5000-git** [comment] 2021-08-06 22:51
It may work now but since Haali Media Splitter is not updated when you encounter an mkv that it can't play there will be nothing to do.
The only solution is to find a test file that isn't so big then the problem may be fixed.

**Comment by Unix-Kernel** [comment] 2021-08-06 23:54
If/when that occurs, then the file will either require re-muxing or to be replaced from original source because no other software or hardware will be able to play it either. So even if the filter/splitter in MPC was updated to the latest version or the current default one is configured/optimized, it will still not be able to play the file through the damaged section if the structure of the file is beyond playback for any software player.

**Comment by clsid2** [comment] 2021-08-07 12:54
Haali Splitter will fail to play several non-broken files. It for example doesn't support files that contain HEVC video.

**Comment by Unix-Kernel** [comment] 2021-08-07 15:19
I never use 265-HEVC, all my files are 264-AVC.


I forgot to mention that even If I ever decided to start using HEVC, there is a simple work-around using MPC-1.7.11 for exclusive AVC by "disabling" the internal matroska filter and "enabling" the "external" haali media splitter and then using MPC-1.9.14-portable with these settings inverted or as the "default" and then renaming their shortcuts with something like 1.7-AVC and 1.9-265. This can be a combination of one installed and the other one portable since both can run simultaneously with different settings/filters applied/configured. The same combo can be done with MPC-BE-1.5.8-portable. I have tested all three of these and it works perfectly. With this setup, it would not be necessary to go back and forth with changing settings anywhere.

Since the processes for all three run independent of each other, it is also possible that all three can be installed (non-portable) and they can be configured the same way independently, however, I have not tested this since I only have 1.7.11-installed and the other two MPC-1.9/MPC-BE-1.5 as portable. 

Of course this is all if I want to exclusive use only MPC as I also have portable versions of smplayer, potplayer, and vlc that can play HEVC.
