### ISSUE TITLE
Progressive shift using libass with different playback speed

### ISSUE THREAD

**Issue by Hqndler** [clsid2/mpc-hc#2306] opened 2023-11-05 18:44 UTC
Libass rendering works great but only with the playback speed at 1.00, if the video is **speedup/down** the timing for the subtitle won't change causing the shift. The shift remains even if the speed is reset after the speedup/down.

No problem if libass rendering is not used.

**Comment by adipose** [comment] 2023-11-05 20:26
> Libass rendering works great but only with the playback speed at 1.00, if the video is **speedup/down** the timing for the subtitle won't change causing the shift. The shift remains even if the speed is reset after the speedup/down.
> 
> No problem if libass rendering is not used.

I couldn't reproduce this.  I played a video at .125x and the subtitles all appeared at exactly the right time.  Please upload a sample and some screenshots of what happens.

**Comment by Hqndler** [comment] 2023-11-05 21:38
[Sure](https://github.com/clsid2/mpc-hc/assets/69089935/1891e455-9d9d-4a83-892f-2bce7dee9c4c)
Video was at x2 speed (a bit fast but since it's the default value), as you can see subtitles are displayed on top of each other at the end.

**Comment by clsid2** [comment] 2023-11-05 22:42
But they don't seem to be at wrong time?

You need to give a link to a video or subtitle file that trigger the problem.

**Comment by Hqndler** [comment] 2023-11-05 22:47
They were well timed, no problem there. I can open any video and play it at 1.25x (or 0.5 it does'nt matter) and have the problem, it's not specific to this video. I can give you a link to this video if you want.

**Comment by clsid2** [comment] 2023-11-05 22:51
Yes give link

**Comment by Hqndler** [comment] 2023-11-05 22:57
You can find the video [here](https://nyaa.si/view/1645603), I use ep 2 at 17:34, this edit does not render well with xysubfilter and other so a good test for libass.

**Comment by adipose** [comment] 2023-11-06 20:59
Can you confirm what version you are using?  When I followed the same steps, my subtitles go at different speed than yours.

There was a small change to libass for encoding but I doubt that would affect this.

**Comment by Hqndler** [comment] 2023-11-06 21:42
I was using the "MPC-HC.2.1.0.x64.exe" from the [release](https://github.com/clsid2/mpc-hc/releases/tag/2.1.0) section, version 2.1.0 (82c53e9b7).

**Comment by adipose** [comment] 2023-11-07 02:45
Please upload your settings.

**Comment by Hqndler** [comment] 2023-11-07 13:49
I'm assuming you're talking about mpc-hc-setting.reg 
[mpc-hc-settings.zip](https://github.com/clsid2/mpc-hc/files/13280610/mpc-hc-settings.zip)

**Comment by clsid2** [comment] 2023-11-07 13:55
I was able to reproduce the overlapping of lines. But it is a bit inconsistent. It can also happen at normal speed.
Example 1: One line is at correct time, other one ~15s early.
Example 2: One 10 seconds late, one 5 seconds early.
Maybe related to how data was muxed in the file? With timing relative to segment starts.

If I extract the sub and load it as external file, then everything seems to be normal.
[extracted_sub.zip](https://github.com/clsid2/mpc-hc/files/13280697/extracted_sub.zip)

**Comment by clsid2** [comment] 2023-11-07 15:33
Changing rate triggers call to `CSubtitleInputPin::NewSegment()`.
Skipping the invalidation stuff for rate changes might be solution. Checking that now.

Edit: I think it is fixed now. Test build:
https://www.sendspace.com/file/r95b0a

Only weird thing is that the problem did not happen without libass. So I wonder if there still is a hidden issue with invalidating samples when using libass.

**Comment by adipose** [comment] 2023-11-07 19:30
I get an assert on line 238:
`ASSERT(m_lastSegmentStart != tStart);`

This happened when tStart=0

**Comment by clsid2** [comment] 2023-11-07 19:44
Yeah, I already removed the assert

**Comment by adipose** [comment] 2023-11-07 19:47
Here's another question I have, about segments:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/de1c14d9-061f-4ab9-826d-3f860ca20369)

The RLE segment doesn't keep track of the start, stop, and rate?

**Comment by clsid2** [comment] 2023-11-07 20:02
That function is just poorly named. The other formats also don't use the start/stop/rate parameters. They just invalidate/clear stuff.

__super::NewSegment() stores the values.

And segment related timestamp handling is done by the allocator in the video renderer.

**Closed as completed** 2023-11-08 15:33 UTC
Labels: bug
