### ISSUE TITLE
Embedded Subtitles not always loading

### ISSUE THREAD

**Issue by MegaMoses** [clsid2/mpc-hc#1939] opened 2022-12-11 16:41 UTC
It looks like as of MPC-HC 1.9.24.31 embedded subtitles for some files is not working.  Not sure what's making it work for some files and not others though.  I've tried with two different files that each have the same filetype (.mkv) and same embedded sub type (.ass) and gotten two different results.

**Comment by clsid2** [comment] 2022-12-11 18:04
I need a link to a file that gives the problem.

**Comment by bibsp** [comment] 2022-12-13 05:09
I think I got it.
Embedded ass not showing when default style is unchecked (Which is default setting). He is probably using default setting.
![Screenshot (780)](https://user-images.githubusercontent.com/98865389/207231043-7e88d6d2-76dc-4a90-a2e5-a046565fdd6a.png)
If video is playing and you check default style you will not see subtitle. You also need to relaunch player, then the setting takes effect. In earlier versions it took effect immediately.

Again this bug came from recent patches. Last working build was 1.9.24.8
[File link](https://drive.google.com/file/d/1COnzfYMiGHhpS5AQa1CjfyU8qXjZKQzT/view?usp=share_link)

**Comment by clsid2** [comment] 2022-12-13 15:18
Everything is working normally for me, with and without default style. Changing it also applies directly.

So more info is needed. Given that it does not happen with every embedded ASS track, a link to a sample file should really help me to reproduce.

**Comment by bibsp** [comment] 2022-12-13 15:45
Test with MPC VR if that matters.
Test with different settings (Not default). Like my settings. And different monitor resolution.
https://github.com/clsid2/mpc-hc/issues/1932#issuecomment-1340917857

**Comment by clsid2** [comment] 2022-12-13 15:49
Works here with those settings as well. But you can test if changing any of those settings has effect for you.

Please give a sample file.

**Comment by bibsp** [comment] 2022-12-13 15:50
> File link

File link is already given.

**Comment by clsid2** [comment] 2022-12-13 16:02
Sorry didn't see it first time. I can reproduce now.

**Comment by clsid2** [comment] 2022-12-13 21:32
Should be fixed in 1.9.24.35

**Comment by bibsp** [comment] 2022-12-14 04:21
Thanks for ass style improvements.

But one glitch is there.
**Checking** default style immediate effect is glitchy.
Unchecking default style is fine.
_Older MPC was not like this._

[If you can't reproduce, test with above settings.]

https://user-images.githubusercontent.com/98865389/207504616-24fcb97a-5d7a-49a5-8e0c-ce96ab76bb58.mp4

**Comment by clsid2** [comment] 2022-12-14 14:59
Fixed in .38
Hopefully everything is working properly now.

**Closed as completed** 2022-12-16 00:30 UTC
